/*Themes */
insert into fp_theme (theme_id, name, description, theme_small_picture_url, theme_preview_picture_url) values ('kidshome4boy1', 'Kids Home For boy 1', '', 'themes/thumbnails/kidshome4boy1.png', 'themes/thumbnails/kidshome4boy1.png');
insert into fp_theme (theme_id, name, description, theme_small_picture_url, theme_preview_picture_url) values ('kidshome4boy2', 'Kids Home For Boy 2', '', 'themes/thumbnails/kidshome4boy2.png', 'themes/thumbnails/kidshome4boy2.png');
insert into fp_theme (theme_id, name, description, theme_small_picture_url, theme_preview_picture_url) values ('kidshome4boy3', 'Kids Home For Boy 3', '', 'themes/thumbnails/kidshome4boy3.png', 'themes/thumbnails/kidshome4boy3.png');
insert into fp_theme (theme_id, name, description, theme_small_picture_url, theme_preview_picture_url) values ('kidshome4boy4', 'Kids Home For Boy 4', '', 'themes/thumbnails/kidshome4boy4.png', 'themes/thumbnails/kidshome4boy4.png');
insert into fp_theme (theme_id, name, description, theme_small_picture_url, theme_preview_picture_url) values ('kidshome4boy5', 'Kids Home For Boy 5', '', 'themes/thumbnails/kidshome4boy5.png', 'themes/thumbnails/kidshome4boy5.png');
insert into fp_theme (theme_id, name, description, theme_small_picture_url, theme_preview_picture_url) values ('kidshome4boy6', 'Kids Home For Boy 6', '', 'themes/thumbnails/kidshome4boy6.png', 'themes/thumbnails/kidshome4boy6.png');
insert into fp_theme (theme_id, name, description, theme_small_picture_url, theme_preview_picture_url) values ('kidshome4boy7', 'Kids Home For Boy 7', '', 'themes/thumbnails/kidshome4boy7.png', 'themes/thumbnails/kidshome4boy7.png');
insert into fp_theme (theme_id, name, description, theme_small_picture_url, theme_preview_picture_url) values ('kidshome4boy8', 'Kids Home For Boy 8', '', 'themes/thumbnails/kidshome4boy8.png', 'themes/thumbnails/kidshome4boy8.png');
insert into fp_theme (theme_id, name, description, theme_small_picture_url, theme_preview_picture_url) values ('kidshome4boy9', 'Kids Home For Boy 9', '', 'themes/thumbnails/kidshome4boy9.png', 'themes/thumbnails/kidshome4boy9.png');
insert into fp_theme (theme_id, name, description, theme_small_picture_url, theme_preview_picture_url) values ('kidshome4girl1', 'Kids Home For Girl 1', '', 'themes/thumbnails/kidshome4girl1.png', 'themes/thumbnails/kidshome4girl1.png');
insert into fp_theme (theme_id, name, description, theme_small_picture_url, theme_preview_picture_url) values ('kidshome4girl2', 'Kids Home For Girl 2', '', 'themes/thumbnails/kidshome4girl2.png', 'themes/thumbnails/kidshome4girl2.png');
insert into fp_theme (theme_id, name, description, theme_small_picture_url, theme_preview_picture_url) values ('kidshome4girl3', 'Kids Home For Girl 3', '', 'themes/thumbnails/kidshome4girl3.png', 'themes/thumbnails/kidshome4girl3.png');
insert into fp_theme (theme_id, name, description, theme_small_picture_url, theme_preview_picture_url) values ('kidshome4girl4', 'Kids Home For Girl 4', '', 'themes/thumbnails/kidshome4girl4.png', 'themes/thumbnails/kidshome4girl4.png');
insert into fp_theme (theme_id, name, description, theme_small_picture_url, theme_preview_picture_url) values ('kidshome4girl5', 'Kids Home For Girl 5', '', 'themes/thumbnails/kidshome4girl5.png', 'themes/thumbnails/kidshome4girl5.png');
insert into fp_theme (theme_id, name, description, theme_small_picture_url, theme_preview_picture_url) values ('kidshomeBoyipodaqua', 'Kids Home Boy Ipod Aqua', '', 'themes/thumbnails/kidshomeBoyipodaqua.png', 'themes/thumbnails/kidshomeBoyipodaqua.png');
insert into fp_theme (theme_id, name, description, theme_small_picture_url, theme_preview_picture_url) values ('kidshomeBoyipodgrey', 'Kids Home Boy Ipod Grey', '', 'themes/thumbnails/kidshomeBoyipodgrey.png', 'themes/thumbnails/kidshomeBoyipodgrey.png');
insert into fp_theme (theme_id, name, description, theme_small_picture_url, theme_preview_picture_url) values ('kidshomeBoyipodltgreen', 'Kids Home Boy Ipod LtGreen', '', 'themes/thumbnails/kidshomeBoyipodltgreen.png', 'themes/thumbnails/kidshomeBoyipodltgreen.png');
insert into fp_theme (theme_id, name, description, theme_small_picture_url, theme_preview_picture_url) values ('kidshomeBoyipodpurple', 'Kids home Boy Ipod Purple', '', 'themes/thumbnails/kidshomeBoyipodpurple.png', 'themes/thumbnails/kidshomeBoyipodpurple.png');
insert into fp_theme (theme_id, name, description, theme_small_picture_url, theme_preview_picture_url) values ('kidshomeBoyipodwine', 'Kids Home Boy Ipod Wine', '', 'themes/thumbnails/kidshomeBoyipodwine.png', 'themes/thumbnails/kidshomeBoyipodwine.png');

/*Avatars */
insert into profile_photo (profile_photo_id, name, url, description) values (1, 'avtr_balloons2', 'themes/avatars/avtr_balloons2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (2, 'avtr_balloons', 'themes/avatars/avtr_balloons.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (3, 'avtr_baseball2', 'themes/avatars/avtr_baseball2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (4, 'avtr_baseball', 'themes/avatars/avtr_baseball.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (5, 'avtr_basketball2', 'themes/avatars/avtr_basketball2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (6, 'avtr_basketball', 'themes/avatars/avtr_basketball.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (7, 'avtr_bike2', 'themes/avatars/avtr_bike2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (8, 'avtr_bike', 'themes/avatars/avtr_bike.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (9, 'avtr_black_puppy2', 'themes/avatars/avtr_black_puppy2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (10, 'avtr_black_puppy', 'themes/avatars/avtr_black_puppy.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (11, 'avtr_bulldogpuppy2', 'themes/avatars/avtr_bulldogpuppy2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (12, 'avtr_bulldogpuppy', 'themes/avatars/avtr_bulldogpuppy.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (13, 'avtr_butterfly2', 'themes/avatars/avtr_butterfly2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (14, 'avtr_butterfly', 'themes/avatars/avtr_butterfly.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (15, 'avtr_cat2', 'themes/avatars/avtr_cat2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (16, 'avtr_cat', 'themes/avatars/avtr_cat.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (17, 'avtr_chowpup_kitten2', 'themes/avatars/avtr_chowpup_kitten2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (18, 'avtr_chowpup_kitten', 'themes/avatars/avtr_chowpup_kitten.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (19, 'avtr_dirtbike2', 'themes/avatars/avtr_dirtbike2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (20, 'avtr_dirtbike', 'themes/avatars/avtr_dirtbike.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (21, 'avtr_dolphin2', 'themes/avatars/avtr_dolphin2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (22, 'avtr_dolphin', 'themes/avatars/avtr_dolphin.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (23, 'avtr_eagle2', 'themes/avatars/avtr_eagle2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (24, 'avtr_eagle', 'themes/avatars/avtr_eagle.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (25, 'avtr_fall_leaves2', 'themes/avatars/avtr_fall_leaves2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (26, 'avtr_fall_leaves', 'themes/avatars/avtr_fall_leaves.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (27, 'avtr_fall_road2', 'themes/avatars/avtr_fall_road2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (28, 'avtr_fall_road', 'themes/avatars/avtr_fall_road.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (29, 'avtr_farm_sunrise', 'themes/avatars/avtr_farm_sunrise.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (30, 'avtr_fish2', 'themes/avatars/avtr_fish2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (31, 'avtr_fish', 'themes/avatars/avtr_fish.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (32, 'avtr_flower_pink2', 'themes/avatars/avtr_flower_pink2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (33, 'avtr_flower_pink', 'themes/avatars/avtr_flower_pink.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (34, 'avtr_flowers2', 'themes/avatars/avtr_flowers2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (35, 'avtr_flowers3', 'themes/avatars/avtr_flowers3.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (36, 'avtr_flowers', 'themes/avatars/avtr_flowers.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (37, 'avtr_football2', 'themes/avatars/avtr_football2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (38, 'avtr_football', 'themes/avatars/avtr_football.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (39, 'avtr_frog2', 'themes/avatars/avtr_frog2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (40, 'avtr_frog', 'themes/avatars/avtr_frog.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (41, 'avtr_headphones_puppy2', 'themes/avatars/avtr_headphones_puppy2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (42, 'avtr_headphones_puppy', 'themes/avatars/avtr_headphones_puppy.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (43, 'avtr_horse.png', 'themes/avatars/avtr_horse.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (44, 'avtr_kitten2', 'themes/avatars/avtr_kitten2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (45, 'avtr_kitten', 'themes/avatars/avtr_kitten.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (46, 'avtr_kitten_smoke2', 'themes/avatars/avtr_kitten_smoke2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (47, 'avtr_kitten_smoke', 'themes/avatars/avtr_kitten_smoke.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (48, 'avtr_lion2', 'themes/avatars/avtr_lion2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (49, 'avtr_lion', 'themes/avatars/avtr_lion.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (50, 'avtr_lizard2', 'themes/avatars/avtr_lizard2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (51, 'avtr_lizard', 'themes/avatars/avtr_lizard.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (52, 'avtr_mountain2', 'themes/avatars/avtr_mountain2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (53, 'avtr_mountain', 'themes/avatars/avtr_mountain.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (54, 'avtr_puppies_group2', 'themes/avatars/avtr_puppies_group2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (55, 'avtr_puppies_group', 'themes/avatars/avtr_puppies_group.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (56, 'avtr_puppy_kitten2', 'themes/avatars/avtr_puppy_kitten2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (57, 'avtr_puppy_kitten3', 'themes/avatars/avtr_puppy_kitten3.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (58, 'avtr_puppy_kitten', 'themes/avatars/avtr_puppy_kitten.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (59, 'avtr_puppy_white2', 'themes/avatars/avtr_puppy_white2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (60, 'avtr_puppy_white', 'themes/avatars/avtr_puppy_white.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (61, 'avtr_race_flag2', 'themes/avatars/avtr_race_flag2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (62, 'avtr_race_flag', 'themes/avatars/avtr_race_flag.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (63, 'avtr_racecar', 'themes/avatars/avtr_racecar.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (64, 'avtr_skater2', 'themes/avatars/avtr_skater2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (65, 'avtr_skater3', 'themes/avatars/avtr_skater3.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (66, 'avtr_skater', 'themes/avatars/avtr_skater.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (67, 'avtr_skijump2', 'themes/avatars/avtr_skijump2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (68, 'avtr_skijump', 'themes/avatars/avtr_skijump.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (69, 'avtr_snowboarder2', 'themes/avatars/avtr_snowboarder2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (70, 'avtr_snowboarder', 'themes/avatars/avtr_snowboarder.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (71, 'avtr_soccer2', 'themes/avatars/avtr_soccer2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (72, 'avtr_soccer', 'themes/avatars/avtr_soccer.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (73, 'avtr_space2', 'themes/avatars/avtr_space2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (74, 'avtr_space3', 'themes/avatars/avtr_space3.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (75, 'avtr_space', 'themes/avatars/avtr_space.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (76, 'avtr_starfish2', 'themes/avatars/avtr_starfish2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (77, 'avtr_starfish', 'themes/avatars/avtr_starfish.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (78, 'avtr_stars2', 'themes/avatars/avtr_stars2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (79, 'avtr_stars3', 'themes/avatars/avtr_stars3.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (80, 'avtr_stars', 'themes/avatars/avtr_stars.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (81, 'avtr_sunflower2', 'themes/avatars/avtr_sunflower2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (82, 'avtr_sunflower', 'themes/avatars/avtr_sunflower.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (83, 'avtr_sunrise2', 'themes/avatars/avtr_sunrise2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (84, 'avtr_sunrise', 'themes/avatars/avtr_sunrise.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (85, 'avtr_tiger2', 'themes/avatars/avtr_tiger2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (86, 'avtr_tiger', 'themes/avatars/avtr_tiger.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (87, 'avtr_tropic2', 'themes/avatars/avtr_tropic2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (88, 'avtr_tropic', 'themes/avatars/avtr_tropic.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (89, 'avtr_tulips2', 'themes/avatars/avtr_tulips2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (90, 'avtr_tulips', 'themes/avatars/avtr_tulips.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (91, 'avtr_wave2', 'themes/avatars/avtr_wave2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (92, 'avtr_wave', 'themes/avatars/avtr_wave.png', '');







