/*SQL update script for release v1.28 */

/* Ticket #879 - updating the cause table */
update cause set hos_full_txt ="<i>Protects</i>^ the Coast of India! Monkeys, herons, and other animals along the coast of India will soon have new mangrove trees to live in, thanks to ChildName of FiftyP. ChildName donated dollaramount from@ gender share account to the Carbon Fund's Tree Planting Program, which plants trees to protect the shoreline and the many creatures that live there. Mangrove trees drink salt water, so they do well by the sea. Their roots prevents mud and sand from being washed away, reducing damage from storms and allowing other plants to grow. Each mangrove is like an entire forest. Its branches provide food for monkeys and nesting sites for birds, while its tangled roots provide a surface for sponges and a hiding place for young fish." where cause_id=1;
update cause set hos_full_txt ="Builds Forests,^ <i>Creates Habitats</i>! The destruction of forests is a double whammy for the environment. Animals lose their habitats, and the loss of trees which absorb harmful@ gases from airplanes, auto more makes global warming worse. Now ChildName of FiftyP is working to put things right. ChildName Donated dollaramount from gender share account to support Reforestation project that will return trees to land that once held healthy forests. One project, in Louisiana, will create a home for the threatened Louisiana black bear and many other threatened species. Another project will create safe habitats for mammals, birds and reptiles in Central America. The new forest will also pull harmful gases from the air, reducing the effect of global warming throughout the world." where cause_id=2;
update cause set hos_full_txt ="Turns Trash^ <i>into Energy!</i> Garbage landfills are not only stinky. They are a danger to the environment. As the trash decays it releases methane, a gas that contributes@ to global warming. But thanks to ChildName of FiftyP, who donated dollaramount from gender share account, programs in New Hampshire and Massachusetts are using methane to create electricity. The methane is captured from landfills before it can escape into the air, and burned to form less dangerous gases. These gases are used to power turbines, which produce the electricity that heats homes, runs computers, and much more. So ChildName's contribution is helping turn trash into energy, and at the same time protecting the earth from methane's, harmful effects." where cause_id=3;
update cause set hos_full_txt ="Puts the Wind^ <i>to Work!</i> While many people worry about the harmful effects of global warming, ChildName of FiftyP is doing something about it. ChildName donated dollaramount from@ gender share account to support Wind Power, one of the best ways to use nature as a clean energy source. gender contribution will help build wind turbines in Texas, Montana, and Iowa. These big machines, with blades that can be as big as a football field, collect breezes from oceans and open fields and convert them to electricity for businesses and homes. Wind power can reduce our use of oil and other fossil fuels, which contribute to rising temperatures, melting glaciers, and violent storms throughout the world." where cause_id=4;
update cause set hos_full_txt ="Rescues^ Stranded Seals! Seals often climb out of the water to spend time on the beach, stretching out for a nap or warming up in the sun. But sometimes a seal on the beach is stranded - @too sick or injured to get back to the water, or entangled in a fisherman's net. Although bystanders may want to help an animal in distress, a stranded seal needs the aid of a trained scientist, who can guide it back to the water, transport it to an animal hospital, or keep it calm until it's ready to swim again. Because of ChildName of FiftyP, stranded seals will be rescued: ChildName donated dollaramount from gender Share account to help send a marine biologist to the scene. " where cause_id=5;
update cause set hos_full_txt ="Helps Truckers^ Go Green! When long-distance truckers pull into truck stops to spend the night, they keep their engines running to heat or cool the big rig and to keep refrigerated cargo cold. @ Each night the truck burns 10 gallons of diesel fuel, sending harmful gases into the air while parked in a lot. But thanks to ChildName of FiftyP, who donated dollaramount from gender Share account to support the Truck Stop Electrification project, more truckers can turn off their engines at night and use greener electric energy to power the inside of the truck. With more than a million drivers pulling into truck stops each night, the Electrification project can reduce the use of diesel fuel by 10 million gallons a day. Thank you ChildName! " where cause_id=6;
update cause set hos_full_txt ="Makes^ Each Whale Count! The whales off the coast of Massachusetts don't know it, but they're being followed and photographed and protected, thanks to ChildName of FiftyP.@ ChildName donated dollaramount from gender Share account to support the work of biologists who identify individual whales and track them year after year. That's how they learn about the health and safety of these huge mammals that play an important role in our oceans' ecosystems, having an impact on us all! Biologists identify each whale by its distinct natural markings, like freckles or tail patterns, or by scars from injuries it may have received in the past. Each whale is named and then photographed over the course of its lifetime part of the effort to make sure that these ancient species survive. " where cause_id=7;
update cause set hos_full_txt ="Reduces gender^ Carbon Footprint! Each year, every child who takes a bus to school adds about a half-ton of greenhouse gases to the air. It's part of their carbon footprint, and it makes global @ warming worse. But even kids who can't walk or bike to school can go green by supporting programs that cancel out the effect of those harmful bus fumes. That's what ChildName of FiftyP did by donating dollaramount from gender Share account to the School Bus Project. gender donation is supporting programs that promote clean energy like wind and solar-power and plant new forests, which absorb harmful gases. And though ChildName still takes the yellow school bus each day, his donation cancels out the impact of that half-ton of harmful gases that used to be part of his carbon footprint. " where cause_id=8;
update cause set hos_full_txt ="Scores One^for African Kids! African kids are crazy about soccer,
 using anything that can be kicked for the sake of playing the game.
 So soccer is a natural starting point for a program that@ wants to make the world
 a better place for kids. The program is now operating in six African
 countries, where kids from disadvantaged communities come together to learn and
 play soccer - and much more.
 Each week they also learn about good nutrition, sanitation, and staying healthy.
 They take part in activities that teach them leadership, teamwork, and respect for others.
 And they benefit from services such as mobile libraries and community gardens. <br><br>
 Programs like these depend on the help of people around the world - people like ChildName of
 FiftyP, whose donation of dollaramount is making a difference for African kids. " where cause_id=9;
update cause set hos_full_txt ="Captures^Whale Songs! Male humpback whales are known for their
 beautiful, haunting songs, some of the longest in the animal kingdom.
 Members of the same group all sing the same @ song, but a whale will switch to
 a new song if it joins a different group.<br><br>
 Scientists want to learn more about the music of this endangered species:
 how humpbacks use songs to communicate, for example, and when and where they sing.
 Their songs may reveal where they migrate in the fall - which could lead to ways
 to protect them from danger.<br><br>   Thanks to ChildName of FiftyP, the humpback
 melodies will continue to be heard. ChildName donated dollaramount from
 gender Share account to support the work of researchers who record and analyze these surprising songs." where cause_id=10;
update cause set hos_full_txt ="Helps^Red Wolves Go Wild! 
Red wolves were once extinct in the wild, but they're making a comeback with help 
 from ChildName of FiftyP. ChildName donated dollaramount from gender Share account to
 @ support a program that plans to breed red wolves in captivity and release their pups into the wild.
 The wolf pups will be placed in a den of wild wolves that will raise them as their own.
 <br><br>As large predators, wolves help keep the ecosystem in balance. 
 The loss of red wolves throughout the South allowed the deer population to grow, 
 which in turn caused serious damage to plants, trees, and streams.   
 <br><br/>Restoring these rare red wolves to their native habitat can take 20 years or more. 
 Thanks, ChildName, for your help in making it happen!" where cause_id=11;
update cause set hos_full_txt ="Provides^Hope to Hungry Children!
 In many parts of the world, countries affected by drought, floods and conflict face
 a severe shortage of food.
 Children under age two are the hardest hit by @ poor nutrition:
 They lose weight, become weak, and are more likely to get sick.
 <br><br>Babies suffering from severe malnutrition need special foods to help
 them quickly gain weight and build strength.
 Plumpy'nut is a high-energy, ready-to-eat mixture in a squeezable foil pouch.
 It tastes like peanut butter and is packed with the calories and protein that babies need
 to regain their strength.<br><br>Thanks to ChildName of FiftyP and his donation
 of dollaramount, children affected by hunger will get the nutrition support they need." where cause_id=12;
 
 /* updating column 1 text */
 update cause set column1_fiftyp_times = "FiftyP took a stand against global warming today with $amtValue1 donation in support of environmental programs around the world. FiftyP's contribution will go toward planting forests, which suck harmful gases from the air and provide habitats for birds, animals, insects, and other living creatures. The money will also help build Wind Farms fields of modern day windmills that turn blowing breezes into clean energy. Finally, FiftyP will be helping to create electricity from smelly trash, using our landfills to protect the environment!" where cause_id =1;
 update cause set column1_fiftyp_times = "FiftyP took a stand against global warming today with $amtValue1 donation in support of environmental programs around the world. FiftyP's contribution will go toward planting forests, which suck harmful gases from the air and provide habitats for birds, animals, insects, and other living creatures. The money will also help build Wind Farms fields of modern day windmills that turn blowing breezes into clean energy. Finally, FiftyP will be helping to create electricity from smelly trash, using our landfills to protect the environment!" where cause_id =2;
 update cause set column1_fiftyp_times = "FiftyP took a stand against global warming today with $amtValue1 donation in support of environmental programs around the world. FiftyP's contribution will go toward planting forests, which suck harmful gases from the air and provide habitats for birds, animals, insects, and other living creatures. The money will also help build Wind Farms fields of modern day windmills that turn blowing breezes into clean energy. Finally, FiftyP will be helping to create electricity from smelly trash, using our landfills to protect the environment!" where cause_id =3;
 update cause set column1_fiftyp_times = "FiftyP took a stand against global warming today with $amtValue1 donation in support of environmental programs around the world. FiftyP's contribution will go toward planting forests, which suck harmful gases from the air and provide habitats for birds, animals, insects, and other living creatures. The money will also help build Wind Farms fields of modern day windmills that turn blowing breezes into clean energy. Finally, FiftyP will be helping to create electricity from smelly trash, using our landfills to protect the environment!" where cause_id =4;
 
 update cause set column1_fiftyp_times = "FiftyP is making a difference! This month it will donate $amtValue1 to support programs that protect marine mammals and prevent global warming. FiftyP's contribution will save seals that get stranded on beaches and help biologists identify and keep track of whales a first step in making sure that they're healthy and safe. The money will also aid efforts to slow climate change, by making it possible for truckers to use less fuel and by supporting projects that create clean energy and plant new forests."  where cause_id =5;
 update cause set column1_fiftyp_times = "FiftyP is making a difference! This month it will donate $amtValue1 to support programs that protect marine mammals and prevent global warming. FiftyP's contribution will save seals that get stranded on beaches and help biologists identify and keep track of whales a first step in making sure that they're healthy and safe. The money will also aid efforts to slow climate change, by making it possible for truckers to use less fuel and by supporting projects that create clean energy and plant new forests."  where cause_id =6;
 update cause set column1_fiftyp_times = "FiftyP is making a difference! This month it will donate $amtValue1 to support programs that protect marine mammals and prevent global warming. FiftyP's contribution will save seals that get stranded on beaches and help biologists identify and keep track of whales a first step in making sure that they're healthy and safe. The money will also aid efforts to slow climate change, by making it possible for truckers to use less fuel and by supporting projects that create clean energy and plant new forests."  where cause_id =7;
 update cause set column1_fiftyp_times = "FiftyP is making a difference! This month it will donate $amtValue1 to support programs that protect marine mammals and prevent global warming. FiftyP's contribution will save seals that get stranded on beaches and help biologists identify and keep track of whales a first step in making sure that they're healthy and safe. The money will also aid efforts to slow climate change, by making it possible for truckers to use less fuel and by supporting projects that create clean energy and plant new forests."  where cause_id =8;
 
 update cause set column1_fiftyp_times = "FiftyP is making a difference! This month it will donate $amtValue1 to support programs that protect endangered animals and brighten the lives of children in need. FiftyP's contribution will return endangered red wolves to the wild and help biologists study the amazing songs of male humpback whales.  The money will also provide a lifesaving food to severely undernourished babies, and will bring soccer, education, and important community services to African children and their families."  where cause_id =9;
 update cause set column1_fiftyp_times = "FiftyP is making a difference! This month it will donate $amtValue1 to support programs that protect endangered animals and brighten the lives of children in need. FiftyP's contribution will return endangered red wolves to the wild and help biologists study the amazing songs of male humpback whales.  The money will also provide a lifesaving food to severely undernourished babies, and will bring soccer, education, and important community services to African children and their families."  where cause_id =10;
 update cause set column1_fiftyp_times = "FiftyP is making a difference! This month it will donate $amtValue1 to support programs that protect endangered animals and brighten the lives of children in need. FiftyP's contribution will return endangered red wolves to the wild and help biologists study the amazing songs of male humpback whales.  The money will also provide a lifesaving food to severely undernourished babies, and will bring soccer, education, and important community services to African children and their families."  where cause_id =11;
 update cause set column1_fiftyp_times = "FiftyP is making a difference! This month it will donate $amtValue1 to support programs that protect endangered animals and brighten the lives of children in need. FiftyP's contribution will return endangered red wolves to the wild and help biologists study the amazing songs of male humpback whales.  The money will also provide a lifesaving food to severely undernourished babies, and will bring soccer, education, and important community services to African children and their families."  where cause_id =12;
 
 

/* End of ticket #879 */

/* #915 */
ALTER TABLE product ADD inProgress_isDeleted TINYINT NOT NULL DEFAULT '0';

/* #909 */
DROP TABLE `mail_sent`;

/* #986 */
ALTER TABLE child_profile ADD spent_default_share_amount TINYINT NOT NULL DEFAULT '0';

