-- SQL update script for release v0.12.
-- delete the data from child_mm_gift related to mm_gift_occasion
delete from child_mm_gift;

insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('4','Dance recital','');
insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('4','Music recital','');
insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('4','Theatrical performance','');
insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('4','Winning Sports season','');
insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('4','Horse show','');
insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('4','Gymnastics competition','');
insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('4','Science Fair award','');
insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('4','Spelling Bee finalist','');
insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('4','Excellent Report Card','');
insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('4','School award','');
insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('4','Driver''s license','');
insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('4','Martial Arts belt','');


delete from mm_gift_occasion where mm_gift_occasion.mm_gift_occasion_category_id = '4';

insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('4','Dance recital','');
insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('4','Music recital','');
insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('4','Theatrical performance','');
insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('4','Winning Sports season','');
insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('4','Horse show','');
insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('4','Gymnastics competition','');
insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('4','Science Fair award','');
insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('4','Spelling Bee finalist','');
insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('4','Excellent Report Card','');
insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('4','School award','');
insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('4','Driver''s license','');
insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('4','Martial Arts belt','');


delete from mm_gift_occasion where mm_gift_occasion.mm_gift_occasion_category_id = '2';

insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('2','Birthday','');
insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('2','Graduation','');
insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('2','Moving Up (to new school level)','');
insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('2','Sweet Sixteen','');
insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('2','Quinceañera','');
insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('2','First Communion','');
insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('2','Confirmation','');
insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('2','Bar/Bat Mitzvah','');

delete from mm_gift_occasion where mm_gift_occasion.mm_gift_occasion_category_id = '1';

insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('1','Christmas','');
insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('1','Chanukah','');
insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('1','Ramadan (Eid al-Fitr)','');
insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('1','Diwali','');
insert into `mm_gift_occasion`(`mm_gift_occasion_category_id`,`name`,`description`) values('1','Valentine''s day','');


/* Data for the `tip` table  (Records 1 - 42) */
delete from tip where tip.tip_section_id = 'SAVE_SECTION';

delete from tip where tip.tip_section_id = 'MONEY_MACHINE_SECTION';

delete from tip where tip.tip_section_id = 'SPEND_SECTION';

delete from tip where tip.tip_section_id = 'SHARE_SECTION';

INSERT INTO `tip` (`tip_section_id`, `tip_data`) VALUES
  ('SAVE_SECTION', 'DID YOU KNOW ... that some old dollar bills get recycled into stationery?'),
  ('SAVE_SECTION', 'DID YOU KNOW ... that \"paper\" money is mostly made of cotton?'),
  ('SAVE_SECTION', 'DID YOU KNOW ... that coins can last for 30 years, while paper money wears out after a year-and-a-half?'),
  ('SPEND_SECTION', 'STALK THE SALES   Are you a clothes hound? Try shopping at the end of the season, when prices are lowest.'),
  ('SPEND_SECTION', 'STALK THE SALES   Have your eye on something special? Ask a salesperson when it''s going on sale.'),
  ('SPEND_SECTION', 'STALK THE SALES   Check newspaper ads for sales. Most stores run big sales on the holiday...every holiday.'),
  ('SPEND_SECTION', 'STALK THE SALES   Shop during bonus hours during a sale (usually early morning) and use coupons to bring prices way down.'),
  ('SPEND_SECTION', 'THINK AGAIN   Don''t be impressed by big markdowns. Decide if an item is worth its current price...that''s what makes it a good deal.'),
  ('SPEND_SECTION', 'THINK AGAIN   Don''t feel pressured to buy just because stuff is on sale. Another sale will come along soon.'),
  ('SPEND_SECTION', 'HIDDEN COSTS    Look for extra charges...like fees for assembling or delivering an item. They''re all part of the total cost.   '),
  ('SPEND_SECTION', 'HIDDEN COSTS   Are batteries included? How about the special glue and paint for that model airplane? Add these in when figuring out the real cost.'),
  ('SPEND_SECTION', 'YOU''RE THE BOSS   Don''t let friends talk you into buying something because it''s \"cool\".'),
  ('SPEND_SECTION', 'YOU''RE THE BOSS   Don''t let salespeople pressure you into making a decision. Take as much time as you need.'),
  ('SPEND_SECTION', 'THE WAITING GAME    DVDs get a lot cheaper just a few months after their release.'),
  ('SPEND_SECTION', 'THE WAITING GAME   Most books first come out in hardcover, but waiting for the paperback version cuts the cost in half.'),
  ('SPEND_SECTION', 'THE WAITING GAME    Find out if that electronic gadget you''re eyeing is coming out with a new model. You may want to wait for the latest version...or to grab the discount on the older model when the new one comes out.'),
  ('SPEND_SECTION', 'KNOW YOURSELF   If you can''t help spending everything in your pocket, carry only the money you''ll reasonably need.'),
  ('SPEND_SECTION', 'KNOW YOURSELF    If hanging out at the mall always turns into a shopping spree, find other ways to spend time with friends.'),
  ('SPEND_SECTION', 'DOLLARS & SENSE   Love to buy clothes? You''ll find good deals on brand names at outlet stores and second-hand shops.'),
  ('SPEND_SECTION', 'DOLLARS & SENSE    Bored with your old electronic games? Trade them in at a video game store.'),
  ('SPEND_SECTION', 'DOLLARS & SENSE   Shopping for a camera or other electronic gadget? Choose a model with features you''ll use, instead of paying for fancy bells and whistles.'),
  ('SPEND_SECTION', 'SCOPE IT OUT  If you''re looking for a big-ticket item like a game system, check the Internet for product reviews and price comparisons.'),
  ('MONEY_MACHINE_SECTION', 'I.D. A NEED   Look around the house for projects crying out to be done. If soccer balls rain down when you open the sports closet, offer to put everything in its place.'),
  ('MONEY_MACHINE_SECTION', 'I.D. A NEED   Parties require lots of work...and workers. If your parents are planning an event, offer to make invitations...decorate the house...hang up the guests'' coats.'),
  ('MONEY_MACHINE_SECTION', 'I.D. A NEED Think of services your neighbors might need. Could you rake the lawns, walk the dogs, help out at a garage sale?'),
  ('MONEY_MACHINE_SECTION', 'STRUT YOUR STUFF   Your business won''t grow if people don''t know. Tell friends and neighbors and ask your parents to help spread the word. Ask satisfied customers to recommend you.'),
  ('MONEY_MACHINE_SECTION', 'STRUT YOUR STUFF   Write a friendly e-mail describing your product or service, and send it to everyone who might be interested. Ask them to forward it to others.'),
  ('MONEY_MACHINE_SECTION', 'STRUT YOUR STUFF    Work with a parent to create an eye-catching flyer describing your business and how you can be reached. Post it on bulletin boards around town.'),
  ('MONEY_MACHINE_SECTION', 'BE A PRO   The first rule of business: Keep your customers happy. Be on time, wear a smile, and give it all you''ve got.'),
  ('MONEY_MACHINE_SECTION', 'BE A PRO   If your job involves caring for a pet or watering plants, ask a parent or friend to step in if you can''t make it.'),
  ('MONEY_MACHINE_SECTION', 'HOLIDAY BU$INE$$ IDEAS   Offer a service to make holidays less hectic: Wrap presents...help decorate...be a mother''s helper.'),
  ('MONEY_MACHINE_SECTION', 'HOLIDAY BU$INE$$ IDEAS   If friends or neighbors will be away for the holiday, offer to: Feed pets or walk dogs...water plants...take in mail and newspapers.'),
  ('MONEY_MACHINE_SECTION', 'HOLIDAY BU$INE$$ IDEAS   If friends or family are holding a holiday party, offer to: Take photos or video...look after young kids...help set up or clean up...create table centerpieces...be a DJ.'),
  ('MONEY_MACHINE_SECTION', 'HOLIDAY BU$INE$$ IDEAS   Create one-of-a-kind holiday cards and gift items to sell, such as jewelry, pet portraits, personalized tee shirts.'),
  ('MONEY_MACHINE_SECTION', 'HOLIDAY BU$INE$$ IDEAS   Take orders for your special brownies or muffins and deliver them fresh for holiday celebrations.'),
  ('MONEY_MACHINE_SECTION', 'EXTREME MONEY   Most millionaires own their own business...and started it from scratch. '),
  ('MONEY_MACHINE_SECTION', 'EXTREME MONEY   Four out of five millionaires weren''t born rich...they built their own fortunes.'),
  ('MONEY_MACHINE_SECTION', 'EXTREME MONEY   Want to be a millionaire? You can, if you start early and save regularly. Check out Millionaire Mania on your home page to see how.'),
  ('MONEY_MACHINE_SECTION', 'EXTREME MONEY   Think it takes a lifetime to earn a million? Some kids do it before they turn 20, by coming up with a great idea and working hard.'),
  ('SHARE_SECTION', 'DID YOU KNOW ... that 13 million U.S. teens volunteer 2 billion hours a year?'),
  ('SHARE_SECTION', 'DID YOU KNOW ... that charitable organizations get 75% of their funds from individuals, not from companies?'),
  ('SHARE_SECTION', 'DID YOU KNOW ... that even a few dollars can save lives in many parts of the world? ');
-- Updating Gift Cards Script
DELETE FROM child_spend;
DELETE FROM product_order;
DELETE FROM product;
DELETE FROM product_category;
DELETE FROM store;
ALTER TABLE product CHANGE COLUMN `description` `choose_desc` TEXT;
ALTER TABLE product MODIFY COLUMN `choose_desc` TEXT,
 	  ADD COLUMN `disclamer_desc` TEXT NOT NULL AFTER `choose_desc`,
 	  ADD COLUMN `confirm_desc` TEXT NOT NULL AFTER `disclamer_desc`;

insert into product_category (name, description) values ('Books/Music/Entertainment','');
insert into product_category (name, description) values ('Clothing','');
insert into product_category (name, description) values ('Computer/Video Games','');
insert into product_category (name, description) values ('Food','');
insert into product_category (name, description) values ('Shoes','');
insert into product_category (name, description) values ('Sports','');

insert into store (name, description, url, company_url, company_logo_url) values ('store 1', '', '','', '');

select @storeId := (select store_id from store where name = 'store 1');

select @booksCategoryId := (select product_category_id from product_category where name = 'Books/Music/Entertainment');

insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @booksCategoryId, 10, "Wal-Mart","Give the Wal-Mart Gift Card any time of year. It's the ideal gift for family and friends, because they can choose exactly what they wish.<ul><li>For purchases at Walmart.com and in U.S. Wal-Mart stores </li><br><li>For purchases by SAM'S Club members in U.S. SAM'S Club stores and at Samsclub.com</li><br><li>	In stores, present the card at checkout</li> <br><li>	Online, enter card number and PIN (on back of card) during checkout. The PIN provides secure online shopping. </li><br><li>	As you make purchases, the card amount decreases. Add to card balance anytime in a Wal-Mart store. (You cannot add to the balance online.)</li><br><li>	Check your card balance in stores or online</li></ul>","FiftyP, Inc. doing business as www.fiftyp.com, is not affiliated with Wal-Mart Stores, Inc.  The services, products or activities of FiftyP, Inc. are neither endorsed nor sponsored by Wal-Mart Stores, Inc.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/walmart.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @booksCategoryId, 25, "Wal-Mart", "Give the Wal-Mart Gift Card any time of year. It's the ideal gift for family and friends, because they can choose exactly what they wish.<ul><li>For purchases at Walmart.com and in U.S. Wal-Mart stores </li><br><li>For purchases by SAM'S Club members in U.S. SAM'S Club stores and at Samsclub.com</li><br><li>	In stores, present the card at checkout</li> <br><li>	Online, enter card number and PIN (on back of card) during checkout. The PIN provides secure online shopping. </li><br><li>	As you make purchases, the card amount decreases. Add to card balance anytime in a Wal-Mart store. (You cannot add to the balance online.)</li><br><li>	Check your card balance in stores or online</li></ul>","FiftyP, Inc. doing business as www.fiftyp.com, is not affiliated with Wal-Mart Stores, Inc.  The services, products or activities of FiftyP, Inc. are neither endorsed nor sponsored by Wal-Mart Stores, Inc.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/walmart.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @booksCategoryId, 50, "Wal-Mart", "Give the Wal-Mart Gift Card any time of year. It's the ideal gift for family and friends, because they can choose exactly what they wish.<ul><li>For purchases at Walmart.com and in U.S. Wal-Mart stores </li><br><li>For purchases by SAM'S Club members in U.S. SAM'S Club stores and at Samsclub.com</li><br><li>	In stores, present the card at checkout</li> <br><li>	Online, enter card number and PIN (on back of card) during checkout. The PIN provides secure online shopping. </li><br><li>	As you make purchases, the card amount decreases. Add to card balance anytime in a Wal-Mart store. (You cannot add to the balance online.)</li><br><li>	Check your card balance in stores or online</li></ul>","FiftyP, Inc. doing business as www.fiftyp.com, is not affiliated with Wal-Mart Stores, Inc.  The services, products or activities of FiftyP, Inc. are neither endorsed nor sponsored by Wal-Mart Stores, Inc.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/walmart.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @booksCategoryId, 10, "Chili's&#174;", "Tastes from all over the world in just one card<br>Chili's<br>Chili's Grills Like No Place Else&#174;, featuring favorites like Big Mouth Burgers and Baby Back Ribs. Molten Chocolate Cake dictates that diners leave room for dessert! Over 750 restaurants nationwide.<br>Macaroni Grill<br>Romano's Macaroni Grill&#174; prepares Italian favorites that includes pasta, veal, steaks, chicken, seafood, and pizza baked in a wood-burning oven. Over 200 restaurants nationwide.<br>On the Border<br>Enjoy such traditional Mexican favorites as our Border Sampler - a tempting array of chicken quesadillas, beef nachos and chicken flautas. Or customized specialties like our Guacamole Live! -- a craveable guacamole prepared tableside.<br>Maggiano's<br>Come to Maggiano's&#174; and celebrate the time-honored tradition of family-sized portions of Southern Italian dishes served with the warm and genuine hospitality reminiscent of Little Italy.","Brinker Restaurant Corporation (""Brinker""), hereby grants to the above named party, permission to utilize, upon receipt from Brinker, a copy of the registered trademark or logo Chili's, Macaroni Grill, On The Border, Cozymel's, Maggiano's, Corner Bakery.  The permission granted herein is limited solely for use by you in connection with your incentive program.<br>Accordingly, we ask that you observe the following guidelines:<ol> <li>Please distinguish our trademark within text, using all CAPITALS, italics or color;</li> <li>Avoid distorting the trademark;</li><li>	Do not alter the graphic design or the color;</li><li>	Always use the proper registration symbol &#174;, as it helps us to protect this valuable asset.</li></ol> Please note that Brinker may revoke this authorization at any time in its sole discretion.  No waiver, estoppel or course of dealing is to be implied or construed from this letter.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/chilis.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @booksCategoryId, 25, "Chili's&#174;", "Tastes from all over the world in just one card<br>Chili's<br>Chili's Grills Like No Place Else&#174;, featuring favorites like Big Mouth Burgers and Baby Back Ribs. Molten Chocolate Cake dictates that diners leave room for dessert! Over 750 restaurants nationwide.<br>Macaroni Grill<br>Romano's Macaroni Grill&#174; prepares Italian favorites that includes pasta, veal, steaks, chicken, seafood, and pizza baked in a wood-burning oven. Over 200 restaurants nationwide.<br>On the Border<br>Enjoy such traditional Mexican favorites as our Border Sampler - a tempting array of chicken quesadillas, beef nachos and chicken flautas. Or customized specialties like our Guacamole Live! -- a craveable guacamole prepared tableside.<br>Maggiano's<br>Come to Maggiano's&#174; and celebrate the time-honored tradition of family-sized portions of Southern Italian dishes served with the warm and genuine hospitality reminiscent of Little Italy.","Brinker Restaurant Corporation (""Brinker""), hereby grants to the above named party, permission to utilize, upon receipt from Brinker, a copy of the registered trademark or logo Chili's, Macaroni Grill, On The Border, Cozymel's, Maggiano's, Corner Bakery.  The permission granted herein is limited solely for use by you in connection with your incentive program.<br>Accordingly, we ask that you observe the following guidelines:<ol> <li>Please distinguish our trademark within text, using all CAPITALS, italics or color;</li> <li>Avoid distorting the trademark;</li><li>	Do not alter the graphic design or the color;</li><li>	Always use the proper registration symbol &#174;, as it helps us to protect this valuable asset.</li></ol> Please note that Brinker may revoke this authorization at any time in its sole discretion.  No waiver, estoppel or course of dealing is to be implied or construed from this letter.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/chilis.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @booksCategoryId, 10, "T.G.I. Friday's&#174;", "At Friday's&#174; Restaurants, we have great food and drinks in an atmosphere that lets you relax and have fun. Now we've stuffed all that fun into a little card, and it's ready for you to give to anyone at anytime. Share the fun of T.G.I. Friday's&#174; restaurants.<br>For a restaurant near you, visit our location listing at www.fridays.com ","Your T.G.I. Friday's&#174; Gift Card may only be used for making purchases at participating T.G.I. Friday's&#174; restaurants.  It cannot be redeemed for cash or applied as payment to any account unless required by law.  This Card is not reloadable.  This card will only be replaced if an original sales receipt, valid identification, and original card number are provided.  Use of the card constitutes acceptance of these terms and conditions.  <br>For more information about the T.G.I. Friday's&#174; Gift Card visit www.fridays.com ","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/tgif.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @booksCategoryId, 25, "T.G.I. Friday's&#174;", "At Friday's&#174; Restaurants, we have great food and drinks in an atmosphere that lets you relax and have fun. Now we've stuffed all that fun into a little card, and it's ready for you to give to anyone at anytime. Share the fun of T.G.I. Friday's&#174; restaurants.<br>For a restaurant near you, visit our location listing at www.fridays.com ","Your T.G.I. Friday's&#174; Gift Card may only be used for making purchases at participating T.G.I. Friday's&#174; restaurants.  It cannot be redeemed for cash or applied as payment to any account unless required by law.  This Card is not reloadable.  This card will only be replaced if an original sales receipt, valid identification, and original card number are provided.  Use of the card constitutes acceptance of these terms and conditions.  <br>For more information about the T.G.I. Friday's&#174; Gift Card visit www.fridays.com ","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/tgif.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @booksCategoryId, 50, "T.G.I. Friday's&#174;","At Friday's&#174; Restaurants, we have great food and drinks in an atmosphere that lets you relax and have fun. Now we've stuffed all that fun into a little card, and it's ready for you to give to anyone at anytime. Share the fun of T.G.I. Friday's&#174; restaurants.<br>For a restaurant near you, visit our location listing at www.fridays.com ","Your T.G.I. Friday's&#174; Gift Card may only be used for making purchases at participating T.G.I. Friday's&#174; restaurants.  It cannot be redeemed for cash or applied as payment to any account unless required by law.  This Card is not reloadable.  This card will only be replaced if an original sales receipt, valid identification, and original card number are provided.  Use of the card constitutes acceptance of these terms and conditions.  <br>For more information about the T.G.I. Friday's&#174; Gift Card visit www.fridays.com ","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/tgif.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @booksCategoryId, 25, "Dave & Buster's", "Give the gift of fun with a Dave & Buster's gift card. Dave & Buster's offers a one-of-a-kind dining adventure - the ultimate experience to Eat, Drink & Play. It's the ultimate incentive or reward for anyone who loves a good time. ","Dave & Buster's is not a sponsor or co-sponsor of this promotion.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/db.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @booksCategoryId, 50, "Dave & Buster's", "Give the gift of fun with a Dave & Buster's gift card. Dave & Buster's offers a one-of-a-kind dining adventure - the ultimate experience to Eat, Drink & Play. It's the ultimate incentive or reward for anyone who loves a good time. ","Dave & Buster's is not a sponsor or co-sponsor of this promotion.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/db.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @booksCategoryId, 10, "AMC Theatres", "Everyone loves the movies! AMC gift cards are a versatile gift card offering flexibility between movie tickets and concessions. AMC is one of the world's largest theatrical exhibition companies and with more than 300 theatres in 30 states it is the choice of over 200 million moviegoers each year.","AMC is not a sponsor or co-sponsor of this promotion.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/amc.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @booksCategoryId, 25, "AMC Theatres", "Everyone loves the movies! AMC gift cards are a versatile gift card offering flexibility between movie tickets and concessions. AMC is one of the world's largest theatrical exhibition companies and with more than 300 theatres in 30 states it is the choice of over 200 million moviegoers each year.","AMC is not a sponsor or co-sponsor of this promotion.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/amc.png');

select @clothingCategoryId := (select product_category_id from product_category where name = 'Clothing');

insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @clothingCategoryId, 10, "Wal-Mart", "Give the Wal-Mart Gift Card any time of year. It's the ideal gift for family and friends, because they can choose exactly what they wish.<ul><li>For purchases at Walmart.com and in U.S. Wal-Mart stores </li><br><li>For purchases by SAM'S Club members in U.S. SAM'S Club stores and at Samsclub.com</li><br><li>	In stores, present the card at checkout</li> <br><li>	Online, enter card number and PIN (on back of card) during checkout. The PIN provides secure online shopping. </li><br><li>	As you make purchases, the card amount decreases. Add to card balance anytime in a Wal-Mart store. (You cannot add to the balance online.)</li><br><li>	Check your card balance in stores or online</li></ul>","FiftyP, Inc. doing business as www.fiftyp.com, is not affiliated with Wal-Mart Stores, Inc.  The services, products or activities of FiftyP, Inc. are neither endorsed nor sponsored by Wal-Mart Stores, Inc.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/walmart.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @clothingCategoryId, 25, "Wal-Mart", "Give the Wal-Mart Gift Card any time of year. It's the ideal gift for family and friends, because they can choose exactly what they wish.<ul><li>For purchases at Walmart.com and in U.S. Wal-Mart stores </li><br><li>For purchases by SAM'S Club members in U.S. SAM'S Club stores and at Samsclub.com</li><br><li>	In stores, present the card at checkout</li> <br><li>	Online, enter card number and PIN (on back of card) during checkout. The PIN provides secure online shopping. </li><br><li>	As you make purchases, the card amount decreases. Add to card balance anytime in a Wal-Mart store. (You cannot add to the balance online.)</li><br><li>	Check your card balance in stores or online</li></ul>","FiftyP, Inc. doing business as www.fiftyp.com, is not affiliated with Wal-Mart Stores, Inc.  The services, products or activities of FiftyP, Inc. are neither endorsed nor sponsored by Wal-Mart Stores, Inc.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/walmart.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @clothingCategoryId, 50, "Wal-Mart", "Give the Wal-Mart Gift Card any time of year. It's the ideal gift for family and friends, because they can choose exactly what they wish.<ul><li>For purchases at Walmart.com and in U.S. Wal-Mart stores </li><br><li>For purchases by SAM'S Club members in U.S. SAM'S Club stores and at Samsclub.com</li><br><li>	In stores, present the card at checkout</li> <br><li>	Online, enter card number and PIN (on back of card) during checkout. The PIN provides secure online shopping. </li><br><li>	As you make purchases, the card amount decreases. Add to card balance anytime in a Wal-Mart store. (You cannot add to the balance online.)</li><br><li>	Check your card balance in stores or online</li></ul>","FiftyP, Inc. doing business as www.fiftyp.com, is not affiliated with Wal-Mart Stores, Inc.  The services, products or activities of FiftyP, Inc. are neither endorsed nor sponsored by Wal-Mart Stores, Inc.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/walmart.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @clothingCategoryId, 25, "Nike", "The Nike Gift Card may be used at NIKETOWN, NikeFactoryStores, NikeWomen, Nike store locations and at NikeStore.com, the official place to buy Nike product online. Choose a high-performance gift from our complete collection of Nike footwear, apparel, accessories and equipment. Register online to join our Members Only store for exclusive access to rare, limited-edition shoes. Not to mention FREE RETURNS on all orders.   The Nike Gift Card may also be used on NIKEiD.com, where you can create individually customized shoes, apparel, equipment and exclusive products.  Equip yourself with the Nike Gift Card.","Nike is not a sponsor or co-sponsor of this program." ,"This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/nike.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @clothingCategoryId, 50, "Nike", "The Nike Gift Card may be used at NIKETOWN, NikeFactoryStores, NikeWomen, Nike store locations and at NikeStore.com, the official place to buy Nike product online. Choose a high-performance gift from our complete collection of Nike footwear, apparel, accessories and equipment. Register online to join our Members Only store for exclusive access to rare, limited-edition shoes. Not to mention FREE RETURNS on all orders.   The Nike Gift Card may also be used on NIKEiD.com, where you can create individually customized shoes, apparel, equipment and exclusive products.  Equip yourself with the Nike Gift Card.","Nike is not a sponsor or co-sponsor of this program." ,"This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/nike.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @clothingCategoryId, 100, "Nike", "The Nike Gift Card may be used at NIKETOWN, NikeFactoryStores, NikeWomen, Nike store locations and at NikeStore.com, the official place to buy Nike product online. Choose a high-performance gift from our complete collection of Nike footwear, apparel, accessories and equipment. Register online to join our Members Only store for exclusive access to rare, limited-edition shoes. Not to mention FREE RETURNS on all orders.   The Nike Gift Card may also be used on NIKEiD.com, where you can create individually customized shoes, apparel, equipment and exclusive products.  Equip yourself with the Nike Gift Card.","Nike is not a sponsor or co-sponsor of this program." ,"This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/nike.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @clothingCategoryId, 25, "GAP", "Gap has everything you need to express your personal style.  From jeans and T's to khakis and oxfords, you'll find great clothes and accessories for men, women, boys, girls and baby.  For the nearest store, call 1-800-GAP-STYLE, or shop our always open Gap.com store.","Gap giftcards can be used at all Gap locations and online at Gap.com.  Only 2 giftcards are redeemable per online transaction.  Gap giftcards are redeemable for merchandise only and cannot be replaced if lost or stolen.  For questions regarding Gap giftcards, please call 1-800-GAP-STYLE","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/gap.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @clothingCategoryId, 50, "GAP", "Gap has everything you need to express your personal style.  From jeans and T's to khakis and oxfords, you'll find great clothes and accessories for men, women, boys, girls and baby.  For the nearest store, call 1-800-GAP-STYLE, or shop our always open Gap.com store.","Gap giftcards can be used at all Gap locations and online at Gap.com.  Only 2 giftcards are redeemable per online transaction.  Gap giftcards are redeemable for merchandise only and cannot be replaced if lost or stolen.  For questions regarding Gap giftcards, please call 1-800-GAP-STYLE","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/gap.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @clothingCategoryId, 10, "Foot Locker", "The perfect fit in a card!<br>The Foot Locker Gift Card lets you shop at more than 3,000 stores across the country and get the athletic brands you love. Hard-core athletes will find the latest developments in technologically enhanced footwear and apparel, and the fashion-conscious will be able to score with the most popular trends in athletic fashion.<br>Valid also at Lady Foot Locker, Champs, and Kid's Foot Locker locations. ","Foot Locker is not a sponsor or co-sponsor of this promotion.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/footLocker.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @clothingCategoryId, 25, "Foot Locker", "The perfect fit in a card!<br>The Foot Locker Gift Card lets you shop at more than 3,000 stores across the country and get the athletic brands you love. Hard-core athletes will find the latest developments in technologically enhanced footwear and apparel, and the fashion-conscious will be able to score with the most popular trends in athletic fashion.<br>Valid also at Lady Foot Locker, Champs, and Kid's Foot Locker locations. ","Foot Locker is not a sponsor or co-sponsor of this promotion.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/footLocker.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @clothingCategoryId, 50, "Foot Locker", "The perfect fit in a card!<br>The Foot Locker Gift Card lets you shop at more than 3,000 stores across the country and get the athletic brands you love. Hard-core athletes will find the latest developments in technologically enhanced footwear and apparel, and the fashion-conscious will be able to score with the most popular trends in athletic fashion.<br>Valid also at Lady Foot Locker, Champs, and Kid's Foot Locker locations. ","Foot Locker is not a sponsor or co-sponsor of this promotion.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/footLocker.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @clothingCategoryId, 100, "Foot Locker", "The perfect fit in a card!<br>The Foot Locker Gift Card lets you shop at more than 3,000 stores across the country and get the athletic brands you love. Hard-core athletes will find the latest developments in technologically enhanced footwear and apparel, and the fashion-conscious will be able to score with the most popular trends in athletic fashion.<br>Valid also at Lady Foot Locker, Champs, and Kid's Foot Locker locations. ","Foot Locker is not a sponsor or co-sponsor of this promotion.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/footLocker.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @clothingCategoryId, 25, "Eddie Bauer&#174;", "Eddie Bauer is a specialty retailer of casual apparel and accessories for men and women that reflect today's modern outdoor lifestyle. Established in 1920 by legendary outdoorsman Eddie Bauer, the company stands for high quality, innovation, style and customer service. Eddie Bauer offers 3 convenient ways to shop; catalog, stores or online.","Your acceptance of this gift card constitutes your agreement to these terms and conditions.  This card is redeemable in U.S. and Canada for merchandise at all participating Eddie Bauer stores, Eddie Bauer Outlet stores, catalogs or online.  Cards cannot be redeemed for cash, or applied as payment to any credit card account or for prior or pending purchases.  Eddie Bauer is not responsible for lost or stolen cards, or for funds used without your knowledge or other unauthorized use.  Refunds or replacements may be issued with original proof of purchase or as required by law.  This card is issued in U.S. funds by Eddie Bauer Services LLC.<br><br>Additional Terms & Conditions:<br>Eddie Bauer&#174; is not affiliated with [Program Name] or [Client Name].  Use of the Eddie Bauer name and logo require written approval prior to use.<br>Or<br>Eddie Bauer&#174; is not a sponsor of this promotion.  Fulfillment of gift cards will be done through (Company).  Gift Cards are subject to all terms and conditions printed on the gift cards and are subject to change at Eddie Bauer's sole discretions.<br>Eddie Bauer is a specialty retailer of casual apparel and accessories for men and women that reflect today's modern outdoor lifestyle. Established in 1920 by legendary outdoorsman Eddie Bauer, the company stands for high quality, innovation, style and customer service. Eddie Bauer offers 3 convenient ways to shop; catalog, stores or online.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/eddieBauer.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @clothingCategoryId, 50, "Eddie Bauer&#174;", "Eddie Bauer is a specialty retailer of casual apparel and accessories for men and women that reflect today's modern outdoor lifestyle. Established in 1920 by legendary outdoorsman Eddie Bauer, the company stands for high quality, innovation, style and customer service. Eddie Bauer offers 3 convenient ways to shop; catalog, stores or online.","Your acceptance of this gift card constitutes your agreement to these terms and conditions.  This card is redeemable in U.S. and Canada for merchandise at all participating Eddie Bauer stores, Eddie Bauer Outlet stores, catalogs or online.  Cards cannot be redeemed for cash, or applied as payment to any credit card account or for prior or pending purchases.  Eddie Bauer is not responsible for lost or stolen cards, or for funds used without your knowledge or other unauthorized use.  Refunds or replacements may be issued with original proof of purchase or as required by law.  This card is issued in U.S. funds by Eddie Bauer Services LLC.<br><br>Additional Terms & Conditions:<br>Eddie Bauer&#174; is not affiliated with [Program Name] or [Client Name].  Use of the Eddie Bauer name and logo require written approval prior to use.<br>Or<br>Eddie Bauer&#174; is not a sponsor of this promotion.  Fulfillment of gift cards will be done through (Company).  Gift Cards are subject to all terms and conditions printed on the gift cards and are subject to change at Eddie Bauer's sole discretions.<br>Eddie Bauer is a specialty retailer of casual apparel and accessories for men and women that reflect today's modern outdoor lifestyle. Established in 1920 by legendary outdoorsman Eddie Bauer, the company stands for high quality, innovation, style and customer service. Eddie Bauer offers 3 convenient ways to shop; catalog, stores or online.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/eddieBauer.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @clothingCategoryId, 25, "Banana Republic", "Exceptional quality, luxury fabrics and refined tailoring define Banana Republic's signature style.  Every season, you'll find a new collection of well-designed clothing and accessories for men and women. ","Banana Republic giftcards can be used at all Banana Republic locations and online at BananaRepublic.com.  Only 2 giftcards are redeemable per online transaction.  Banana Republic giftcards are redeemable for merchandise only and cannot be replaced if lost or stolen.  For questions regarding Banana Republic giftcards, please call 1-888-BR-STYLE.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/bananaRepublic.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @clothingCategoryId, 50, "Banana Republic", "Exceptional quality, luxury fabrics and refined tailoring define Banana Republic's signature style.  Every season, you'll find a new collection of well-designed clothing and accessories for men and women. ","Banana Republic giftcards can be used at all Banana Republic locations and online at BananaRepublic.com.  Only 2 giftcards are redeemable per online transaction.  Banana Republic giftcards are redeemable for merchandise only and cannot be replaced if lost or stolen.  For questions regarding Banana Republic giftcards, please call 1-888-BR-STYLE.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/bananaRepublic.png');


select @computerCategoryId := (select product_category_id from product_category where name = 'Computer/Video Games');

insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @computerCategoryId, 10, "Wal-Mart", "Give the Wal-Mart Gift Card any time of year. It's the ideal gift for family and friends, because they can choose exactly what they wish.<ul><li>For purchases at Walmart.com and in U.S. Wal-Mart stores </li><br><li>For purchases by SAM'S Club members in U.S. SAM'S Club stores and at Samsclub.com</li><br><li>	In stores, present the card at checkout</li> <br><li>	Online, enter card number and PIN (on back of card) during checkout. The PIN provides secure online shopping. </li><br><li>	As you make purchases, the card amount decreases. Add to card balance anytime in a Wal-Mart store. (You cannot add to the balance online.)</li><br><li>	Check your card balance in stores or online</li></ul>","FiftyP, Inc. doing business as www.fiftyp.com, is not affiliated with Wal-Mart Stores, Inc.  The services, products or activities of FiftyP, Inc. are neither endorsed nor sponsored by Wal-Mart Stores, Inc.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/walmart.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @computerCategoryId, 25, "Wal-Mart", "Give the Wal-Mart Gift Card any time of year. It's the ideal gift for family and friends, because they can choose exactly what they wish.<ul><li>For purchases at Walmart.com and in U.S. Wal-Mart stores </li><br><li>For purchases by SAM'S Club members in U.S. SAM'S Club stores and at Samsclub.com</li><br><li>	In stores, present the card at checkout</li> <br><li>	Online, enter card number and PIN (on back of card) during checkout. The PIN provides secure online shopping. </li><br><li>	As you make purchases, the card amount decreases. Add to card balance anytime in a Wal-Mart store. (You cannot add to the balance online.)</li><br><li>	Check your card balance in stores or online</li></ul>","FiftyP, Inc. doing business as www.fiftyp.com, is not affiliated with Wal-Mart Stores, Inc.  The services, products or activities of FiftyP, Inc. are neither endorsed nor sponsored by Wal-Mart Stores, Inc.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/walmart.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @computerCategoryId, 50, "Wal-Mart", "Give the Wal-Mart Gift Card any time of year. It's the ideal gift for family and friends, because they can choose exactly what they wish.<ul><li>For purchases at Walmart.com and in U.S. Wal-Mart stores </li><br><li>For purchases by SAM'S Club members in U.S. SAM'S Club stores and at Samsclub.com</li><br><li>	In stores, present the card at checkout</li> <br><li>	Online, enter card number and PIN (on back of card) during checkout. The PIN provides secure online shopping. </li><br><li>	As you make purchases, the card amount decreases. Add to card balance anytime in a Wal-Mart store. (You cannot add to the balance online.)</li><br><li>	Check your card balance in stores or online</li></ul>","FiftyP, Inc. doing business as www.fiftyp.com, is not affiliated with Wal-Mart Stores, Inc.  The services, products or activities of FiftyP, Inc. are neither endorsed nor sponsored by Wal-Mart Stores, Inc.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/walmart.png');


select @foodCategoryId := (select product_category_id from product_category where name = 'Food');

insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @foodCategoryId, 25, "The Panera Card&#174;", "Panera Bread&#174; offers made to order sandwiches, salads and soups that are served with artisan breads baked daily in each bakery-cafe. Panera provides a warm and welcoming environment for breakfast, lunch and dinner with free Wi-Fi available in most locations.  To find the closest Panera Bread to you, go to <ahref=""www.panerabread.com"">www.panerabread.com.</a>","Panera Bread is not a sponsor or co-sponsor of this program.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/panera.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @foodCategoryId, 50, "The Panera Card&#174;", "Panera Bread&#174; offers made to order sandwiches, salads and soups that are served with artisan breads baked daily in each bakery-cafe. Panera provides a warm and welcoming environment for breakfast, lunch and dinner with free Wi-Fi available in most locations.  To find the closest Panera Bread to you, go to <ahref=""www.panerabread.com"">www.panerabread.com.</a>","Panera Bread is not a sponsor or co-sponsor of this program.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/panera.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @foodCategoryId, 10, "Chili's&#174;", "Tastes from all over the world in just one card<br>Chili's<br>Chili's Grills Like No Place Else&#174;, featuring favorites like Big Mouth Burgers and Baby Back Ribs. Molten Chocolate Cake dictates that diners leave room for dessert! Over 750 restaurants nationwide.<br>Macaroni Grill<br>Romano's Macaroni Grill&#174; prepares Italian favorites that includes pasta, veal, steaks, chicken, seafood, and pizza baked in a wood-burning oven. Over 200 restaurants nationwide.<br>On the Border<br>Enjoy such traditional Mexican favorites as our Border Sampler - a tempting array of chicken quesadillas, beef nachos and chicken flautas. Or customized specialties like our Guacamole Live! -- a craveable guacamole prepared tableside.<br>Maggiano's<br>Come to Maggiano's&#174; and celebrate the time-honored tradition of family-sized portions of Southern Italian dishes served with the warm and genuine hospitality reminiscent of Little Italy.","Brinker Restaurant Corporation (""Brinker""), hereby grants to the above named party, permission to utilize, upon receipt from Brinker, a copy of the registered trademark or logo Chili's, Macaroni Grill, On The Border, Cozymel's, Maggiano's, Corner Bakery.  The permission granted herein is limited solely for use by you in connection with your incentive program.<br>Accordingly, we ask that you observe the following guidelines:<ol> <li>Please distinguish our trademark within text, using all CAPITALS, italics or color;</li> <li>Avoid distorting the trademark;</li><li>	Do not alter the graphic design or the color;</li><li>	Always use the proper registration symbol &#174;, as it helps us to protect this valuable asset.</li></ol> Please note that Brinker may revoke this authorization at any time in its sole discretion.  No waiver, estoppel or course of dealing is to be implied or construed from this letter.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/chilis.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @foodCategoryId, 25, "Chili's&#174;","Tastes from all over the world in just one card<br>Chili's<br>Chili's Grills Like No Place Else&#174;, featuring favorites like Big Mouth Burgers and Baby Back Ribs. Molten Chocolate Cake dictates that diners leave room for dessert! Over 750 restaurants nationwide.<br>Macaroni Grill<br>Romano's Macaroni Grill&#174; prepares Italian favorites that includes pasta, veal, steaks, chicken, seafood, and pizza baked in a wood-burning oven. Over 200 restaurants nationwide.<br>On the Border<br>Enjoy such traditional Mexican favorites as our Border Sampler - a tempting array of chicken quesadillas, beef nachos and chicken flautas. Or customized specialties like our Guacamole Live! -- a craveable guacamole prepared tableside.<br>Maggiano's<br>Come to Maggiano's&#174; and celebrate the time-honored tradition of family-sized portions of Southern Italian dishes served with the warm and genuine hospitality reminiscent of Little Italy.","Brinker Restaurant Corporation (""Brinker""), hereby grants to the above named party, permission to utilize, upon receipt from Brinker, a copy of the registered trademark or logo Chili's, Macaroni Grill, On The Border, Cozymel's, Maggiano's, Corner Bakery.  The permission granted herein is limited solely for use by you in connection with your incentive program.<br>Accordingly, we ask that you observe the following guidelines:<ol> <li>Please distinguish our trademark within text, using all CAPITALS, italics or color;</li> <li>Avoid distorting the trademark;</li><li>	Do not alter the graphic design or the color;</li><li>	Always use the proper registration symbol &#174;, as it helps us to protect this valuable asset.</li></ol> Please note that Brinker may revoke this authorization at any time in its sole discretion.  No waiver, estoppel or course of dealing is to be implied or construed from this letter.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/chilis.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @foodCategoryId, 10, "Uno Chicago Grill&#174; Gift Card", "Good Friends, Great Food.<br>That's the Chicago Way.<br>Uno Chicago Grill&#174; invented Chicago-style Deep Dish Pizza in 1943 and has been making friends ever since. The restaurant's fresh menu now offers much more than its famous pizza, including an array of signature dishes, healthy fare, grilled favorites and a contemporary drink list. Guests keep coming back to this inviting Chi-town classic thanks to its attentive service and indulgent menu.<br>Uno currently has over 200 full-service restaurants in 32 states, the District of Columbia and Puerto Rico.","Uno Chicago Grill is not a sponsor or co-sponsor of this promotion.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/uno.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @foodCategoryId, 25, "Uno Chicago Grill&#174; Gift Card", "Good Friends, Great Food.<br>That's the Chicago Way.<br>Uno Chicago Grill&#174; invented Chicago-style Deep Dish Pizza in 1943 and has been making friends ever since. The restaurant's fresh menu now offers much more than its famous pizza, including an array of signature dishes, healthy fare, grilled favorites and a contemporary drink list. Guests keep coming back to this inviting Chi-town classic thanks to its attentive service and indulgent menu.<br>Uno currently has over 200 full-service restaurants in 32 states, the District of Columbia and Puerto Rico.","Uno Chicago Grill is not a sponsor or co-sponsor of this promotion.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/uno.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @foodCategoryId, 50, "Uno Chicago Grill&#174; Gift Card", "Good Friends, Great Food.<br>That's the Chicago Way.<br>Uno Chicago Grill&#174; invented Chicago-style Deep Dish Pizza in 1943 and has been making friends ever since. The restaurant's fresh menu now offers much more than its famous pizza, including an array of signature dishes, healthy fare, grilled favorites and a contemporary drink list. Guests keep coming back to this inviting Chi-town classic thanks to its attentive service and indulgent menu.<br>Uno currently has over 200 full-service restaurants in 32 states, the District of Columbia and Puerto Rico.","Uno Chicago Grill is not a sponsor or co-sponsor of this promotion.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/uno.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @foodCategoryId, 10, "T.G.I. Friday's&#174;", "At Friday's&#174; Restaurants, we have great food and drinks in an atmosphere that lets you relax and have fun. Now we've stuffed all that fun into a little card, and it's ready for you to give to anyone at anytime. Share the fun of T.G.I. Friday's&#174; restaurants.<br>For a restaurant near you, visit our location listing at www.fridays.com ","Your T.G.I. Friday's&#174; Gift Card may only be used for making purchases at participating T.G.I. Friday's&#174; restaurants.  It cannot be redeemed for cash or applied as payment to any account unless required by law.  This Card is not reloadable.  This card will only be replaced if an original sales receipt, valid identification, and original card number are provided.  Use of the card constitutes acceptance of these terms and conditions.  <br>For more information about the T.G.I. Friday's&#174; Gift Card visit www.fridays.com ","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/tgif.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @foodCategoryId, 25, "T.G.I. Friday's&#174;", "At Friday's&#174; Restaurants, we have great food and drinks in an atmosphere that lets you relax and have fun. Now we've stuffed all that fun into a little card, and it's ready for you to give to anyone at anytime. Share the fun of T.G.I. Friday's&#174; restaurants.<br>For a restaurant near you, visit our location listing at www.fridays.com ","Your T.G.I. Friday's&#174; Gift Card may only be used for making purchases at participating T.G.I. Friday's&#174; restaurants.  It cannot be redeemed for cash or applied as payment to any account unless required by law.  This Card is not reloadable.  This card will only be replaced if an original sales receipt, valid identification, and original card number are provided.  Use of the card constitutes acceptance of these terms and conditions.  <br>For more information about the T.G.I. Friday's&#174; Gift Card visit www.fridays.com ","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/tgif.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @foodCategoryId, 50, "T.G.I. Friday's&#174;", "At Friday's&#174; Restaurants, we have great food and drinks in an atmosphere that lets you relax and have fun. Now we've stuffed all that fun into a little card, and it's ready for you to give to anyone at anytime. Share the fun of T.G.I. Friday's&#174; restaurants.<br>For a restaurant near you, visit our location listing at www.fridays.com ","Your T.G.I. Friday's&#174; Gift Card may only be used for making purchases at participating T.G.I. Friday's&#174; restaurants.  It cannot be redeemed for cash or applied as payment to any account unless required by law.  This Card is not reloadable.  This card will only be replaced if an original sales receipt, valid identification, and original card number are provided.  Use of the card constitutes acceptance of these terms and conditions.  <br>For more information about the T.G.I. Friday's&#174; Gift Card visit www.fridays.com ","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/tgif.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @foodCategoryId, 25, "Dave & Buster's", "Give the gift of fun with a Dave & Buster's gift card. Dave & Buster's offers a one-of-a-kind dining adventure - the ultimate experience to Eat, Drink & Play. It's the ultimate incentive or reward for anyone who loves a good time. ","Dave & Buster's is not a sponsor or co-sponsor of this promotion.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/db.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @foodCategoryId, 50, "Dave & Buster's", "Give the gift of fun with a Dave & Buster's gift card. Dave & Buster's offers a one-of-a-kind dining adventure - the ultimate experience to Eat, Drink & Play. It's the ultimate incentive or reward for anyone who loves a good time. ","Dave & Buster's is not a sponsor or co-sponsor of this promotion.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/db.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @foodCategoryId, 10, "Outback Steakhouse", "Satisfy your crave at Outback Steakhouse with juicy steaks, fresh seafood and our signature Bloomin' Onion&#174;. For more than 20 years, Outback has perfected big, bold ""come back flavors"". Crave On.<br>The Outback Steakhouse Gift Card is also valid for use at all Bonefish Grill, Carrabba's Italian Grill, Fleming's Prime Steakhouse & Wine Bar, Cheeseburger in Paradise and Blue Coral locations. ","Outback Steakhouse is not a sponsor or co-sponsor of this promotion.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/outBack.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @foodCategoryId, 25, "Outback Steakhouse", "Satisfy your crave at Outback Steakhouse with juicy steaks, fresh seafood and our signature Bloomin' Onion&#174;. For more than 20 years, Outback has perfected big, bold ""come back flavors"". Crave On.<br>The Outback Steakhouse Gift Card is also valid for use at all Bonefish Grill, Carrabba's Italian Grill, Fleming's Prime Steakhouse & Wine Bar, Cheeseburger in Paradise and Blue Coral locations. ","Outback Steakhouse is not a sponsor or co-sponsor of this promotion.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/outBack.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @foodCategoryId, 50, "Outback Steakhouse", "Satisfy your crave at Outback Steakhouse with juicy steaks, fresh seafood and our signature Bloomin' Onion&#174;. For more than 20 years, Outback has perfected big, bold ""come back flavors"". Crave On.<br>The Outback Steakhouse Gift Card is also valid for use at all Bonefish Grill, Carrabba's Italian Grill, Fleming's Prime Steakhouse & Wine Bar, Cheeseburger in Paradise and Blue Coral locations. ","Outback Steakhouse is not a sponsor or co-sponsor of this promotion.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/outBack.png');

select @shoesCategoryId := (select product_category_id from product_category where name = 'Shoes');

insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @shoesCategoryId, 10, "Wal-Mart", "Give the Wal-Mart Gift Card any time of year. It's the ideal gift for family and friends, because they can choose exactly what they wish.<ul><li>For purchases at Walmart.com and in U.S. Wal-Mart stores </li><br><li>For purchases by SAM'S Club members in U.S. SAM'S Club stores and at Samsclub.com</li><br><li>	In stores, present the card at checkout</li> <br><li>	Online, enter card number and PIN (on back of card) during checkout. The PIN provides secure online shopping. </li><br><li>	As you make purchases, the card amount decreases. Add to card balance anytime in a Wal-Mart store. (You cannot add to the balance online.)</li><br><li>	Check your card balance in stores or online</li></ul>","FiftyP, Inc. doing business as www.fiftyp.com, is not affiliated with Wal-Mart Stores, Inc.  The services, products or activities of FiftyP, Inc. are neither endorsed nor sponsored by Wal-Mart Stores, Inc.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/walmart.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @shoesCategoryId, 25, "Wal-Mart", "Give the Wal-Mart Gift Card any time of year. It's the ideal gift for family and friends, because they can choose exactly what they wish.<ul><li>For purchases at Walmart.com and in U.S. Wal-Mart stores </li><br><li>For purchases by SAM'S Club members in U.S. SAM'S Club stores and at Samsclub.com</li><br><li>	In stores, present the card at checkout</li> <br><li>	Online, enter card number and PIN (on back of card) during checkout. The PIN provides secure online shopping. </li><br><li>	As you make purchases, the card amount decreases. Add to card balance anytime in a Wal-Mart store. (You cannot add to the balance online.)</li><br><li>	Check your card balance in stores or online</li></ul>","FiftyP, Inc. doing business as www.fiftyp.com, is not affiliated with Wal-Mart Stores, Inc.  The services, products or activities of FiftyP, Inc. are neither endorsed nor sponsored by Wal-Mart Stores, Inc.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/walmart.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @shoesCategoryId, 50, "Wal-Mart", "Give the Wal-Mart Gift Card any time of year. It's the ideal gift for family and friends, because they can choose exactly what they wish.<ul><li>For purchases at Walmart.com and in U.S. Wal-Mart stores </li><br><li>For purchases by SAM'S Club members in U.S. SAM'S Club stores and at Samsclub.com</li><br><li>	In stores, present the card at checkout</li> <br><li>	Online, enter card number and PIN (on back of card) during checkout. The PIN provides secure online shopping. </li><br><li>	As you make purchases, the card amount decreases. Add to card balance anytime in a Wal-Mart store. (You cannot add to the balance online.)</li><br><li>	Check your card balance in stores or online</li></ul>","FiftyP, Inc. doing business as www.fiftyp.com, is not affiliated with Wal-Mart Stores, Inc.  The services, products or activities of FiftyP, Inc. are neither endorsed nor sponsored by Wal-Mart Stores, Inc.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/walmart.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @shoesCategoryId, 25, "Nike", "The Nike Gift Card may be used at NIKETOWN, NikeFactoryStores, NikeWomen, Nike store locations and at NikeStore.com, the official place to buy Nike product online. Choose a high-performance gift from our complete collection of Nike footwear, apparel, accessories and equipment. Register online to join our Members Only store for exclusive access to rare, limited-edition shoes. Not to mention FREE RETURNS on all orders.   The Nike Gift Card may also be used on NIKEiD.com, where you can create individually customized shoes, apparel, equipment and exclusive products.  Equip yourself with the Nike Gift Card.","Nike is not a sponsor or co-sponsor of this program." ,"This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/nike.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @shoesCategoryId, 50, "Nike", "The Nike Gift Card may be used at NIKETOWN, NikeFactoryStores, NikeWomen, Nike store locations and at NikeStore.com, the official place to buy Nike product online. Choose a high-performance gift from our complete collection of Nike footwear, apparel, accessories and equipment. Register online to join our Members Only store for exclusive access to rare, limited-edition shoes. Not to mention FREE RETURNS on all orders.   The Nike Gift Card may also be used on NIKEiD.com, where you can create individually customized shoes, apparel, equipment and exclusive products.  Equip yourself with the Nike Gift Card.","Nike is not a sponsor or co-sponsor of this program." ,"This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/nike.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @shoesCategoryId, 100, "Nike", "The Nike Gift Card may be used at NIKETOWN, NikeFactoryStores, NikeWomen, Nike store locations and at NikeStore.com, the official place to buy Nike product online. Choose a high-performance gift from our complete collection of Nike footwear, apparel, accessories and equipment. Register online to join our Members Only store for exclusive access to rare, limited-edition shoes. Not to mention FREE RETURNS on all orders.   The Nike Gift Card may also be used on NIKEiD.com, where you can create individually customized shoes, apparel, equipment and exclusive products.  Equip yourself with the Nike Gift Card.","Nike is not a sponsor or co-sponsor of this program." ,"This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/nike.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @shoesCategoryId, 25, "GAP", "Gap has everything you need to express your personal style.  From jeans and T's to khakis and oxfords, you'll find great clothes and accessories for men, women, boys, girls and baby.  For the nearest store, call 1-800-GAP-STYLE, or shop our always open Gap.com store.","Gap giftcards can be used at all Gap locations and online at Gap.com.  Only 2 giftcards are redeemable per online transaction.  Gap giftcards are redeemable for merchandise only and cannot be replaced if lost or stolen.  For questions regarding Gap giftcards, please call 1-800-GAP-STYLE","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/gap.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @shoesCategoryId, 50, "GAP", "Gap has everything you need to express your personal style.  From jeans and T's to khakis and oxfords, you'll find great clothes and accessories for men, women, boys, girls and baby.  For the nearest store, call 1-800-GAP-STYLE, or shop our always open Gap.com store.","Gap giftcards can be used at all Gap locations and online at Gap.com.  Only 2 giftcards are redeemable per online transaction.  Gap giftcards are redeemable for merchandise only and cannot be replaced if lost or stolen.  For questions regarding Gap giftcards, please call 1-800-GAP-STYLE","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/gap.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @shoesCategoryId, 10, "Foot Locker", "The perfect fit in a card!<br>The Foot Locker Gift Card lets you shop at more than 3,000 stores across the country and get the athletic brands you love. Hard-core athletes will find the latest developments in technologically enhanced footwear and apparel, and the fashion-conscious will be able to score with the most popular trends in athletic fashion.<br>Valid also at Lady Foot Locker, Champs, and Kid's Foot Locker locations.","Foot Locker is not a sponsor or co-sponsor of this promotion.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/footLocker.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @shoesCategoryId, 25, "Foot Locker", "The perfect fit in a card!<br>The Foot Locker Gift Card lets you shop at more than 3,000 stores across the country and get the athletic brands you love. Hard-core athletes will find the latest developments in technologically enhanced footwear and apparel, and the fashion-conscious will be able to score with the most popular trends in athletic fashion.<br>Valid also at Lady Foot Locker, Champs, and Kid's Foot Locker locations. ","Foot Locker is not a sponsor or co-sponsor of this promotion.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/footLocker.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @shoesCategoryId, 50, "Foot Locker", "The perfect fit in a card!<br>The Foot Locker Gift Card lets you shop at more than 3,000 stores across the country and get the athletic brands you love. Hard-core athletes will find the latest developments in technologically enhanced footwear and apparel, and the fashion-conscious will be able to score with the most popular trends in athletic fashion.<br>Valid also at Lady Foot Locker, Champs, and Kid's Foot Locker locations. ","Foot Locker is not a sponsor or co-sponsor of this promotion.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/footLocker.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @shoesCategoryId, 100,"Foot Locker","The perfect fit in a card!<br>The Foot Locker Gift Card lets you shop at more than 3,000 stores across the country and get the athletic brands you love. Hard-core athletes will find the latest developments in technologically enhanced footwear and apparel, and the fashion-conscious will be able to score with the most popular trends in athletic fashion.<br>Valid also at Lady Foot Locker, Champs, and Kid's Foot Locker locations. ","Foot Locker is not a sponsor or co-sponsor of this promotion.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/footLocker.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @shoesCategoryId, 25, "Banana Republic", "Exceptional quality, luxury fabrics and refined tailoring define Banana Republic's signature style.  Every season, you'll find a new collection of well-designed clothing and accessories for men and women. ","Banana Republic giftcards can be used at all Banana Republic locations and online at BananaRepublic.com.  Only 2 giftcards are redeemable per online transaction.  Banana Republic giftcards are redeemable for merchandise only and cannot be replaced if lost or stolen.  For questions regarding Banana Republic giftcards, please call 1-888-BR-STYLE.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/bananaRepublic.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @shoesCategoryId, 50, "Banana Republic","Exceptional quality, luxury fabrics and refined tailoring define Banana Republic's signature style.  Every season, you'll find a new collection of well-designed clothing and accessories for men and women. ","Banana Republic giftcards can be used at all Banana Republic locations and online at BananaRepublic.com.  Only 2 giftcards are redeemable per online transaction.  Banana Republic giftcards are redeemable for merchandise only and cannot be replaced if lost or stolen.  For questions regarding Banana Republic giftcards, please call 1-888-BR-STYLE.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/bananaRepublic.png');

select @sportsCategoryId := (select product_category_id from product_category where name = 'Sports');

insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @sportsCategoryId, 10, "Wal-Mart", "Give the Wal-Mart Gift Card any time of year. It's the ideal gift for family and friends, because they can choose exactly what they wish.<ul><li>For purchases at Walmart.com and in U.S. Wal-Mart stores </li><br><li>For purchases by SAM'S Club members in U.S. SAM'S Club stores and at Samsclub.com</li><br><li>	In stores, present the card at checkout</li> <br><li>	Online, enter card number and PIN (on back of card) during checkout. The PIN provides secure online shopping. </li><br><li>	As you make purchases, the card amount decreases. Add to card balance anytime in a Wal-Mart store. (You cannot add to the balance online.)</li><br><li>	Check your card balance in stores or online</li></ul>","FiftyP, Inc. doing business as www.fiftyp.com, is not affiliated with Wal-Mart Stores, Inc.  The services, products or activities of FiftyP, Inc. are neither endorsed nor sponsored by Wal-Mart Stores, Inc.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/walmart.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @sportsCategoryId, 25, "Wal-Mart", "Give the Wal-Mart Gift Card any time of year. It's the ideal gift for family and friends, because they can choose exactly what they wish.<ul><li>For purchases at Walmart.com and in U.S. Wal-Mart stores </li><br><li>For purchases by SAM'S Club members in U.S. SAM'S Club stores and at Samsclub.com</li><br><li>	In stores, present the card at checkout</li> <br><li>	Online, enter card number and PIN (on back of card) during checkout. The PIN provides secure online shopping. </li><br><li>	As you make purchases, the card amount decreases. Add to card balance anytime in a Wal-Mart store. (You cannot add to the balance online.)</li><br><li>	Check your card balance in stores or online</li></ul>","FiftyP, Inc. doing business as www.fiftyp.com, is not affiliated with Wal-Mart Stores, Inc.  The services, products or activities of FiftyP, Inc. are neither endorsed nor sponsored by Wal-Mart Stores, Inc.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/walmart.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @sportsCategoryId, 50, "Wal-Mart", "Give the Wal-Mart Gift Card any time of year. It's the ideal gift for family and friends, because they can choose exactly what they wish.<ul><li>For purchases at Walmart.com and in U.S. Wal-Mart stores </li><br><li>For purchases by SAM'S Club members in U.S. SAM'S Club stores and at Samsclub.com</li><br><li>	In stores, present the card at checkout</li> <br><li>	Online, enter card number and PIN (on back of card) during checkout. The PIN provides secure online shopping. </li><br><li>	As you make purchases, the card amount decreases. Add to card balance anytime in a Wal-Mart store. (You cannot add to the balance online.)</li><br><li>	Check your card balance in stores or online</li></ul>","FiftyP, Inc. doing business as www.fiftyp.com, is not affiliated with Wal-Mart Stores, Inc.  The services, products or activities of FiftyP, Inc. are neither endorsed nor sponsored by Wal-Mart Stores, Inc.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/walmart.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @sportsCategoryId, 25, "Nike", "The Nike Gift Card may be used at NIKETOWN, NikeFactoryStores, NikeWomen, Nike store locations and at NikeStore.com, the official place to buy Nike product online. Choose a high-performance gift from our complete collection of Nike footwear, apparel, accessories and equipment. Register online to join our Members Only store for exclusive access to rare, limited-edition shoes. Not to mention FREE RETURNS on all orders.   The Nike Gift Card may also be used on NIKEiD.com, where you can create individually customized shoes, apparel, equipment and exclusive products.  Equip yourself with the Nike Gift Card.","Nike is not a sponsor or co-sponsor of this program." ,"This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/nike.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @sportsCategoryId, 50, "Nike", "The Nike Gift Card may be used at NIKETOWN, NikeFactoryStores, NikeWomen, Nike store locations and at NikeStore.com, the official place to buy Nike product online. Choose a high-performance gift from our complete collection of Nike footwear, apparel, accessories and equipment. Register online to join our Members Only store for exclusive access to rare, limited-edition shoes. Not to mention FREE RETURNS on all orders.   The Nike Gift Card may also be used on NIKEiD.com, where you can create individually customized shoes, apparel, equipment and exclusive products.  Equip yourself with the Nike Gift Card.","Nike is not a sponsor or co-sponsor of this program." ,"This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/nike.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @sportsCategoryId, 100, "Nike", "The Nike Gift Card may be used at NIKETOWN, NikeFactoryStores, NikeWomen, Nike store locations and at NikeStore.com, the official place to buy Nike product online. Choose a high-performance gift from our complete collection of Nike footwear, apparel, accessories and equipment. Register online to join our Members Only store for exclusive access to rare, limited-edition shoes. Not to mention FREE RETURNS on all orders.   The Nike Gift Card may also be used on NIKEiD.com, where you can create individually customized shoes, apparel, equipment and exclusive products.  Equip yourself with the Nike Gift Card.","Nike is not a sponsor or co-sponsor of this program." ,"This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/nike.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @sportsCategoryId, 10, "Foot Locker", "The perfect fit in a card!<br>The Foot Locker Gift Card lets you shop at more than 3,000 stores across the country and get the athletic brands you love. Hard-core athletes will find the latest developments in technologically enhanced footwear and apparel, and the fashion-conscious will be able to score with the most popular trends in athletic fashion.<br>Valid also at Lady Foot Locker, Champs, and Kid's Foot Locker locations. ","Foot Locker is not a sponsor or co-sponsor of this promotion.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/footLocker.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @sportsCategoryId, 25, "Foot Locker", "The perfect fit in a card!<br>The Foot Locker Gift Card lets you shop at more than 3,000 stores across the country and get the athletic brands you love. Hard-core athletes will find the latest developments in technologically enhanced footwear and apparel, and the fashion-conscious will be able to score with the most popular trends in athletic fashion.<br>Valid also at Lady Foot Locker, Champs, and Kid's Foot Locker locations. ","Foot Locker is not a sponsor or co-sponsor of this promotion.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/footLocker.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @sportsCategoryId, 50, "Foot Locker", "The perfect fit in a card!<br>The Foot Locker Gift Card lets you shop at more than 3,000 stores across the country and get the athletic brands you love. Hard-core athletes will find the latest developments in technologically enhanced footwear and apparel, and the fashion-conscious will be able to score with the most popular trends in athletic fashion.<br>Valid also at Lady Foot Locker, Champs, and Kid's Foot Locker locations. ","Foot Locker is not a sponsor or co-sponsor of this promotion.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/footLocker.png');
insert into product (store_id, product_category_id, price, name, choose_desc,disclamer_desc,confirm_desc, image_url) values (@storeId, @sportsCategoryId, 100, "Foot Locker", "The perfect fit in a card!<br>The Foot Locker Gift Card lets you shop at more than 3,000 stores across the country and get the athletic brands you love. Hard-core athletes will find the latest developments in technologically enhanced footwear and apparel, and the fashion-conscious will be able to score with the most popular trends in athletic fashion.<br>Valid also at Lady Foot Locker, Champs, and Kid's Foot Locker locations. ","Foot Locker is not a sponsor or co-sponsor of this promotion.","This Gift Card is in the mail within 48 hours of your parent's approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!", 'giftCards/footLocker.png');

-- Related to bug 16658 Matching popup.
ALTER TABLE `child_profile` MODIFY COLUMN `parent_matching` FLOAT UNSIGNED DEFAULT 0;
