/*SQL update script for release v1.39 */
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Email template for add new child");
 UPDATE sys_template 
 SET design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd"><html><head><title>ThreeJars</title><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"></head><body><table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">  <tr>    <td style="border-bottom:1px solid #7B2B83">  <table width="100%" border="0">  <tr>  <td><img src="cid:logo_parent.gif" width="294" height="84"></td> <td align="right" style="padding:55px 10px 0px 0px" > <font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"> <b>New Member </b></font></td> </tr>  </table></td>  </tr> <tr>    <td style="padding:20px;font-size:12px; font-family:verdana;">  Thanks for adding another child to your account. Our community of responsible<br/> kids grows stronger with each new member.<br/><br/> Questions? Please email us at <a href=''mailto:${supportEmail}''>${supportEmail}</a>. <br/><br/>Thanks for helping your kids learn healthy money habits!<br/><br/>  <a href=''${siteURL}''>${siteURL}</a><br>Raise money-wise, caring kids </td>  </tr>  <tr>   <td bgcolor="#7B2B83" style="padding:5px">  <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff"> For more information please contact our support team at </font>. <a href=''mailto:${supportEmail}''> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">  ${supportEmail}</font></a><br>    </td>  </tr></table></body>'
 WHERE sys_template_id = @systemTemplateId  ;
 
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Email template for add new child");
 UPDATE sys_template 
 SET subject = 'New Member' 
 WHERE sys_template_id = @systemTemplateId  ;
 
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Email template for cancel membership");
 UPDATE sys_template 
 SET design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd"><html><head><title>ThreeJars</title><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"></head><body><table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">  <tr> <td style="border-bottom:1px solid #7B2B83">      <table width="100%" border="0">        <tr>          <td><img src="cid:logo_parent.gif" width="294" height="84"></td>          <td align="right" style="padding:55px 10px 0px 0px" ><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"> <b>Membership Cancellation </b></font></td>        </tr>    </table></td>  </tr>  <tr>    <td style="padding:20px;font-size:12px; font-family:verdana;">  At your request, your family account with ThreeJars has been cancelled. We''re sorry to see you go.  <br/><br/>	Please take a minute to reply to this email to let us know why you have chosen to cancel. We''d also like to hear any suggestions you may have. We''re always open to good ideas!  <br/><br/> ThreeJars helps kids develop the financial skills and values they need to succeed <br/>in life.	If you decide to reinstate your service, please contact us at <br/> <a href=''mailto:${supportEmail}''>${supportEmail}</a>. We will be happy to assist you.<br/><br/> <a href=''${siteURL}''>${siteURL}</a><br>Raise money-wise, caring kids	 </td>  </tr>  <tr>    <td bgcolor="#7B2B83" style="padding:5px"> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">For more information please contact our support team at </font><a href=''mailto:${supportEmail}''><font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">${supportEmail}</font></a><br>    </td>  </tr></table></body>'
 WHERE sys_template_id = @systemTemplateId  ;
 
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Email template for cancel membership");
 UPDATE sys_template 
 SET subject = 'Membership Cancellation' 
 WHERE sys_template_id = @systemTemplateId  ;
 
 
 /*  project request*/
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Email template for project request");
 UPDATE sys_template 
 SET design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd"><html><head><title>ThreeJars</title><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"></head><body><table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">  <tr>    <td style="border-bottom:1px solid #7B2B83">      <table width="100%" border="0">        <tr>          <td><img src="cid:logo_parent.gif" width="294" height="84"></td>          <td align="right" style="padding:55px 10px 0px 0px" ><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"> <b>Project request(Action required)		  </b></font></td>        </tr>    </table></td>  </tr>  <tr>    <td style="padding:20px;font-size:12px; font-family:verdana;"> ${childName} has proposed a new project: ${projectName},  by ${date?string("MMMM d, yyyy")}, for $${amount}.<br/><br/> <a href=''${approvalLink}''>Click Here to Approve<img src="cid:check.png"></a><br/><br/>or<br/><a href=''${rejectionLink}''>Click Here to Reject<img src="cid:X.png"></a></b><br/><br/>  You may also respond by clicking <b>Reply</b> and typing "Approve" or "Reject". Then hit Send.<br/><br/> <a href=''${siteURL}''>${siteURL}</a> <br/>Raise money-wise, caring kids. Who knew it could be this easy? <br/>  </td>  </tr>  <tr>    <td bgcolor="#7B2B83" style="padding:5px"> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">For more information please contact our support team at </font><a href=''mailto:${supportEmail}''><font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">${supportEmail}</font></a><br>    </td>  </tr></table></body> '
 WHERE sys_template_id = @systemTemplateId  ;

 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Email template for project request");
 UPDATE sys_template 
 SET subject = 'Project request (Action required)' 
 WHERE sys_template_id = @systemTemplateId  ;
 
 /*  gift request*/
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Email template for gift request");
 UPDATE sys_template 
 SET design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd"><html><head><title>ThreeJars</title><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"></head><body><table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">  <tr>    <td style="border-bottom:1px solid #7B2B83">      <table width="100%" border="0">        <tr>          <td><img src="cid:logo_parent.gif" width="294" height="84"></td>          <td align="right" style="padding:55px 10px 0px 0px" ><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"><b>			Gift request (Action required)		  </b></font></td>        </tr>    </table></td>  </tr>  <tr>    <td style="padding:20px;font-size:12px; font-family:verdana;">	 ${childName} has requested a gift: $${amount} from ${giftFrom}.<br/><br/><a href=''${approvalLink}''>Click Here to Approve<img src="cid:check.png"></a><br/><br/>or<br/><a href=''${rejectionLink}''>Click Here to Reject<img src="cid:X.png"></a></b> <br/><br/> You may also respond by clicking <b>Reply</b> and typing "Approve" or "Reject". Then hit Send.<br/><br/><a href=''${siteURL}''>${siteURL}</a> <br/> Allowance made easy. Raise money-wise, caring kids.	 </td>  </tr>  <tr>    <td bgcolor="#7B2B83" style="padding:5px"> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">For more information please contact our support team at </font><a href=''mailto:${supportEmail}''><font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">${supportEmail}</font></a><br>    </td>  </tr></table></body>'
 WHERE sys_template_id = @systemTemplateId  ;
 
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Email template for gift request");
 UPDATE sys_template 
 SET subject = 'Gift request (Action required)' 
 WHERE sys_template_id = @systemTemplateId  ;
 
 /*  Chore request*/
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Email template for chore request");
 UPDATE sys_template 
 SET design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd"><html><head><title>ThreeJars</title><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"></head><body><table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">  <tr>    <td style="border-bottom:1px solid #7B2B83">      <table width="100%" border="0">        <tr>          <td><img src="cid:logo_parent.gif" width="294" height="84"></td>          <td align="right" style="padding:55px 10px 0px 0px" ><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"><b> Chore request (Action required)		  </b></font></td>        </tr>    </table></td>  </tr>  <tr>    <td style="padding:20px;font-size:12px; font-family:verdana;">	  ${childName} has requested an additional chore: ${choreName} performed <br/>  ${choreFrequency}.<br/><br/> <a href=''${approvalLink}''>Click Here to Approve<img src="cid:check.png""></a><br/><br/>or<br/><a href=''${rejectionLink}''>Click Here to Reject<img src="cid:X.png"></a></b><br/><br/>  You may also respond by clicking <b>Reply</b> and typing "Approve" or "Reject". Then hit Send.<br/><br/><a href=''${siteURL}''>${siteURL}</a><br/>Allowance made easy. Raise money-wise, caring kids. </td>  </tr>  <tr>    <td bgcolor="#7B2B83" style="padding:5px"> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">For more information please contact our support team at </font><a href=''mailto:${supportEmail}''><font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">${supportEmail}</font></a><br>    </td>  </tr></table></body>'
 WHERE sys_template_id = @systemTemplateId  ;
 
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Email template for chore request");
 UPDATE sys_template 
 SET subject = 'Chore request(Action required)' 
 WHERE sys_template_id = @systemTemplateId  ;
 
/*   Allowance Change request */
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Email template for change allowance request");
 UPDATE sys_template 
 SET design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd"><html><head><title>ThreeJars</title><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"></head><body><table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">  <tr>    <td style="border-bottom:1px solid #7B2B83">      <table width="100%" border="0">        <tr>          <td><img src="cid:logo_parent.gif" width="294" height="84"></td>          <td align="right" style="padding:55px 10px 0px 0px" ><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"><b> Allowance Change request (Action required)  </b></font></td>        </tr>    </table></td>  </tr>  <tr>    <td style="padding:20px;font-size:12px; font-family:verdana;"> ${childName} would like to receive $${amount} ${frequency}.  <br/><br/><a href=''${approvalLink}''>Click Here to Approve<img src="cid:check.png"></a><br/><br/>or<br/><a href=''${rejectionLink}''>Click Here to Reject<img src="cid:X.png"></a></b><br/><br/>  You may also respond by clicking <b>Reply</b> and typing "Approve" or "Reject". Then hit Send.<br/><br/><a href=''${siteURL}''>${siteURL}</a> <br/>	Raise money-wise, caring kids. Who knew it could be this easy? </td>  </tr>  <tr>    <td bgcolor="#7B2B83" style="padding:5px"> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">For more information please contact our support team at </font><a href=''mailto:${supportEmail}''><font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">${supportEmail}</font></a><br>    </td>  </tr></table></body>'
 WHERE sys_template_id = @systemTemplateId  ;
 
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Email template for change allowance request");
 UPDATE sys_template 
 SET subject = 'Allowance change request request(Action required)' 
 WHERE sys_template_id = @systemTemplateId  ;

 /*change allocations request*/
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Email template for change allocations request");
 UPDATE sys_template 
 SET design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd"><html><head><title>ThreeJars</title><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"></head><body><table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">  <tr>    <td style="border-bottom:1px solid #7B2B83">      <table width="100%" border="0">        <tr>          <td><img src="cid:logo_parent.gif" width="294" height="84"></td>          <td align="right" style="padding:55px 10px 0px 0px" ><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"><b> Allocation Request   (Action required)  </b></font></td>        </tr>    </table></td>  </tr>  <tr>    <td style="padding:20px;font-size:12px; font-family:verdana;">	 ${childName} would like to change ${pronoun} allocations to [${save}%Save, ${spend}%Spend, and ${share}%Share]. <br/><br/><a href=''${approvalLink}''>Click Here to Approve<img src="cid:check.png"></a><br/><br/>or<br/><a href=''${rejectionLink}''>Click Here to Reject<img src="cid:X.png"></a></b> <br/><br/> You may also respond by clicking <b>Reply</b> and typing "Approve" or "Reject". Then hit Send.<br/><br/><a href=''${siteURL}''>${siteURL}</a> <br/>Raise money-wise, caring kids. Who knew it could be this easy?  </td>  </tr>  <tr>    <td bgcolor="#7B2B83" style="padding:5px"> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">For more information please contact our support team at </font><a href=''mailto:${supportEmail}''><font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">${supportEmail}</font></a><br>    </td>  </tr></table></body>'
 WHERE sys_template_id = @systemTemplateId  ;
 
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Email template for change allocations request");
 UPDATE sys_template 
 SET subject = 'Allocation request(Action required)' 
 WHERE sys_template_id = @systemTemplateId  ;
 
 /*Spend Request*/
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Email template for spend request");
 UPDATE sys_template 
 SET design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd"><html><head><title>ThreeJars</title><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"></head><body><table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">  <tr>    <td style="border-bottom:1px solid #7B2B83">      <table width="100%" border="0">        <tr>          <td><img src="cid:logo_parent.gif" width="294" height="84"></td>          <td align="right" style="padding:55px 10px 0px 0px" ><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"><b>Spend request (Action required)  		  </b></font></td>        </tr>    </table></td>  </tr>  <tr>    <td style="padding:20px;font-size:12px; font-family:verdana;">	 ${childName} would like to buy a $${amount} ${cardName} gift card. <br/><br/>  <a href=''${approvalLink}''>Click Here to Approve<img src="cid:check.png"></a><br/><br/>or<br/><a href=''${rejectionLink}''>Click Here to Reject<img src="cid:X.png"></a></b><br/><br/>  You may also respond by clicking <b>Reply</b> and typing "Approve" or "Reject". Then hit Send.<br/><br/><a href=''${siteURL}''>${siteURL}</a><br/>Raise money-wise, caring kids. Who knew it could be this easy?	</td>  </tr>  <tr>    <td bgcolor="#7B2B83" style="padding:5px"> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">For more information please contact our support team at </font><a href=''mailto:${supportEmail}''><font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">${supportEmail}</font></a><br>    </td>  </tr></table></body>'
 WHERE sys_template_id = @systemTemplateId  ;
 
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Email template for spend request");
 UPDATE sys_template 
 SET subject = 'Spend request(Action required)' 
 WHERE sys_template_id = @systemTemplateId  ;

 /*Share Request*/
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Email template for share request");
 UPDATE sys_template 
 SET design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd"><html><head><title>ThreeJars</title><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"></head><body><table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">  <tr>    <td style="border-bottom:1px solid #7B2B83">      <table width="100%" border="0">        <tr>          <td><img src="cid:logo_parent.gif" width="294" height="84"></td>          <td align="right" style="padding:55px 10px 0px 0px" ><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"><b> Share request (Action required)    </b></font></td>        </tr>    </table></td>  </tr>  <tr>    <td style="padding:20px;font-size:12px; font-family:verdana;">	  ${childName} would like to donate $${amount} to ${causeName}, a project sponsored by	${charityName}. <br/><br/>  <a href=''${approvalLink}''>Click Here to Approve<img src="cid:check.png"></a><br/><br/>or<br/><a href=''${rejectionLink}''>Click Here to Reject<img src="cid:X.png"></a></b><br/><br/>  You may also respond by clicking <b>Reply</b> and typing "Approve" or "Reject".Then hit Send.<br/><br/><a href=''${siteURL}''>${siteURL}</a> <br/>	Raise money-wise, caring kids. Who knew it could be this easy? </td>  </tr>  <tr>    <td bgcolor="#7B2B83" style="padding:5px"> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">For more information please contact our support team at </font><a href=''mailto:${supportEmail}''><font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">${supportEmail}</font></a><br>    </td>  </tr></table></body>'
 WHERE sys_template_id = @systemTemplateId  ;
 
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Email template for share request");
 UPDATE sys_template 
 SET subject = 'Share request(Action required)' 
 WHERE sys_template_id = @systemTemplateId  ;
 
 /*  Investment request  */
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Email template for investment request");
 UPDATE sys_template 
 SET design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd"><html><head><title>ThreeJars</title><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"></head><body><table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">  <tr>    <td style="border-bottom:1px solid #7B2B83">      <table width="100%" border="0">        <tr>          <td><img src="cid:logo_parent.gif" width="294" height="84"></td>          <td align="right" style="padding:55px 10px 0px 0px" ><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"><b>	Investment request (Action required)    		  </b></font></td>        </tr>    </table></td>  </tr>  <tr>    <td style="padding:20px;font-size:12px; font-family:verdana;"> ${childName} would like to make $${profitAmount} by investing in a ${investment} for<br/> ${timePeriod}.<br/> <br/><a href=''${approvalLink}''>Click Here to Approve<img src="cid:check.png"></a><br/><br/>or<br/><a href=''${rejectionLink}''>Click Here to Reject<img src="cid:X.png"></a></b><br/><br/>  You may also respond by clicking <b>Reply</b> and typing "Approve" or "Reject". Then hit Send.<br/><br/><a href=''${siteURL}''>${siteURL}</a><br/>Raise money-wise, caring kids. Who knew it could be this easy?	 </td>  </tr>  <tr>    <td bgcolor="#7B2B83" style="padding:5px"> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">For more information please contact our support team at </font><a href=''mailto:${supportEmail}''><font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">${supportEmail}</font></a><br>    </td>  </tr></table></body>'
 WHERE sys_template_id = @systemTemplateId  ;
 
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Email template for investment request");
 UPDATE sys_template 
 SET subject = 'Investment request(Action required)' 
 WHERE sys_template_id = @systemTemplateId  ;
 
 
 
 /* transfer funds request  */
 
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Email template for transfer funds request");
 UPDATE sys_template 
 SET design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd"><html><head><title>ThreeJars</title><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"></head><body><table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">  <tr>    <td style="border-bottom:1px solid #7B2B83">      <table width="100%" border="0">        <tr>          <td><img src="cid:logo_parent.gif" width="294" height="84"></td>          <td align="right" style="padding:55px 10px 0px 0px" ><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"><b>Request to Move Money(Action required) </b></font></td>        </tr>    </table></td>  </tr>  <tr>    <td style="padding:20px;font-size:12px; font-family:verdana;"> ${childName} would like to transfer $${amount} from ${pronoun} ${fromAccount} Account to ${pronoun} ${toAccount} Account. <br/><br/><a href=''${approvalLink}''>Click Here to Approve<img src="cid:check.png"></a><br/><br/>or<br/><a href=''${rejectionLink}''>Click Here to Reject<img src="cid:X.png"></a></b><br/><br/>  You may also respond by clicking <b>Reply</b> and typing "Approve" or "Reject". Then hit Send.<br/><br/><a href=''${siteURL}''>${siteURL}</a> <br/>	Raise money-wise, caring kids. Who knew it could be this easy? </td>  </tr>  <tr>    <td bgcolor="#7B2B83" style="padding:5px"> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">For more information please contact our support team at </font><a href=''mailto:${supportEmail}''><font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">${supportEmail}</font></a><br>    </td>  </tr></table></body>'
 WHERE sys_template_id = @systemTemplateId  ;
 
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Email template for transfer funds request");
 UPDATE sys_template 
 SET subject = 'Request to Move Money(Action required)' 
 WHERE sys_template_id = @systemTemplateId  ;
 
/*   Request for Cash withdrawal*/ 
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Email template for cash request");
 UPDATE sys_template 
 SET design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd"><html><head><title>ThreeJars</title><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"></head><body><table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">  <tr>    <td style="border-bottom:1px solid #7B2B83">      <table width="100%" border="0">        <tr>          <td><img src="cid:logo_parent.gif" width="294" height="84"></td>          <td align="right" style="padding:55px 10px 0px 0px" ><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"><b> Cash Withdrawal Request(Action required)     		  </b></font></td>        </tr>    </table></td>  </tr>  <tr>    <td style="padding:20px;font-size:12px; font-family:verdana;">	  ${childName} would like to withdraw $${amount} from ${pronoun} Spend Account. <br/><br/><a href=''${approvalLink}''>Click Here to Approve<img src="cid:check.png"></a><br/><br/>or<br/><a href=''${rejectionLink}''>Click Here to Reject<img src="cid:X.png"></a></b><br/><br/>  You may also respond by clicking <b>Reply</b> and typing "Approve" or "Reject". Then hit Send.<br/><br/><a href=''${siteURL}''>${siteURL}</a> <br/>Raise money-wise, caring kids. Who knew it could be this easy? </td>  </tr>  <tr>    <td bgcolor="#7B2B83" style="padding:5px"> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">For more information please contact our support team at </font><a href=''mailto:${supportEmail}''><font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">${supportEmail}</font></a><br>    </td>  </tr></table></body>'
 WHERE sys_template_id = @systemTemplateId  ;
 
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Email template for cash request");
 UPDATE sys_template 
 SET subject = 'Cash withdrawal request(Action required)' 
 WHERE sys_template_id = @systemTemplateId  ;
 
 /* problem in sql  approved/reject by an email*/
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Email template of child's confirmation request sent to parent");
 UPDATE sys_template 
 SET design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd"><html><head><title>ThreeJars</title><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"></head><body><table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">  <tr>    <td style="border-bottom:1px solid #7B2B83">    <table width="100%" border="0">        <tr>          <td> <img src="cid:logo_parent.gif" width="294" height="84"></td>       <td align="right" style="padding:55px 10px 0px 0px" nowrap="nowrap"> <font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"> <b>  Confirmation: Child Request ${approveRejectStatus}.</b></font></td>        </tr>    </table></td>  </tr>   <tr>    <td style="padding:20px;font-size:12px; font-family:verdana;"> <p>${message} <br/><br/>  A message has been sent to ${childName}s''s homepage. <br/><br/></p> <a href=''${siteURL}''>${siteURL}</a><br>Raise money-wise, caring kids. Who knew it could be this easy? </td>  </tr>  <tr>    <td bgcolor="#7B2B83" style="padding:5px"> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">For more information please contact our support team at </font><a href=''mailto:${supportEmail}''><font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">${supportEmail}</font></a><br>    </td>  </tr></table></body>'
 WHERE sys_template_id = @systemTemplateId  ;
 
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Email template of child's confirmation request sent to parent");
 UPDATE sys_template 
 SET subject = 'Confirmation: Child Request %s' 
 WHERE sys_template_id = @systemTemplateId  ;
 
 /* share confriamtion for USA*/
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Charging email for share confirmation");
 UPDATE sys_template 
 SET design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd"><html><head><title>ThreeJars</title><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"></head><body><table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">  <tr>    <td style="border-bottom:1px solid #7B2B83">      <table width="100%" border="0">	    <tr><td colspan="2" align="right" style="padding:5px 10px 0px 0px" ><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"><b>			Charitable Donation </b></font></td>		</tr>        <tr>          <td><img src="cid:logo_parent.gif" width="294" height="84"></td>		  <td><img src="cid:${ngoURL}"></td>        </tr>    </table></td>  </tr>  <tr>    <td style="padding:20px;font-size:12px; font-family:verdana;">		${currentDate?string("MMMM d, yyyy")}<br/><br/>		Dear ${parentName},<br/><br/>	On behalf of ${organization}  we''d like to thank you. Your donation of $${donationAmount} has been processed and will be directed to  	${organization} in support of ${donationCause}. <br/><br/> Here are the details:<br/><br/>Date of transaction: ${transactionDate?string("MMMM d, yyyy")}<br/> Transaction#: ${transactionId}<br/> Payment method: ${paymentMethod}<br/><br/> This letter confirms that no goods or services were provided to you in exchange,<br/> in whole or in part, for	this charitable contribution. This contribution is fully<br/> deductible to the extent allowed by law. <br/><br/>For more information about ${organization}, ${organizationURL}. <br/><br/>We appreciate your commitment to making a difference!<br/><br/>	<a href=''${siteURL}''>${siteURL}</a><br>	Raise money-wise, caring kids.  </td>  </tr>  <tr>    <td bgcolor="#7B2B83" style="padding:5px"> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">For more information please contact our support team at </font><a href=''mailto:${supportEmail}''><font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">${supportEmail}</font></a><br>    </td>  </tr></table></body> '
 WHERE sys_template_id = @systemTemplateId  ;
 
 /* share confriamtion for Canada*/
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Charging email for share confirmation for parents from Canada");
 UPDATE sys_template 
 SET design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd"><html><head><title>ThreeJars</title><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"></head><body><table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">  <tr>    <td style="border-bottom:1px solid #7B2B83">      <table width="100%" border="0">	    <tr><td colspan="2" align="right" style="padding:5px 10px 0px 0px" ><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"><b>			Charitable Donation </b></font></td>		</tr>        <tr>          <td><img src="cid:logo_parent.gif" width="294" height="84"></td>		  <td><img src="cid:${ngoURL}"></td>        </tr>    </table></td>  </tr>  <tr>    <td style="padding:20px;font-size:12px; font-family:verdana;">		${currentDate?string("MMMM d, yyyy")}<br/><br/>	 Dear ${parentName},<br/><br/> On behalf of ${organization} we''d like to thank you. Your donation of $${donationAmount} has been processed and will be directed to ${organization} in support of ${donationCause}. <br/><br/> Here are the details:<br/><br/> Date of transaction: ${transactionDate?string("MMMM d, yyyy")}<br/> Transaction#: ${transactionId}<br/> Payment method: ${paymentMethod}<br/><br/> This letter confirms that no goods or services were provided to you in exchange,<br/> in whole or in part, for this charitable contribution. Your contribution may be tax<br/> deductible;please contact a professional tax advisor for tax-related questions. <br/><br/>For more information about ${organization}, ${organizationURL}. <br/><br/>	We appreciate your commitment to making a difference!<br/><br/>	 <a href=''${siteURL}''>${siteURL}</a><br>	Raise money-wise, caring kids.  </td>  </tr>  <tr>    <td bgcolor="#7B2B83" style="padding:5px"> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">For more information please contact our support team at </font><a href=''mailto:''${supportEmail}><font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">${supportEmail}</font></a><br>    </td>  </tr></table></body>'
 WHERE sys_template_id = @systemTemplateId  ;
 
 /* for Gift Card Order confirmation – USA and Canada */
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Charging email for gift card confirmation");
 UPDATE sys_template 
 SET design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd"><html><head><title>ThreeJars</title><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"></head><body><table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">  <tr>    <td style="border-bottom:1px solid #7B2B83">      <table width="100%" border="0">        <tr>          <td><img src="cid:logo_parent.gif" width="294" height="84"></td>          <td align="right" style="padding:55px 10px 0px 0px" ><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"><b>			Gift Card Order     		  </b></font></td>        </tr>    </table></td>  </tr>  <tr>    <td style="padding:20px;font-size:12px; font-family:verdana;">		${purchaseDate?string("MMMM d, yyyy")}<br/><br/> Dear ${parentName},<br/><br/>We''re writing to confirm your recent gift card purchase. Your payment has been<br/> processed. You can expect delivery by first-class mail within 7 to 10 business<br/> days.<br/><br/>Here are the details:<br/><br/>		Purchase date: ${purchaseDate?string("MMMM d, yyyy")}<br/><br/>		Confirmation#: ${orderNumber}<br/><br/>		Item: ${giftName} gift card<br/>		Value: $${giftPrice}<br/>		Shipping, Handling & Merchant Charge: ${shippingCost}<br/>		Total: $${total}<br/>		Payment method: ${ccType}, ${ccDisplayNumber}<br/><br/>		Shipping Address:<br/>		${buyerName}<br/>		${streetName}<br/>		${cityName}<br/><br/> For questions about your child''s gift card purchase, or to learn more about our<br/>retail partners, go to	<a href=''${siteURL}/faq''>${siteURL}/faq</a>. Still have questions? Email us at<br/>		<a href=''${siteURL}/support''>${siteURL}/support</a>. <br/><br/>	 ThreeJars: Where kids spend their money, not yours, and learn to value a dollar. <br/><br/> <a href=''${siteURL}''>${siteURL}</a><br>	Raise money-wise, caring kids. </td>  </tr>  <tr>    <td bgcolor="#7B2B83" style="padding:5px"> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">For more information please contact our support team at </font><a href=''mailto:${supportEmail}''><font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">${supportEmail}</font></a><br>    </td>  </tr></table></body>'
 WHERE sys_template_id = @systemTemplateId  ;
 
 /*   Email for confirming shipping  */
 
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Email for confirming shipping");
 UPDATE sys_template 
 SET design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd"><html><head><title>ThreeJars</title><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"></head><body><table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">  <tr>    <td style="border-bottom:1px solid #7B2B83">      <table width="100%" border="0">        <tr>          <td><img src="cid:logo_parent.gif" width="294" height="84"></td>          <td align="right" style="padding:55px 10px 0px 0px" ><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"><b>			Gift Card Shipped    		  </b></font></td>        </tr>    </table></td>  </tr>  <tr>    <td style="padding:20px;font-size:12px; font-family:verdana;">		${currentDate?string("MMMM d, yyyy")}<br/><br/> Dear ${parentName},<br/><br/>  We''re pleased to let you know that your gift card order has been shipped. You <br/>can expect delivery by first-class mail within 7 to 10 business days. <br/><br/>		Here are the details of your order, including your Order Number. We recommend<br/> that you retain this email for future reference.<br/><br/> Purchase date: ${purchaseDate?string("MMMM d, yyyy")}<br/>		Order#: ${orderNumber}<br/><br/>		Item: ${itemName} gift card<br/>Value: $${itemPrice}<br/>	Shipping, Handling & Merchant Charge: ${shippingCharges}<br/>		Total: $${total}<br/>		Payment method: ${ccType}, ${ccDisplayNumber}<br/><br/>		Shipping Address:<br/>		${parentName} ${lastName}<br/>		${shippingAddress}<br/>		${shippingAddress1}, ${shippingAddress2} ${zip} <br/><br/>ThreeJars: Where kids spend their money, not yours, and learn to value a dollar. <br/><br/>		<a href=''${siteURL}''>${siteURL}</a><br> Raise money-wise, caring kids. </td>  </tr>  <tr>    <td bgcolor="#7B2B83" style="padding:5px"> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">For more information please contact our support team at </font><a href=''mailto:${supportEmail}''><font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">${supportEmail}</font></a><br>    </td>  </tr></table></body>'
 WHERE sys_template_id = @systemTemplateId  ;
 
 /*  [MEMBERSHIP CARD ORDER]  */
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Charging email for membership card purchase");
 UPDATE sys_template 
 SET design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd"><html><head><title>ThreeJars</title><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"></head><body><table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">  <tr>    <td style="border-bottom:1px solid #7B2B83">      <table width="100%" border="0">        <tr>          <td><img src="cid:logo_parent.gif" width="294" height="84"></td>          <td align="right" style="padding:55px 10px 0px 0px" ><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"><b>			Membership Card Order    		  </b></font></td>        </tr>    </table></td>  </tr>  <tr>    <td style="padding:20px;font-size:12px; font-family:verdana;"> Dear ${parentName},<br/><br/> Thank you for your recent purchase of ${singular} ThreeJars Family Membership ${plural}. Your payment has been processed. You can expect delivery by first-class<br/>mail within 7 to 10 business days.<br/><br/>Here are the details:<br/><br/>  Purchase date: ${purchaseDate?string("MMMM d, yyyy")}<br/>  Order#: ${orderNumber}<br/><br/>  Quantity: ${quantity} Membership Card${plural}<br/> Unit Price: $29.95 per Family Membership<br/> Subtotal: $${subTotal}<br/> Shipping & Handling: ${shippingHandling}<br/> Total: $${total}<br/> Payment method: ${ccType}, ${ccDisplayNumber}<br/><br/> Shipping Address:<br/>		${buyerName} <br/>		${streetName}<br/>		${cityName}<br/><br/>	 Thank you for introducing ThreeJars to your family, friends, and colleagues. We appreciate your support.<br/><br/>	 <a href=''${siteURL}''>${siteURL}</a><br>	Raising money-wise, caring kids. Who knew it could be this easy?  </td>  </tr>  <tr>    <td bgcolor="#7B2B83" style="padding:5px"> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">For more information please contact our support team at </font><a href=''mailto:${supportEmail}''><font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">${supportEmail}</font></a><br>    </td>  </tr></table></body>'
 WHERE sys_template_id = @systemTemplateId  ;
 
 /* Goal setting email*/
 
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Goal setting email");
 UPDATE sys_template 
 SET design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd"><html><head><title>ThreeJars</title><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"></head><body><table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">  <tr>    <td style="border-bottom:1px solid #7B2B83">      <table width="100%" border="0">        <tr>          <td><img src="cid:logo_parent.gif" width="294" height="84"></td>          <td align="right" style="padding:55px 10px 0px 0px" ><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"><b>			Goal Setting    		  </b></font></td>        </tr>    </table></td>  </tr>  <tr>    <td style="padding:20px;font-size:12px; font-family:verdana;">		Dear ${parentName},<br/><br/> We thought you''d like to know that ${kidName} is using ThreeJars''s Goal Setting<br/>  feature to save for something special.<br/><br/> ${kidName}''s goal: ${goalSettingItem}<br/>		${kidName}''s estimate of its cost: ${goalSettingAmount}<br/> Days until ${possesivePronoun} goal is reached: ${days} days<br/><br/> For ways to help ${kidName} reach  ${possesivePronoun} goal faster, log in to your account at ThreeJars. <br/><br/> <a href=''${siteURL}''>${siteURL}</a><br>	Raise money-wise, caring kids. Who knew it could be this easy? </td>  </tr>  <tr>    <td bgcolor="#7B2B83" style="padding:5px"> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">For more information please contact our support team at </font><a href=''mailto:${supportEmail}''><font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">${supportEmail}</font></a><br>    </td>  </tr></table></body> '
 WHERE sys_template_id = @systemTemplateId  ; 
 
 /* Change of Email */
 
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Email template for when email address changed");
 UPDATE sys_template 
 SET design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd"><html><head><title>ThreeJars</title><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"></head><body><table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">  <tr>    <td style="border-bottom:1px solid #7B2B83">      <table width="100%" border="0">        <tr>          <td><img src="cid:logo_parent.gif" width="294" height="84"></td>          <td align="right" style="padding:55px 10px 0px 0px" ><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"><b>			Change of Email    		  </b></font></td>        </tr>    </table></td>  </tr>  <tr>    <td style="padding:20px;font-size:12px; font-family:verdana;">	 This is to confirm your request to discontinue the use of this email address with<br/>regard to ThreeJars, including its use as your login ID. If you did not make this<br/>request, please contact us as soon as possible at <a href=''mailto:${supportEmail}''>${supportEmail}</a>.<br/><br/> <a href=''${siteURL}''>${siteURL}</a><br> Raise money-wise, caring kids </td>  </tr>  <tr>    <td bgcolor="#7B2B83" style="padding:5px"> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">For more information please contact our support team at </font><a href=''mailto:${supportEmail}''><font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">${supportEmail}</font></a><br>    </td>  </tr></table></body> '
 WHERE sys_template_id = @systemTemplateId  ;

/*  Free Membership Trial  (WELCOME_CODE_FAMILY_PLAN Need to confirm wiht Jason 
whetere we need to update this template or create a new template.)*/
 
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Email template for new paying user for family plan");
 UPDATE sys_template 
 SET design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd"> <html> <head> <title>ThreeJars</title> <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"> </head> <body>  <table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">   <tr>     <td style="border-bottom:1px solid #7B2B83">       <table width="100%" border="0">         <tr>           <td><img src="cid:logo_parent.gif" width="294" height="84"></td>   <td align="right" style="padding:55px 10px 0px 0px" ><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"><b> Free Membership Trial  	  </b></font></td>        </tr>     </table></td>   </tr>   <tr>    <td style="padding:20px;font-size:12px; font-family:verdana;"> 	Welcome! Your free 7-day membership trial begins today.<br/><br/>  	You''re about to transform how your child thinks about money! <br/><br/>     Who knew it could be this easy?	<br/><br/> 	When your free trial is over, the annual family membership fee of $29.95  will be<br/>charged to your credit card: 	Payment method: ${paymentMethod}.	<br/><br/>You may cancel your membership before the end of the trial period at<br/><a href=''${siteURL}''>${supportEmail}</a>. <br/><br/>  	Thanks for helping your kids learn healthy money habits!<br/><br/> 	<a href=''${siteURL}''>${siteURL}</a><br>  Raise money-wise, caring kids 	</td>   </tr>   <tr>     <td bgcolor="#7B2B83" style="padding:5px"> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">For more information please contact our support team at </font><a href=''${siteURL}''><font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">${supportEmail}</font></a><br>     </td>  </tr> </table></body> '
 WHERE sys_template_id = @systemTemplateId  ;
 
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Email template for new paying user for family plan");
 UPDATE sys_template 
 SET subject = 'Free Membership Trial' 
 WHERE sys_template_id = @systemTemplateId  ;
 
 
 /*  Membership Renewal  */
 
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Email sent when five days left to expire");
 UPDATE sys_template 
 SET design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd"><html><head><title>FiftyP</title><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"></head><body><table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">  <tr>    <td style="border-bottom:1px solid #7B2B83">      <table width="100%" border="0">        <tr>          <td><img src="cid:logo_parent.gif" width="294" height="84"></td>          <td align="right" style="padding:55px 10px 0px 0px" ><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"> <b>Membership Renewal </b></font></td>        </tr>    </table></td>  </tr>  <tr>    <td style="padding:20px;font-size:12px; font-family:verdana;"> Your family''s membership has expired.  it''s not too late to renew!<br/><br/> It''s important your ${numOfKids} learns to save more, spend less, and help others. <br/><br/>Take a minute now to renew your membership and help your ${numOfKids} learn<br/> healthy money habits.<br/><br/> Please contact us our Billing Team at <a href=''mailto:${supportEmail}''><font  style="font-size:11px; line-height:16px" face="verdana" >${supportEmail}</font></a> to insure uninterrupted service. <br/> We will be happy to assist you! <br/><br/>  <a href=''${siteURL}''>${siteURL}</a> <br/><br>	 </td>  </tr>  <tr>    <td bgcolor="#7B2B83" style="padding:5px"> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">For more information please contact our support team at </font><a href=''mailto:support@fiftyp.com''><font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">support@fiftyp.com</font></a><br>    </td>  </tr></table></body>'
 WHERE sys_template_id = @systemTemplateId  ; 
 
  /*  ALLOWANCE_NOTIFICATION  */
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Email template for Allowance notification");
 UPDATE sys_template 
 SET design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd"><html><head><title>ThreeJars</title><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"></head><body><table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">  <tr>    <td style="border-bottom:1px solid #7B2B83">      <table width="100%" border="0">        <tr>          <td><img src="cid:logo_parent.gif" width="294" height="84"></td>          <td align="right" style="padding:55px 10px 0px 0px" ><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"><b>			${childNames} allowance tomorrow		  </b></font></td>        </tr>    </table></td>  </tr>  <tr>    <td style="padding:20px;font-size:12px; font-family:verdana;">	Allowance will be posted on ThreeJars tomorrow along with other scheduled <br/>earnings. <b>Your credit card is not charged</b>.<br/><br/> To alter payment, please log in to <a href=''${siteURL}''>${siteURL}</a>. <br/><br/> <a href=''${siteURL}''>${siteURL}</a><br/> Raise money-wise, caring kids. Who knew it could be this easy?	 </td>  </tr>  <tr>    <td bgcolor="#7B2B83" style="padding:5px"> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">For more information please contact our support team at </font><a href=''mailto:${supportEmail}''><font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">${supportEmail}</font></a><br>    </td>  </tr></table></body>'
 WHERE sys_template_id = @systemTemplateId  ; 
 
 
 /*  Alter ngo table */
 ALTER TABLE ngo_profile ADD ngo_url TEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL ;
 
 /* update the ngo_field*/
 UPDATE ngo_profile SET ngo_url = 'http://carbonfund.org/' 
 WHERE ngo_profile_id =1;
 
 UPDATE ngo_profile SET ngo_url = 'www.wdcs.org'
 WHERE ngo_profile_id =2  ;
 
 UPDATE ngo_profile SET ngo_url = 'http://www.playsoccer-nonprofit.org/' 
 WHERE ngo_profile_id =3;
 
 UPDATE ngo_profile SET ngo_url = 'http://www.nywolf.org/' 
 WHERE ngo_profile_id =4  ;
 
 UPDATE ngo_profile SET ngo_url = 'www.savethechildren.org' 
 WHERE  ngo_profile_id =5  ;
 
 UPDATE ngo_profile SET ngo_url = 'http://www.nature.org/'
 WHERE ngo_profile_id =6 ;
 
 UPDATE ngo_profile SET ngo_url = 'http://www.mhopus.org/' 
 WHERE ngo_profile_id =7  ;
 
 UPDATE ngo_profile SET ngo_url = 'http://www.pawsweb.org/' 
 WHERE ngo_profile_id =8 ;
 
/*1276 */
 select @systemTemplateId:=(select sys_template_id from sys_template where description = "Email template for new paying user for family plan");
 UPDATE sys_template 
 SET design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd"> <html> <head> <title>ThreeJars</title> <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"> </head> <body>  <table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">   <tr>     <td style="border-bottom:1px solid #7B2B83">       <table width="100%" border="0">         <tr>           <td><img src="cid:logo_parent.gif" width="294" height="84"></td>   <td align="right" style="padding:55px 10px 0px 0px" ><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"><b> Free Membership Trial  	  </b></font></td>        </tr>     </table></td>   </tr>   <tr>    <td style="padding:20px;font-size:12px; font-family:verdana;"> 	Welcome! Your free ${numberOfTrialDays}-day membership trial begins today.<br/><br/>  	You''re about to transform how your child thinks about money! <br/><br/>     Who knew it could be this easy?	<br/><br/> 	When your free trial is over, the annual family membership fee of $29.95  will be<br/>charged to your credit card: 	Payment method: ${paymentMethod}.	<br/><br/>You may cancel your membership before the end of the trial period at<br/><a href=''${siteURL}''>${supportEmail}</a>. <br/><br/>  	Thanks for helping your kids learn healthy money habits!<br/><br/> 	<a href=''${siteURL}''>${siteURL}</a><br>  Raise money-wise, caring kids 	</td>   </tr>   <tr>     <td bgcolor="#7B2B83" style="padding:5px"> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">For more information please contact our support team at </font><a href=''${siteURL}''><font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">${supportEmail}</font></a><br>     </td>  </tr> </table></body>'
 WHERE sys_template_id = @systemTemplateId  ;
 
/* #1294 Change family memership price from $29.95 to $30 */
update sys_template set design=replace(design,'29.95','30');
update subscription_type set price = 30 where subscription_type_id = 'FAMILY_PLAN';