/* New Themes */
insert into fp_theme (theme_id, name, description, theme_small_picture_url, theme_preview_picture_url) values ('kidshome4boy10', 'Kids Home For Boy 10', '', 'themes/thumbnails/kidshome4boy10.png', 'themes/thumbnails/kidshome4boy10.png');
insert into fp_theme (theme_id, name, description, theme_small_picture_url, theme_preview_picture_url) values ('kidshome4boy11', 'Kids Home For Boy 11', '', 'themes/thumbnails/kidshome4boy11.png', 'themes/thumbnails/kidshome4boy11.png');

/* New Avatars */
insert into profile_photo (profile_photo_id, name, url, description) values (93, 'avtr_balloons2', 'themes/avatars/avtr_balloons2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (94, 'avtr_baseballplayer2', 'themes/avatars/avtr_baseballplayer2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (95, 'avtr_baseballplayer3', 'themes/avatars/avtr_baseballplayer3.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (96, 'avtr_baseballplayer', 'themes/avatars/avtr_baseballplayer.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (97, 'avtr_basketballhoop2', 'themes/avatars/avtr_basketballhoop2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (98, 'avtr_basketballhoop', 'themes/avatars/avtr_basketballhoop.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (99, 'avtr_bulldog', 'themes/avatars/avtr_bulldog.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (100, 'avtr_car', 'themes/avatars/avtr_car.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (102, 'avtr_carblue2', 'themes/avatars/avtr_carblue2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (103, 'avtr_carblue', 'themes/avatars/avtr_carblue.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (104, 'avtr_carcorvette', 'themes/avatars/avtr_carcorvette.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (105, 'avtr_cargrey2', 'themes/avatars/avtr_cargrey2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (106, 'avtr_cargrey', 'themes/avatars/avtr_cargrey.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (107, 'avtr_carred2', 'themes/avatars/avtr_carred2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (108, 'avtr_carred', 'themes/avatars/avtr_carred.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (109, 'avtr_chess2', 'themes/avatars/avtr_chess2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (110, 'avtr_chess', 'themes/avatars/avtr_chess.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (111, 'avtr_dogwig', 'themes/avatars/avtr_dogwig.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (112, 'avtr_equestrian', 'themes/avatars/avtr_equestrian.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (113, 'avtr_fish3', 'themes/avatars/avtr_fish3.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (114, 'avtr_footballhelmet', 'themes/avatars/avtr_footballhelmet.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (115, 'avtr_footballplay', 'themes/avatars/avtr_footballplay.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (116, 'avtr_footballplayer2', 'themes/avatars/avtr_footballplayer2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (117, 'avtr_footballplayer3', 'themes/avatars/avtr_footballplayer3.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (118, 'avtr_footballplayer4', 'themes/avatars/avtr_footballplayer4.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (119, 'avtr_footballplayer5', 'themes/avatars/avtr_footballplayer5.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (120, 'avtr_footballplayer6', 'themes/avatars/avtr_footballplayer6.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (121, 'avtr_footballplayer7', 'themes/avatars/avtr_footballplayer7.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (122, 'avtr_footballplayer', 'themes/avatars/avtr_footballplayer.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (123, 'avtr_gamer2', 'themes/avatars/avtr_gamer2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (124, 'avtr_gamer3', 'themes/avatars/avtr_gamer3.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (125, 'avtr_gamer4', 'themes/avatars/avtr_gamer4.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (126, 'avtr_gamer', 'themes/avatars/avtr_gamer.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (127, 'avtr_golf2', 'themes/avatars/avtr_golf2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (128, 'avtr_golf', 'themes/avatars/avtr_golf.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (129, 'avtr_greenwoods2', 'themes/avatars/avtr_greenwoods2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (130, 'avtr_greenwoods', 'themes/avatars/avtr_greenwoods.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (131, 'avtr_guitar2', 'themes/avatars/avtr_guitar2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (132, 'avtr_guitar3', 'themes/avatars/avtr_guitar3.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (133, 'avtr_guitar4', 'themes/avatars/avtr_guitar4.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (134, 'avtr_guitar5', 'themes/avatars/avtr_guitar5.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (135, 'avtr_guitar6', 'themes/avatars/avtr_guitar6.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (136, 'avtr_guitar', 'themes/avatars/avtr_guitar.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (137, 'avtr_hockey2', 'themes/avatars/avtr_hockey2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (138, 'avtr_hockey3', 'themes/avatars/avtr_hockey3.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (139, 'avtr_hockey', 'themes/avatars/avtr_hockey.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (140, 'avtr_horse2', 'themes/avatars/avtr_horse2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (141, 'avtr_horse3', 'themes/avatars/avtr_horse3.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (142, 'avtr_piano', 'themes/avatars/avtr_piano.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (143, 'avtr_skater4', 'themes/avatars/avtr_poolballs.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (144, 'avtr_skater4', 'themes/avatars/avtr_skater4.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (145, 'avtr_skater5', 'themes/avatars/avtr_skater5.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (146, 'avtr_skater6', 'themes/avatars/avtr_skater6.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (147, 'avtr_skater7', 'themes/avatars/avtr_skater7.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (148, 'avtr_ski', 'themes/avatars/avtr_ski.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (149, 'avtr_skigoggles', 'themes/avatars/avtr_skigoggles.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (150, 'avtr_snowmountain', 'themes/avatars/avtr_snowmountain.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (151, 'avtr_soccerballblack', 'themes/avatars/avtr_soccerballblack.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (152, 'avtr_soccerballblue2', 'themes/avatars/avtr_soccerballblue2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (153, 'avtr_soccerballblue', 'themes/avatars/avtr_soccerballblue.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (154, 'avtr_soccerballgreen', 'themes/avatars/avtr_soccerballgreen.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (155, 'avtr_soccerballpurple', 'themes/avatars/avtr_soccerballpurple.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (156, 'avtr_soccerballred2', 'themes/avatars/avtr_soccerballred2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (157, 'avtr_soccerballred', 'themes/avatars/avtr_soccerballred.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (158, 'avtr_soccerballwhite', 'themes/avatars/avtr_soccerballwhite.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (159, 'avtr_soccerballyellow', 'themes/avatars/avtr_soccerballyellow.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (160, 'avtr_surfgirl', 'themes/avatars/avtr_surfgirl.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (161, 'avtr_surfguy', 'themes/avatars/avtr_surfguy.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (162, 'avtr_surfwave2', 'themes/avatars/avtr_surfwave2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (163, 'avtr_surfwave3', 'themes/avatars/avtr_surfwave3.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (164, 'avtr_surfwave4', 'themes/avatars/avtr_surfwave4.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (165, 'avtr_surfwave', 'themes/avatars/avtr_surfwave.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (166, 'avtr_swim2', 'themes/avatars/avtr_swim2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (167, 'avtr_swim', 'themes/avatars/avtr_swim.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (168, 'avtr_tennisball', 'themes/avatars/avtr_tennisball.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (169, 'avtr_track', 'themes/avatars/avtr_track.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (170, 'avtr_truck2', 'themes/avatars/avtr_truck2.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (171, 'avtr_truck3', 'themes/avatars/avtr_truck3.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (172, 'avtr_truck', 'themes/avatars/avtr_truck.png', '');
insert into profile_photo (profile_photo_id, name, url, description) values (173, 'avtr_weimeraner', 'themes/avatars/avtr_weimeraner.png', '');

/* Ticket #71 Allowance Notification */
update `sys_template` set `design` = '<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\"http://www.w3.org/TR/html4/loose.dtd\">\r\n<html>\r\n<head>\r\n<title>FiftyP</title>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n</head>\r\n<body>\r\n<table width=\"600\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #7B2B83\">\r\n  <tr>\r\n    <td style=\"border-bottom:1px solid #7B2B83\">\r\n      <table width=\"100%\" border=\"0\">\r\n        <tr>\r\n          <td><img src=\"cid:logo_parent.gif\" width=\"294\" height=\"84\"></td>\r\n          <td align=\"right\" style=\"padding:55px 10px 0px 0px\" ><font color=\"#F68B1F\" size=\"2\" style=\"font-size:14px;\" face=\"verdana\"><b>\r\n\t\t\tReminder: Tomorrow is Allowance Day for  ${childNames}!\r\n\t\t  </b></font></td>\r\n        </tr>\r\n    </table></td>\r\n  </tr>\r\n  <tr>\r\n    <td style=\"padding:20px;font-size:12px; font-family:verdana;\">\r\n\t<p>Dear ${parentName},</p>\r\n\t<p>\r\n\t  This is to let you know that allowance will be posted on FiftyP tomorrow for ${childNames}, along with other earnings or gifts that may be scheduled. Your credit card will not be charged. For more details, or to make changes to this posting, log in to <a href=''http://www.fiftyp.com''>www.fiftyp.com</a> and select their name.  \r\n\t<br/><br/><p>\tThank you for being part of our community. We hope your family is enjoying FiftyPs unique approach to teaching kids financial and social responsibility ... and that you will tell your friends. The bigger our FiftyP community, the greater the interest in what it means to be a money-wise, caring kid.</p>\r\n\t<p> Please let us know if you have any questions or suggestions for us. We are always looking to improve and enhance FiftyP. You can drop us an email at <a href=''http://www.fiftyp.com''>support@fiftyp.com</a> or log in to FiftyP and select Feedback from the Helpful Links menu. </p>\r\n\t  <p>\r\n\t\t\tWith best wishes,<br>\r\n\t\t\tTeam FiftyP<br>\r\n\t\t\t<a href=''http://www.fiftyp.com''>www.fiftyp.com</a><br>\r\n\t  </p>\r\n\t</td>\r\n  </tr>\r\n  <tr>\r\n    <td bgcolor=\"#7B2B83\" style=\"padding:5px\"> <font  style=\"font-size:11px; line-height:16px\" face=\"verdana\" color=\"#ffffff\">For more information please contact our support team at <a href=''http://www.fiftyp.com''>support@fiftyp.com</a><br>\r\n    </font> </td>\r\n  </tr>\r\n</table>\r\n\r\n</body>' where `sys_template_id` = 'ALLOWANCE_NOTIFICATION';

/* Ticket #71 Allowance Notification (grammar fix) */
update sys_template set design = '<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\"http://www.w3.org/TR/html4/loose.dtd\">\r\n<html>\r\n<head>\r\n<title>FiftyP</title>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n</head>\r\n<body>\r\n<table width=\"600\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #7B2B83\">\r\n  <tr>\r\n    <td style=\"border-bottom:1px solid #7B2B83\">\r\n      <table width=\"100%\" border=\"0\">\r\n        <tr>\r\n          <td><img src=\"cid:logo_parent.gif\" width=\"294\" height=\"84\"></td>\r\n          <td align=\"right\" style=\"padding:55px 10px 0px 0px\" ><font color=\"#F68B1F\" size=\"2\" style=\"font-size:14px;\" face=\"verdana\"><b>\r\n\t\t\tReminder: Tomorrow is Allowance Day for  ${childNames}!\r\n\t\t  </b></font></td>\r\n        </tr>\r\n    </table></td>\r\n  </tr>\r\n  <tr>\r\n    <td style=\"padding:20px;font-size:12px; font-family:verdana;\">\r\n\t<p>Dear ${parentName},</p>\r\n\t<p>\r\n\t  This is to let you know that allowance will be posted on FiftyP tomorrow for ${childNames}, along with other earnings or gifts that may be scheduled. Your credit card will not be charged. For more details, or to make changes to this posting, log in to <a href=''http://www.fiftyp.com''>www.fiftyp.com</a> and select ${personalPronoun} name.  \r\n\t<br/><br/><p>\tThank you for being part of our community. We hope your family is enjoying FiftyPs unique approach to teaching kids financial and social responsibility ... and that you will tell your friends. The bigger our FiftyP community, the greater the interest in what it means to be a money-wise, caring kid.</p>\r\n\t<p> Please let us know if you have any questions or suggestions for us. We are always looking to improve and enhance FiftyP. You can drop us an email at <a href=''http://www.fiftyp.com''>support@fiftyp.com</a> or log in to FiftyP and select Feedback from the Helpful Links menu. </p>\r\n\t  <p>\r\n\t\t\tWith best wishes,<br>\r\n\t\t\tThe FiftyP Team<br>\r\n\t\t\t<a href=''http://www.fiftyp.com''>www.fiftyp.com</a><br>\r\n\t  </p>\r\n\t</td>\r\n  </tr>\r\n  <tr>\r\n    <td bgcolor=\"#7B2B83\" style=\"padding:5px\"> <font  style=\"font-size:11px; line-height:16px\" face=\"verdana\" color=\"#ffffff\">For more information please contact our support team at <a href=''http://www.fiftyp.com''>support@fiftyp.com</a><br>\r\n    </font> </td>\r\n  </tr>\r\n</table>\r\n\r\n</body>' where sys_template_id = 'ALLOWANCE_NOTIFICATION';

/* Ticket #71 Allowance Notification (added missing apostrophe) */
update sys_template set design = '<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\"http://www.w3.org/TR/html4/loose.dtd\">\r\n<html>\r\n<head>\r\n<title>FiftyP</title>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n</head>\r\n<body>\r\n<table width=\"600\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #7B2B83\">\r\n  <tr>\r\n    <td style=\"border-bottom:1px solid #7B2B83\">\r\n      <table width=\"100%\" border=\"0\">\r\n        <tr>\r\n          <td><img src=\"cid:logo_parent.gif\" width=\"294\" height=\"84\"></td>\r\n          <td align=\"right\" style=\"padding:55px 10px 0px 0px\" ><font color=\"#F68B1F\" size=\"2\" style=\"font-size:14px;\" face=\"verdana\"><b>\r\n\t\t\tReminder: Tomorrow is Allowance Day for  ${childNames}!\r\n\t\t  </b></font></td>\r\n        </tr>\r\n    </table></td>\r\n  </tr>\r\n  <tr>\r\n    <td style=\"padding:20px;font-size:12px; font-family:verdana;\">\r\n\t<p>Dear ${parentName},</p>\r\n\t<p>\r\n\t  This is to let you know that allowance will be posted on FiftyP tomorrow for ${childNames}, along with other earnings or gifts that may be scheduled. Your credit card will not be charged. For more details, or to make changes to this posting, log in to <a href=''http://www.fiftyp.com''>www.fiftyp.com</a> and select ${personalPronoun} name.  \r\n\t<br/><br/><p>\tThank you for being part of our community. We hope your family is enjoying FiftyP''s unique approach to teaching kids financial and social responsibility ... and that you will tell your friends. The bigger our FiftyP community, the greater the interest in what it means to be a money-wise, caring kid.</p>\r\n\t<p> Please let us know if you have any questions or suggestions for us. We are always looking to improve and enhance FiftyP. You can drop us an email at <a href=''http://www.fiftyp.com''>support@fiftyp.com</a> or log in to FiftyP and select Feedback from the Helpful Links menu. </p>\r\n\t  <p>\r\n\t\t\tWith best wishes,<br>\r\n\t\t\tThe FiftyP Team<br>\r\n\t\t\t<a href=''http://www.fiftyp.com''>www.fiftyp.com</a><br>\r\n\t  </p>\r\n\t</td>\r\n  </tr>\r\n  <tr>\r\n    <td bgcolor=\"#7B2B83\" style=\"padding:5px\"> <font  style=\"font-size:11px; line-height:16px\" face=\"verdana\" color=\"#ffffff\">For more information please contact our support team at <a href=''http://www.fiftyp.com''>support@fiftyp.com</a><br>\r\n    </font> </td>\r\n  </tr>\r\n</table>\r\n\r\n</body>' where sys_template_id = 'ALLOWANCE_NOTIFICATION';

/* Ticket #71 Allowance Notification (use Dear FiftyP Parent instead of parent nickname) */
update sys_template set design = '<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\"http://www.w3.org/TR/html4/loose.dtd\">\r\n<html>\r\n<head>\r\n<title>FiftyP</title>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n</head>\r\n<body>\r\n<table width=\"600\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #7B2B83\">\r\n  <tr>\r\n    <td style=\"border-bottom:1px solid #7B2B83\">\r\n      <table width=\"100%\" border=\"0\">\r\n        <tr>\r\n          <td><img src=\"cid:logo_parent.gif\" width=\"294\" height=\"84\"></td>\r\n          <td align=\"right\" style=\"padding:55px 10px 0px 0px\" ><font color=\"#F68B1F\" size=\"2\" style=\"font-size:14px;\" face=\"verdana\"><b>\r\n\t\t\tReminder: Tomorrow is Allowance Day for  ${childNames}!\r\n\t\t  </b></font></td>\r\n        </tr>\r\n    </table></td>\r\n  </tr>\r\n  <tr>\r\n    <td style=\"padding:20px;font-size:12px; font-family:verdana;\">\r\n\t<p>Dear FiftyP Parent,</p>\r\n\t<p>\r\n\t  This is to let you know that allowance will be posted on FiftyP tomorrow for ${childNames}, along with other earnings or gifts that may be scheduled. Your credit card will not be charged. For more details, or to make changes to this posting, log in to <a href=''http://www.fiftyp.com''>www.fiftyp.com</a> and select ${personalPronoun} name.  \r\n\t<br/><br/><p>\tThank you for being part of our community. We hope your family is enjoying FiftyP''s unique approach to teaching kids financial and social responsibility ... and that you will tell your friends. The bigger our FiftyP community, the greater the interest in what it means to be a money-wise, caring kid.</p>\r\n\t<p> Please let us know if you have any questions or suggestions for us. We are always looking to improve and enhance FiftyP. You can drop us an email at <a href=''http://www.fiftyp.com''>support@fiftyp.com</a> or log in to FiftyP and select Feedback from the Helpful Links menu. </p>\r\n\t  <p>\r\n\t\t\tWith best wishes,<br>\r\n\t\t\tThe FiftyP Team<br>\r\n\t\t\t<a href=''http://www.fiftyp.com''>www.fiftyp.com</a><br>\r\n\t  </p>\r\n\t</td>\r\n  </tr>\r\n  <tr>\r\n    <td bgcolor=\"#7B2B83\" style=\"padding:5px\"> <font  style=\"font-size:11px; line-height:16px\" face=\"verdana\" color=\"#ffffff\">For more information please contact our support team at <a href=''http://www.fiftyp.com''>support@fiftyp.com</a><br>\r\n    </font> </td>\r\n  </tr>\r\n</table>\r\n\r\n</body>' where sys_template_id = 'ALLOWANCE_NOTIFICATION';

/* Ticket #71 Allowance Notification (use parent name if available in billing address) */
update `sys_template` set `design` = '<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\"http://www.w3.org/TR/html4/loose.dtd\">\r\n<html>\r\n<head>\r\n<title>FiftyP</title>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n</head>\r\n<body>\r\n<table width=\"600\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #7B2B83\">\r\n  <tr>\r\n    <td style=\"border-bottom:1px solid #7B2B83\">\r\n      <table width=\"100%\" border=\"0\">\r\n        <tr>\r\n          <td><img src=\"cid:logo_parent.gif\" width=\"294\" height=\"84\"></td>\r\n          <td align=\"right\" style=\"padding:55px 10px 0px 0px\" ><font color=\"#F68B1F\" size=\"2\" style=\"font-size:14px;\" face=\"verdana\"><b>\r\n\t\t\tReminder: Tomorrow is Allowance Day for  ${childNames}!\r\n\t\t  </b></font></td>\r\n        </tr>\r\n    </table></td>\r\n  </tr>\r\n  <tr>\r\n    <td style=\"padding:20px;font-size:12px; font-family:verdana;\">\r\n\tDear ${parentName},<br/><br/>  This is to let you know that allowance will be posted on FiftyP tomorrow for ${childNames}, along with other earnings or gifts that may be scheduled. Your credit card will not be charged. For more details, or to make changes to this posting, log in to <a href=''http://www.fiftyp.com''>www.fiftyp.com</a> and select ${personalPronoun} name.  \r\n\t<br/><br/>\tThank you for being part of our community. We hope your family is enjoying FiftyP''s unique approach to teaching kids financial and social responsibility ... and that you will tell your friends. The bigger our FiftyP community, the greater the interest in what it means to be a money-wise, caring kid.<br/><br/> Please let us know if you have any questions or suggestions for us. We are always looking to improve and enhance FiftyP. You can drop us an email at <a href=''http://www.fiftyp.com''>support@fiftyp.com</a> or log in to FiftyP and select Feedback from the Helpful Links menu. <br/><br/> With best wishes,<br>\r\n\t\t\tThe FiftyP Team<br>\r\n\t\t\t<a href=''http://www.fiftyp.com''>www.fiftyp.com</a><br>\r\n\t  </p>\r\n\t</td>\r\n  </tr>\r\n  <tr>\r\n    <td bgcolor=\"#7B2B83\" style=\"padding:5px\"> <font  style=\"font-size:11px; line-height:16px\" face=\"verdana\" color=\"#ffffff\">For more information please contact our support team at <a href=''http://www.fiftyp.com''>support@fiftyp.com</a><br>\r\n    </font> </td>\r\n  </tr>\r\n</table>\r\n\r\n</body>' where `sys_template_id` = 'ALLOWANCE_NOTIFICATION';