-- SQL update script for release v1.14.

UPDATE cause SET photo1_url = 'share/42.HoS_1.png' WHERE cause_id = 1;
UPDATE cause SET hos_full_txt = '<i>Protects</i>^ the Coast of India! Monkeys, herons, and other animals along the coast of India will soon have new mangrove trees to live in, thanks to ChildName of FiftyP. ChildName donated dollaramount from@ gender Share account to the Carbon Funds Tree Planting Program, which plants trees to protect the short line and the many creatures that live there Mangrove trees drink salt water, so they do well by the sea. Their root prevent mud and sand from being washed away, reducing damage from storms and allowing other plant to grow. Each mangrove is like an entire forest: Its branches provide food for monkeys and nesting sites for birds, while its tangled root provide a surface for sponges and a hiding place for young fish.' WHERE cause_id = 1;

UPDATE cause SET photo1_url = 'share/42.HoS_2.png' WHERE cause_id = 2;
UPDATE cause SET hos_full_txt = 'Builds Forests,^ <i>Creates Habitats!</i> The destruction of forests is a double whammy for the environment. Animals lose their habitats, and the loss of trees - which absorb harmful@ gases from airplanes, autos, and more - makes global warming worse. Now ChildName of FiftyP is working to put things right. ChildName donated dollaramount from gender Share account to support Reforestation project that will return trees to land that once held healthy forests. One project, in Louisiana, will create a home for the threatened Louisiana black bear and many other threatened species. Another project will create safe habitats for mammals, birds and reptiles in Central America. The new forest will also pull harmful gases from the air, reducing the effect of global warming throughout the world.' WHERE cause_id = 2;

UPDATE cause SET photo1_url = 'share/42.HoS_3.png' WHERE cause_id = 3;
UPDATE cause SET hos_full_txt = 'Turns Trash^ <i>into Energy!</i> Garbage landfills are not only stinky...they are a danger to the environment. As the trash decays it releases methane, a gas that contributes@ to global warming. But thanks to ChildName of FiftyP, who donated dollaramount from gender Share account, programs in Hampshire and Massachusetts are using methane to create electricity. The methane is captured from landfills before it can escape into the air, and burned to form less dangerous gases. These gases are used to power turbines, which produce the electricity that heats homes, run computers, and much more. So ChildName contribution is helping turn trash into energy, and at the same time protecting the earth from methanes harmful effects.' WHERE cause.cause_id = 3;

UPDATE cause SET photo1_url = 'share/42.HoS_4.png' WHERE cause_id = 4;
UPDATE cause SET hos_full_txt = 'Puts the Wind^ <i>to Work!</i> While many people worry about the harmful effects of global warming, ChildName of FiftyP is doing something about it. ChildName donated dollaramount from@ gender Share account to support Wind Power, one of the best ways to use nature as a clean energy source. gender contribution will help build wind turbines in Texas, Montana, and Iowa. These big machines, with blades that can be as big as a football field, collect breezes from oceans and open fields and convert them to electricity for businesses and homes. Wind power can reduce our use of oil and other fossil fuels, which contribute to rising temperatures, melting glaciers, and violent storms throughout the world.' WHERE cause_id = 4;

CREATE TABLE fiftyp_donation (
  fiftyp_donation_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  amount DOUBLE NOT NULL,
  start_date DATETIME NOT NULL,
  end_date DATETIME NOT NULL,
  PRIMARY KEY (fiftyp_donation_id)
) ENGINE = InnoDB;

INSERT INTO fiftyp_donation (amount, start_date, end_date) VALUES (500, '2008-01-01 00:00:00', '2009-01-31 23:59:59');
INSERT INTO fiftyp_donation (amount, start_date, end_date) VALUES (230, '2009-02-01 00:00:00', '2009-02-28 23:59:59');

UPDATE cause SET hos_full_txt = '<i>Protects</i>^ the Coast of India! Monkeys, herons, and other animals along the coast of India will soon have new mangrove trees to live in, thanks to ChildName of FiftyP. ChildName donated $dollaramount from@ gender share account to the Carbon Fund\\''s Tree Planting Program, which plants trees to protect the short line and the many creatures that live there. Mangrove trees drink salt water, so they do well by the sea. Their root prevents mud and sand from being washed away, reducing damage from storms and allowing other plants to grow. Each mangrove is like an entire forest. Its branches provide food for monkeys and nesting sites for birds, while its tangled roots provide a surface for sponges and a hiding place for young fish.' WHERE cause_id = 1;
UPDATE cause SET hos_full_txt = 'Builds Forests,^ <i>Creates Habitats</i>! The destruction of forests is a double whammy for the environment. Animals lose their habitats, and the loss of trees which absorb harmful@ gases from airplanes, auto more makes global warming worse. Now ChildName of FiftyP is working to put things right. ChildName Donated $dollaramount from gender share account to support Reforestation project that will return trees to land that once held healthy forests. One project, in Louisiana, will create a home for the threatened Louisiana black bear and many other threatened species. Another project will create safe habitats for mammals, birds and reptiles in Central America. The new forest will also pull harmful gases from the air, reducing the effect of global warming throughout the world.' WHERE cause_id = 2;
UPDATE cause SET hos_full_txt = 'Turns Trash^ <i>into Energy!</i> Garbage landfills are not only stinky. They are a danger to the environment. As the trash decays it releases methane, a gas that contributes@ to global warming. But thanks to ChildName of FiftyP, who donated dollaramount from gender share account, programs in Hampshire and Massachusetts are using methane to create electricity. The methane is captured from landfills before it can escape into the air, and burned to form less dangerous gases. These gases are used to power turbines, which produce the electricity that heats homes, run computers, and much more. So ChildName contribution is helping turn trash into energy, and at the same time protecting the earth from methane\\''s harmful effects.' WHERE cause_id = 3;
UPDATE cause SET hos_full_txt = 'Puts the Wind^ <i>to Work!</i> While many people worry about the harmful effects of global warming, ChildName of FiftyP is doing something about it. ChildName donated $dollaramount from@ gender share account to support Wind Power, one of the best ways to use nature as a clean energy source. gender\\''s contribution will help build wind turbines in Texas, Montana, and Iowa. These big machines, with blades that can be as big as a football field, collect breezes from oceans and open fields and convert them to electricity for businesses and homes. Wind power can reduce our use of oil and other fossil fuels, which contribute to rising temperatures, melting glaciers, and violent storms throughout the world.' WHERE cause_id = 4;

UPDATE sys_template SET design = '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\r\n<html xmlns="http://www.w3.org/1999/xhtml">\r\n<head>		\r\n	<title>FiftyP</title>\r\n</head>\r\n<body>\r\n<img  src="cid:logo_parent.gif"  /><br />\r\n<font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"><b>${userName} has sent you an ecard from FiftyP </b></font> \r\n<img  src="cid:${imageName}" style="position:absolute;left:0px;top:120px;z-index:-1;" /> \r\n  <table width="250" align="left" >\r\n    <tr>\r\n        <td >\r\n          <p style="color:#77823B;font-family:verdana;font-size:14px;"><b>From ${userName},</b>\r\n            <br />${userName}@fiftyp.com \r\n          </p>\r\n		<p style="font-family:verdana;font-size:13px;">${spreadTxt!""?cap_first?chop_linebreak}\r\n		</p>		\r\n		<p style="font-family:verdana;font-size:13px;">Check it out!<br>\r\n		<a target="_blank" href="http://www.fiftyp.com" style="color:#000000">www.fiftyp.com</a>\r\n		</p>\r\n  </tr>\r\n</table>\r\n<span style="position:absolute; left:15px; top:500px;"><p><font color="#F68B1F" size="1" style="font-size:14px;" face="verdana">${customMsg}</font></p></span></body>'
  WHERE sys_template.sys_template_id = 'SPREAD_THE_WORD_CODE' LIMIT 1;

update sys_template set design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd">\r\n<html>\r\n<head>\r\n<title>FiftyP</title>\r\n<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">\r\n</head>\r\n<body>\r\n<table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">\r\n  <tr>\r\n    <td style="border-bottom:1px solid #7B2B83">\r\n  <table width="100%" border="0">\r\n    <tr>\r\n    <td><img src="cid:logo_parent.gif" width="294" height="84"></td>\r\n    <td align="right" style="padding:55px 10px 0px 0px"><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"><b>Account Activation</b></font></td>\r\n    </tr>\r\n  </table>\r\n</td>\r\n  </tr>\r\n  <tr>\r\n    <td style="padding:20px;font-size:12px; font-family:verdana;">\r\n  <p>Dear FiftyP parent,</p>\r\n  <p>Please click on the link below to activate your account</p>\r\n  <p><a href="${link}">${link}<a/></p>\r\n  <br>Regards,<br/> \r\n  The FiftyP team \r\n  </td>\r\n  </tr>\r\n  <tr>\r\n    <td bgcolor="#7B2B83" style="padding:5px"> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">For more information please contact our support team at </font><a href=''http://www.fiftyp.com''><font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">support@fiftyp.com</font></a><br>\r\n    </td>\r\n  </tr>\r\n</table>\r\n\r\n</body>\r\n</html>' where sys_template_id = 'ACTIVATION_CODE';
update sys_template set design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd">\r\n<html>\r\n<head>\r\n<title>FiftyP</title>\r\n<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">\r\n</head>\r\n<body>\r\n<table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">\r\n  <tr>\r\n    <td style="border-bottom:1px solid #7B2B83">\r\n      <table width="100%" border="0">\r\n        <tr>\r\n          <td><img src="cid:logo_parent.gif" width="294" height="84"></td>\r\n          <td align="right" style="padding:55px 10px 0px 0px" ><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"><b>\r\n			Reminder: Tomorrow is allowance day for  ${childNames}!\r\n		  </b></font></td>\r\n        </tr>\r\n    </table></td>\r\n  </tr>\r\n  <tr>\r\n    <td style="padding:20px;font-size:12px; font-family:verdana;">\r\n	Dear ${parentName},<br/><br/>  This is to let you know that allowance will be posted on FiftyP tomorrow for ${childNames} along with other earnings or gifts that may be scheduled. Your credit card will not be charged. For more details, or to make changes to this posting, log in to <a href=''http://www.fiftyp.com''>www.fiftyp.com</a> and select ${personalPronoun} name.  \r\n	<br/><br/>	Thank you for being part of our community. We hope your family is enjoying FiftyP''s unique approach to teaching kids financial and social responsibility... and that you will tell your friends. The bigger our FiftyP community, the greater the interest in what it means to be a money-wise, caring kid.<br/><br/> Please let us know if you have any questions or suggestions for us. We are always looking to improve and enhance FiftyP. You can drop us an email at <a href=''http://www.fiftyp.com''>support@fiftyp.com</a> or log in to FiftyP and select Feedback from the Helpful Links menu. <br/><br/> With best wishes,<br>\r\n			The FiftyP Team<br>\r\n			<a href=''http://www.fiftyp.com''>www.fiftyp.com</a><br>\r\n	  </p>\r\n	</td>\r\n  </tr>\r\n  <tr>\r\n    <<td bgcolor="#7B2B83" style="padding:5px"> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">For more information please contact our support team at </font><a href=''http://www.fiftyp.com''><font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">support@fiftyp.com</font></a><br>\r\n    </td>\r\n  </tr>\r\n</table>\r\n\r\n</body>' where sys_template_id = 'ALLOWANCE_NOTIFICATION';
update sys_template set design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd">\r\n<html>\r\n<head>\r\n<title>FiftyP</title>\r\n<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">\r\n</head>\r\n<body>\r\n<table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">\r\n  <tr>\r\n    <td style="border-bottom:1px solid #7B2B83">\r\n      <table width="100%" border="0">\r\n        <tr>\r\n          <td><img src="cid:logo_parent.gif" width="294" height="84"></td>\r\n          <td align="right" style="padding:55px 10px 0px 0px" nowrap="nowrap"><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"><b>Forgot Password</b></font></td>\r\n        </tr>\r\n    </table></td>\r\n  </tr>\r\n  <tr>\r\n    <td style="padding:20px;font-size:12px; font-family:verdana;">\r\n	<p>Dear ${userName},</p>\r\n	<p>Your account expires in less than 5 days. We will automatically charge you</p>\r\n	<p>If you wish to stop your account, please login and disable your family account</b></p>\r\n	<br/>	<p>Regards,<br/> \r\n	The FiftyP team \r\n	</p>\r\n	</td>\r\n  </tr>\r\n  <tr>\r\n    <td bgcolor="#7B2B83" style="padding:5px"> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">For more information please contact our support team at </font><a href=''http://www.fiftyp.com''><font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">support@fiftyp.com</font></a><br>\r\n    </td>\r\n  </tr>\r\n</table>\r\n\r\n</body>\r\n</html>' where sys_template_id = 'FIVE_DAYS_EXPIRY_NOTIFICATION';

update sys_template set design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd">\r\n<html>\r\n<head>\r\n<title>FiftyP</title>\r\n<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">\r\n</head>\r\n<body>\r\n<br>\r\n<br>\r\n<table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">\r\n  <tr>\r\n    <td style="border-bottom:1px solid #7B2B83">\r\n      <table width="100%" border="0">\r\n        <tr>\r\n          <td align="center"  nowrap="nowrap"><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"><b>FiftyP site feedback from child</b></font></td>\r\n        </tr>\r\n    </table></td>\r\n  </tr>\r\n  <tr>\r\n    <td style="padding:20px;font-size:12px; font-family:verdana;">\r\n	<p><b> ${userName}</b> has given Feedback on${pageName}.</p>\r\n	<p>Feedback rate: ${feedback}.</p>\r\n\r\n	<p>This feedback is generated from the machine ${clientAddress} on ${date}\r\n	</td>\r\n  </tr>\r\n\r\n</table>' where sys_template_id = 'CHILD_FEED_BACK';
update sys_template set subject = 'FiftyP site feedback from child' where sys_template_id = 'CHILD_FEED_BACK';

update sys_template set design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd">\r\n<html>\r\n<head>\r\n<title>FiftyP</title>\r\n<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">\r\n</head>\r\n<body>\r\n<table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">\r\n  <tr>\r\n    <td style="border-bottom:1px solid #7B2B83">\r\n      <table width="100%" border="0">\r\n        <tr>\r\n          <td><img src="cid:logo_parent.gif" width="294" height="84"></td>\r\n          <td align="right" style="padding:55px 10px 0px 0px" nowrap="nowrap"><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"><b>Forgot password</b></font></td>\r\n        </tr>\r\n    </table></td>\r\n  </tr>\r\n  <tr>\r\n    <td style="padding:20px;font-size:12px; font-family:verdana;">\r\n	<p>Dear FiftyP parent,</p>\r\n	<p>You requested to change your password.</p>\r\n	<p>Your new password is: <b>${newPassword}</b></p>\r\n	<br/>Regards,<br/> \r\n	The FiftyP team \r\n	\r\n	</td>\r\n  </tr>\r\n  <tr>\r\n    <td bgcolor="#7B2B83" style="padding:5px"> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">For more information please contact our support team at </font><a href=''http://www.fiftyp.com''><font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">support@fiftyp.com</font></a><br>\r\n    </td>\r\n  </tr>\r\n</table>\r\n\r\n</body>\r\n</html>' where sys_template_id = 'FORGOT_PASSWORD';
update sys_template set subject = 'FiftyP new password' where sys_template_id = 'FORGOT_PASSWORD';

update sys_template set design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd">\r\n<html>\r\n<head>\r\n<title>FiftyP</title>\r\n<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">\r\n</head>\r\n<body>\r\n<table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">\r\n  <tr>\r\n    <td style="border-bottom:1px solid #7B2B83">\r\n      <table width="100%" border="0">\r\n        <tr>\r\n          <td><img src="cid:logo_parent.gif" width="294" height="84"></td>\r\n          <td align="right" style="padding:55px 10px 0px 0px" nowrap="nowrap"><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"><b>\r\n			Confirmation: Child added to family account\r\n		  </b></font></td>\r\n        </tr>\r\n    </table></td>\r\n  </tr>\r\n  <tr>\r\n    <td style="padding:20px;font-size:12px; font-family:verdana;">\r\n	<p>Dear FiftyP parent,</p>\r\n	<p>\r\n	  Thank you for adding another child to your FiftyP account. You have activated a free membership as of ${activationDate?string("MMMM d, yyyy")}.    \r\n	<p>This free membership introduces your child to basic money management skills and to charitable causes. FiftyP also makes it easy for you to keep track of ${personalPronoun} allowance and extra earnings.</p>\r\n	<p>If you''d like ${personalPronoun} to get even more out of FiftyP, consider switching to a one-year or three-year membership plan. Both give kids hands-on experience with saving, spending, and sharing the best way to learn. Now''s the time to help ${personalPronoun} form healthy habits!</p>\r\n	<p>You can upgrade your child''s membership at any time: Log in to your FiftyP account at www.fiftyp.com and click the <strong>Membership </strong>button.</p>\r\n	<p>Questions? Please email us at <a href="mailto:support@fiftyp.com">support@fiftyp.com </a>. </p>\r\n	 <p>With best wishes,<br>\r\n	  Team FiftyP<br>\r\n	  <a href=''http://www.fiftyp.com''>www.fiftyp.com</a><br>\r\n	  </p>\r\n	</td>\r\n  </tr>\r\n  <tr>\r\n    <td bgcolor="#7B2B83" style="padding:5px"> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">For more information please contact our support team at </font><a href=''http://www.fiftyp.com''><font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">support@fiftyp.com</font></a><br>\r\n    </td>\r\n  </tr>\r\n</table>\r\n\r\n</body>' where sys_template_id = 'ORDER_CONFIRMATION_NEW_CHILD_FREE';
update sys_template set subject = 'Confirmation: Child added to family account' where sys_template_id = 'ORDER_CONFIRMATION_NEW_CHILD_FREE';

update sys_template set design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd">\r\n<html>\r\n<head>\r\n<title>FiftyP</title>\r\n<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">\r\n</head>\r\n<body>\r\n<table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">\r\n  <tr>\r\n    <td style="border-bottom:1px solid #7B2B83">\r\n      <table width="100%" border="0">\r\n        <tr>\r\n          <td><img src="cid:logo_parent.gif" width="294" height="84"></td>\r\n          <td align="right" style="padding:55px 10px 0px 0px" nowrap="nowrap"><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"><b>\r\n			Confirmation: Child added to family account\r\n		  </b></font></td>\r\n        </tr>\r\n    </table></td>\r\n  </tr>\r\n  <tr>\r\n    <td style="padding:20px;font-size:12px; font-family:verdana;">\r\n	<p>Dear ${parentName},</p>\r\n	<p>\r\n	  Thank you for adding another child to your FiftyP account. Our FiftyP community grows stronger with each new member!    \r\n	<p>This new ${membershipType} membership has been activated as of ${activationDate?string("MMMM d, yyyy")}. Have your child jump in and get started!</p>\r\n	<p>If at any time you wish to alter the membership, log in to your FiftyP account at <a href="http://www.fiftyp.com">www.fiftyp.com </a> and click the <strong>Membership </strong>button.</p>\r\n	<p>Questions? Please email us at <a href="mailto:support@fiftyp.com">support@fiftyp.com </a>.</p>\r\n	<p>Thanks for putting your child on the right path! </p>\r\n	With best wishes,<br>\r\n	Team FiftyP<br>\r\n	<a href=''http://www.fiftyp.com''>www.fiftyp.com</a><br>\r\n	</td>\r\n  </tr>\r\n  <tr>\r\n    <td bgcolor="#7B2B83" style="padding:5px"> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">For more information please contact our support team at </font><a href=''http://www.fiftyp.com''><font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">support@fiftyp.com</font></a><br>\r\n    </td>\r\n  </tr>\r\n</table>\r\n\r\n</body>' where sys_template_id = 'ORDER_CONFIRMATION_NEW_CHILD_ONE_OR_THREE_YEAR ';
update sys_template set subject = 'Confirmation: Child added to family account' where sys_template_id = 'ORDER_CONFIRMATION_NEW_CHILD_ONE_OR_THREE_YEAR';

update sys_template set design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd">\r\n<html>\r\n<head>\r\n<title>FiftyP</title>\r\n<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">\r\n</head>\r\n<body>\r\n<table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">\r\n  <tr>\r\n    <td style="border-bottom:1px solid #7B2B83">\r\n      <table width="100%" border="0">\r\n        <tr>\r\n          <td><img src="cid:logo_parent.gif" width="294" height="84"></td>\r\n          <td align="right" style="padding:55px 10px 0px 0px" nowrap="nowrap"><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"><b>\r\n      Order confirmation of share transaction/tax deduct\r\n      </b></font></td>\r\n        </tr>\r\n    </table></td>\r\n  </tr>\r\n  <tr>\r\n    <td style="padding:20px;font-size:12px; font-family:verdana;">\r\n  <p>Dear ${parentName},</p>\r\n  <p>\r\n    We are writing to confirm your recent donation to ${organization} in support of ${donationCause}. Your family can be proud of supporting this organization and its important work.     \r\n  <p>Your donation of $${donationAmount}  has been processed. Here are the details:\r\n  <p><br>\r\n      Date of Transaction: ${transactionDate?string("MMMM d, yyyy")}<br>\r\n      Transaction #: ${transactionId}<br> \r\n    Payment method: ${paymentMethod}, \r\n\r\n\r\n card #${ccDisplayNumber} </p>\r\n    <p>To learn more about FiftyP and our commitment to raising social awareness, visit us at <a href="http://www.fiftyp.com">www.fiftyp.com </a> or check our FAQs at <a href="http://www.fiftyp.com/faq">www.fiftyp.com/faq </a>. Still have questions? Email us at www.fiftyp.com/support . </p>\r\n    <p>Please keep us informed of any changes to your email address. You can update your information by logging in to your FiftyP account and clicking on Your Profile .</p>\r\n    <p>[The Carbon Fund] is a 501(c)(3) charitable organization. Please consider printing this confirmation for your records.</p>\r\n    <p>We appreciate your commitment to making a difference! </p>\r\n    \r\n      With best wishes,<br>\r\n      Team FiftyP<br>\r\n      <a href=''http://www.fiftyp.com''>www.fiftyp.com</a><br>\r\n    \r\n  </td>\r\n  </tr>\r\n  <tr>\r\n    <td bgcolor="#7B2B83" style="padding:5px"> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">For more information please contact our support team at </font><a href=''http://www.fiftyp.com''><font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">support@fiftyp.com</font></a><br>\r\n    </td>\r\n  </tr>\r\n</table>\r\n\r\n</body>' where sys_template_id = 'ORDER_CONFIRMATION_SHARE_TRANSACTION';
update sys_template set subject = 'Order confirmation of share transaction' where sys_template_id = 'ORDER_CONFIRMATION_SHARE_TRANSACTION';

update sys_template set design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd">\r\n<html>\r\n<head>\r\n<title>FiftyP</title>\r\n<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">\r\n</head>\r\n<body>\r\n<br>\r\n<br>\r\n<table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">\r\n  <tr>\r\n    <td style="border-bottom:1px solid #7B2B83">\r\n      <table width="100%" border="0">\r\n        <tr>\r\n          <td align="center"  nowrap="nowrap"><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"><b>FiftyP site feedback from parent </b></font></td>\r\n        </tr>\r\n    </table></td>\r\n  </tr>\r\n  <tr>\r\n    <td style="padding:20px;font-size:12px; font-family:verdana;">\r\n	<p><b> ${userName}</b> has given Feedback on ${pageName}.</p>\r\n	<p>Content Rating: <#if "${contentRating}"!="undefined">${contentRating} <#else>N/A</#if></p>\r\n	<p>Design Rating: <#if "${desingRating}"!="undefined">${desingRating}   <#else>N/A</#if></p>\r\n	<p>Use Rating: <#if "${useRating}"!="undefined">${useRating} 		  <#else>N/A</#if></p>\r\n	<p>OverAll Rating: <#if "${overAllRating}"!="undefined">${overAllRating} <#else>N/A</#if></p>\r\n	<p>Selected Topic:<#if "${topic}"!="choose">${topic} <#else>N/A</#if></p>\r\n	<p>Topic Comments:<#if "${topic}"!="choose">${topicComment} <#else>N/A</#if></p>\r\n	<br/>	\r\n	<p>This feedback is generated from the machine ${clientAddress} on ${date}\r\n	</td>\r\n  </tr>\r\n\r\n</table>' where sys_template_id = 'PARENT_FEED_BACK';
update sys_template set subject = 'FiftyP site feedback from parent' where sys_template_id = 'PARENT_FEED_BACK';

update sys_template set design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd">\r\n<html>\r\n<head>\r\n<title>FiftyP</title>\r\n<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">\r\n</head>\r\n<body>\r\n<table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">\r\n  <tr>\r\n    <td style="border-bottom:1px solid #7B2B83">\r\n      <table width="100%" border="0">\r\n        <tr>\r\n          <td><img src="cid:logo_parent.gif" width="294" height="84"></td>\r\n          <td align="right" style="padding:55px 10px 0px 0px" nowrap="nowrap"><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"><b>\r\n			${request}\r\n		  </b></font></td>\r\n        </tr>\r\n    </table></td>\r\n  </tr>\r\n  <tr>\r\n    <td style="padding:20px;font-size:12px; font-family:verdana;">\r\n	<p>Dear ${parentName},</p>\r\n	<p>\r\n		<b>A request is awaiting your approval at FiftyP.com!</b>\r\n		<br/> \r\n		<b>${childName}</b> ${childRequest}<br>\r\n		You''ll find details on the Parent Summary page at <a href=''http://www.fiftyp.com''>www.fiftyp.com</a>. \r\n		<br/> \r\n\r\n</p>\r\n	<br/>	\r\n        	With best wishes,<br>\r\n		Team FiftyP<br>\r\n		<a href=''http://www.fiftyp.com''>www.fiftyp.com</a><br>\r\n		\r\n	</td>\r\n  </tr>\r\n  <tr>\r\n    <td bgcolor="#7B2B83" style="padding:5px"> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">For more information please contact our support team at </font><a href=''http://www.fiftyp.com''><font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">support@fiftyp.com</font></a><br>\r\n    </td>\r\n  </tr>\r\n</table>\r\n\r\n</body>' where sys_template_id = 'REQUEST_SEND_TO_PARENT';

update sys_template set design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd">\r\n<html>\r\n<head>\r\n<title>FiftyP</title>\r\n<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">\r\n</head>\r\n<body>\r\n<br>\r\n<br>\r\n<table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">\r\n  <tr>\r\n    <td style="border-bottom:1px solid #7B2B83">\r\n      <table width="100%" border="0">\r\n        <tr>\r\n          <td align="center"  nowrap="nowrap"><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"><b>FiftyP site suggested cause from child</b></font></td>\r\n        </tr>\r\n    </table></td>\r\n  </tr>\r\n  <tr>\r\n    <td style="padding:20px;font-size:12px; font-family:verdana;">\r\n	<p><b> ${userName}</b> suggested the following cause: </b></p>\r\n	<p> Location: <b> ${location}</b>.</p>\r\n	<p> Category: <b> ${category}</b>.</p>\r\n	<p> Cause: <b> ${cause}</b>.</p>\r\n	\r\n	<p>This suggested cause is generated from the machine <b>${clientAddress}</b> on <b>${date}</b>\r\n	</td>\r\n  </tr>\r\n\r\n</table>' where sys_template_id = 'SUGGEST_CAUSE_CODE';
update sys_template set subject = 'FiftyP site suggested cause from child' where sys_template_id = 'SUGGEST_CAUSE_CODE';

update sys_template set design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd">\r\n<html>\r\n<head>\r\n<title>FiftyP</title>\r\n<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">\r\n</head>\r\n<body>\r\n<table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">\r\n  <tr>\r\n    <td style="border-bottom:1px solid #7B2B83">\r\n      <table width="100%" border="0">\r\n        <tr>\r\n          <td><img src="cid:logo_parent.gif" width="294" height="84"></td>\r\n          <td align="right" style="padding:55px 10px 0px 0px" nowrap="nowrap"><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"><b>\r\n			Order confirmation of gift card\r\n		  </b></font></td>\r\n        </tr>\r\n    </table></td>\r\n  </tr>\r\n  <tr>\r\n    <td style="padding:20px;font-size:12px; font-family:verdana;">\r\n	<p>Dear ${parentName},</p>\r\n	<p>We''re writing to confirm your recent gift card purchase. Your payment has been processed. You can expect delivery by first-class mail within 7 to 10 business days. </p>\r\n	<p>\r\n		Purchase date: ${purchaseDate?string("MMMM d, yyyy")}\r\n		<br>\r\n      Confirmation #: ${orderNumber}</p>\r\n	  <p>Item: ${giftName} gift card <br>\r\n	  Value: $${giftPrice} <br>\r\n	  Merchant Charge : ${merchantValue}<br> \r\n	  Shipping &amp; handling: ${shippingCost} <br>\r\n	  Total: $${total}<br>\r\n	  Method of payment: ${paymentMethod}, \r\n\r\n\r\n card #${ccDisplayNumber}</p>\r\n	  <p> Shipping Address: <br>\r\n        ${buyerName} <br>\r\n        ${streetName} <br>\r\n        ${cityName} <br>\r\n        ${state} <br>\r\n        ${country} <br>\r\n      </p>\r\n	  <p>For questions about your child''s gift card purchase, or to learn more about our retail partners, go to www.fiftyp.com/faq . Still have questions? Email us at www.fiftyp.com/support . </p>\r\n	  <p>Please keep us informed of any changes to your email address. You can update your information by logging in to your FiftyP account and clicking on “Your Profile�?.</p>\r\n	  <p>Thanks for supporting your child in this purchase. Allowing our kids to make spending decisions gives them a great opportunity to practice money management skills. </p>\r\n	  \r\n	  With best wishes,<br>\r\n			Team FiftyP<br>\r\n			<a href=''http://www.fiftyp.com''>www.fiftyp.com</a><br>\r\n	  	</td>\r\n  </tr>\r\n  <tr>\r\n    <td bgcolor="#7B2B83" style="padding:5px"> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">For more information please contact our support team at </font><a href=''http://www.fiftyp.com''><font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">support@fiftyp.com</font></a><br>\r\n    </td>\r\n  </tr>\r\n</table>\r\n\r\n</body>' where sys_template_id = 'ORDER_CONFIRMATION_GIFT_CARD';
update sys_template set subject = 'Order confirmation of gift card transaction' where sys_template_id = 'ORDER_CONFIRMATION_GIFT_CARD';

update sys_template set design = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd">\r\n<html>\r\n<head>\r\n<title>FiftyP</title>\r\n<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">\r\n</head>\r\n<body>\r\n<table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">\r\n  <tr>\r\n    <td style="border-bottom:1px solid #7B2B83">\r\n      <table width="100%" border="0">\r\n        <tr>\r\n          <td><img src="cid:logo_parent.gif" width="294" height="84"></td>\r\n          <td align="right" style="padding:55px 10px 0px 0px" nowrap="nowrap"><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"><b>\r\n			Order Confirmation of Membership Card Purchase\r\n		  </b></font></td>\r\n        </tr>\r\n    </table></td>\r\n  </tr>\r\n  <tr>\r\n    <td style="padding:20px;font-size:12px; font-family:verdana;">\r\n	<p>Dear ${parentName},</p>\r\n	<p>\r\n	  Thank you for your recent purchase of FiftyP Membership Cards. Your payment has been processed. You can expect delivery by first-class mail within 7 business days.    	<p>Here are the details:</p>\r\n	<p>Purchase date: ${purchaseDate?string("MMMM d, yyyy")} <br>\r\n	Order #: ${orderNumber}</p>\r\n	Quantity: ${quantity} Membership Cards <br>\r\n	Unit Price: $${unitPrice} per card <br>\r\n	Subtotal: $${subtotal} <br>\r\n	Shipping &amp; handling: $${shippingHandling} <br>\r\n	Total: $${total} <br>\r\n	Payment method: ${paymentMethod}, card #${ccDisplayNumber}\r\n	<p>Shipping Address: <br>\r\n	  ${buyerName} <br>\r\n	  ${streetName} <br>\r\n	  ${cityName}</p>\r\n	<p>To learn more about FiftyP, please visit us at <a href="http://www.fiftyp.com">www.fiftyp.com </a> or check our FAQs at <a href="http://www.fiftyp.com/faq">www.fiftyp.com/faq </a>. Still have questions? Email us at www.fiftyp.com/support . </p>\r\n	<p>Thank you for introducing FiftyP to your family, friends, colleagues and customers. We appreciate your support. </p>\r\n	<p>&nbsp;	  </p>\r\n	  <p>\r\n			With best wishes,<br>\r\n			Team FiftyP<br>\r\n			<a href=''http://www.fiftyp.com''>www.fiftyp.com</a><br>\r\n	  </p>\r\n	</td>\r\n  </tr>\r\n  <tr>\r\n    <td bgcolor="#7B2B83" style="padding:5px"> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">For more information please contact our support team at </font><a href=''http://www.fiftyp.com''><font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">support@fiftyp.com</font></a><br>\r\n    </td>\r\n  </tr>\r\n</table>\r\n\r\n</body>' where sys_template_id = 'ORDER_CONFIRMATION_MEMBERSHIP_CARD_TRANSACTION';

ALTER TABLE `mail_inbox` MODIFY COLUMN `msg_text` VARCHAR(1024) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL;

insert into product_description (name,choose_desc,disclamer_desc,confirm_desc,image_url)
values ('The Bay','Open the possibilities! Hbc Gift Cards are great for any occasions and a great way to shop at all of our stores in the Hbc family. Whether it\'s The Bay, Zellers, Home Outfitters, or Designer Depot, with lots of great items to choose from in our large selection, you\'ll be sure to find just the right thing.  We make it convenient to choose from over 1,000,000 products  by  shopping at any of our more than 500 locations of the Hbc family of stores coast to coast.','Hbc, The Bay, Zellers, Home Outfitters, and Designer  Depot  are not affiliated with FiftyP and are not sponsors or co-sponsors with this promotion.','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/theBay.png'),
('Zellers','Open the possibilities! Hbc Gift Cards are great for any occasions and a great way to shop at all of our stores in the Hbc family. Whether it\'s The Bay, Zellers, Home Outfitters, or Designer Depot, with lots of great items to choose from in our large selection, you\'ll be sure to find just the right thing.  We make it convenient to choose from over 1,000,000 products  by  shopping at any of our more than 500 locations of the Hbc family of stores coast to coast.','Hbc, The Bay, Zellers, Home Outfitters, and Designer Depot are not affiliated with FiftyP and are not sponsors or co-sponsors with this promotion.','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/zellers.png'),
('Home Outfitters','Open the possibilities! Hbc Gift Cards are great for any occasions and a great way to shop at all of our stores in the Hbc family. Whether it\'s The Bay, Zellers, Home Outfitters, or Designer Depot, with lots of great items to choose from in our large selection, you\'ll be sure to find just the right thing.  We make it convenient to choose from over 1,000,000 products  by  shopping at any of our more than 500 locations of the Hbc family of stores coast to coast.','Hbc, The Bay, Zellers, Home Outfitters, and Designer Depot are not affiliated with FiftyP and are not sponsors or co-sponsors with this promotion.','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/homeOutfitters.png'),
('Petro-Canada','<p>Stop in and fill up, not just on gas  but so much more. Petro - Canada gift cards make a great gift because everyone  can use them. Good for gas, car washes, maintenance and the convenience of  buying snacks and drinks at any of our participating locations across Canada -  great when you\'re on the go. <br>Don\'t worry about cash when you have  your card on hand. For your convenience, use your Petro - Canada card at participating  Petro-Canada locations at the pump or with the attendant, and at Certigard Car  Repair Centres across Canada. </p>','Petro-Canada and Certigard Car Repair Centers are not affiliated with FiftyP and are not sponsors or co-sponsors with this promotion.','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/petroCanada.png'),
('Gap / Baby Gap / Gap Kids','<p>Gap  has everything you need to express your personal style. From jeans and T\'s to  khakis and oxfords, you\'ll find great clothes and accessories for men, women,  boys, girls and baby. Use your gift card at over 2000 Gap, GapKids, babyGap and  GapBody locations across Canada and the U.S. For the nearest store, call  1-800-GAP-STYLE, or shop our always open Gap.com store.</p>','<p>Unfortunately, gap.com does not accept  Gift Certificates as payment at this time.<br>Gap, GapKids, babyGap and GapBody �are not affiliated with FiftyP and are not  sponsors or co-sponsors with this promotion.</p>','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/gap.png'),
('La Senza','<p>Come discover the wonderful world of  fashion in a fun retail environment that fulfills your shopping needs. With  over 80 stores across Canada, La Senza Girl is the place for affordable,  high-style fashion, accessories and sleepwear for tweens. Visit one of our  lively stores and enjoy the great shopping atmosphere or shop online at  www.lasenzagirl.com.</p>Customer Service: 1888- La Senza','<p>Conditions: Gift cards are issued by La Senza Inc.  and are redeemable for merchandise only at any La Senza Girl, La Senza and La  Senza Express store locations in Canada. The La Senza Girl Gift  Cards cannot be redeemed for cash. The La Senza Girl Gift Cards cannot be  redeemed online. The La Senza Girl Gift Card is currency and is considered as  cash. It cannot be replaced if lost or stolen. La Senza Girl Gift Cards do not  expire.<br>La Senza Girl, La Senza and La Senza  Express are  not affiliated with FiftyP and are not sponsors or co-sponsors with this  promotion.</p>','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/laSenzaGirl.png'),
('Mark\'s Work Wearhouse','<p>Mark\'s Work Wearhouse has business  casual, weekend and work wear and offers accessories and footwear. These are  great for young men and women or as a gift for Moms and Dads across Canada. For  the industrial wear customer, Mark\'s offers the dependable safety, heavy duty  performance and comfort of Dakota. For the casual customer Mark\'s offers the  contemporary look of Denver Hayes and WindRiver. <br>Mark\'s has always been Canada\'s leader  in industrial work wear and now Mark\'s is Canada\'s leader in business casual  wear with several khaki styles to choose from, easy to coordinate tops, dressy  looking denim, and casual outerwear and footwear. It\'s comfortable, washable,  durable, and versatile. <br>Mark\'s Gift Cards can be redeemed at  any one of our 325 stores across Canada, and all purchases are  covered by our 100% customer satisfaction guarantee.</p>','Mark\'s Work Wearhouse is not affiliated with FiftyP and is not a sponsor or co-sponsor with this promotion.','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/marksWorkWearhouse.png'),
('Old Navy','<p>Shopping is fun again.<br>Old Navy has been offering fun,  fashion, and value since 1994. From streetwear to sleepwear, we\'ve got the newest styles and plenty of basics, too. The Old Navy Gift Certificate is a  great way to enjoy the Old Navy experience.<br>The Old Navy Gift Certificate is just like cash, only so much better.<br>� It\'s versatile! The perfect gift for  any occasion.<br>�It\'s valuable! Redeem it in any Old  Navy store - or be nice and give it to a friend.</p>Old Navy Gift Certificates are honored at all Old Navy stores. To find an Old Navy  store near you, visit oldnavy.com and click on our handy and helpful Store  Locator. Or call 1-800-OLD-NAVY.','<p>Please direct any inquiries or concerns  regarding your order to GiftCertificates.ca. Questions regarding Old Navy Gift  Certificates should be directed to 1-800-OLD-NAVY. Old Navy Gift Certificates  are redeemable for merchandise only. Unfortunately, oldnavy.com does not accept  Gift Certificates as payment at this time.</p>Old Navy is not  affiliated with FiftyP and is not a sponsor or co-sponsor with this promotion.','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/oldNavy.png'),
('Roots','<p>You\'ll always be in style when you shop  at ROOTS stores. There are so many products to choose from including the best  quality leathers, shoes, jackets, bags and luggage. You\'ll find something for everyone at ROOTS  Athletics, ROOTS Baby and ROOTS Kids Clothing. Finish off your look with style with accessories like fragrance,  jewellery and sunglasses.<br>ROOTS has been a producer of custom  merchandise for the sports and entertainment and has produced merchandise for  hundreds of films, television shows, sports teams, athletes and musical groups  and corporations. ROOTS is proud to be the official outfitter to the Canadian,  US and British Olympic Teams.</p>','ROOTS, ROOTS Athletics, ROOTS Baby and ROOTS Kids Clothing are not affiliated with FiftyP and are not sponsors or co-sponsors with this promotion.','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/roots.png'),
('Sunglass Hut','Sunglass Hut is all about style. We\'ve got the coolest shades by A-list designers like Ray-Ban&#174, Versace&#174, Arnette&#174, and Revo&#174. With over 1600 locations worldwide, you\'ll find a Sunglass Hut wherever the sun shines. Visit one of our stores today and find the perfect pair to complete your look. Find the store nearest you or shop online at sunglasshut.com.','Sunglass Hut is not affiliated with FiftyP and is not a sponsor or co-sponsor with this promotion.','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/sunglassHut.png'),
('Suzy Shier','<p>What\'s Suzy wearing? <br>It\'s fresh... it\'s new...it\'s  fashionable. Suzy Shier has a wide range of fashions for the modern active  woman. There\'s something to please everyone at a value that can\'t be beat. </p>Whether for you or as a gift, Suzie Shier always fits the occasion and  offers a great selection of must-have fashions.','<p>Gift certificates are available in $10  and $25 denominations. For the store location nearest you log on to www.suzyshier.com.<br>Suzy Shier is not affiliated with FiftyP and is not a  sponsor or co-sponsor with this promotion. </p>','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/suzyShier.png'),
('iTunes','<p>Get instant entertainment and keep on  rocking with iTunes. Shop at the music store that never closes! iTunes Gift Cards are perfect for  everyone who enjoys music. Each card features an iTunes Store code redeemable  for songs, TV shows, movies, audiobooks, and iPod games. Sync them to your iPod,  burn them to CD, or at listen at home on your computer. Discover the next big  things or rediscover old favourites. <br>Good for $15, $25, or $50 worth of  iTunes Store credit (note: denominations vary by retailer). Get a free iTunes  jukebox application for Mac or PC </p>','<p>The iTunes Store is available only to  persons age 13 or older in the U.S. and many other countries; see www.apple.com/itunes/download for a list of countries. Requires iTunes 6.0 or  later (7.0 or later for video), compatible hardware and software, and Internet  access (fees may apply). Terms apply. 2Video playback and iPod games require the fifth-generation iPod.<br>iTunes&#174 is a registered trademark of  Apple Inc. Apple is not a participant or sponsor of this program. </p>','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/iTunesCa.png'),
('Chapters','Use your Chapters gift cards at our stores where we have a huge selection of books, music and multimedia software. Kids of all ages will appreciate selecting their own titles among the Best Sellers, Business, Computing, Literature, Gardening, Cooking and more. Select any amount you want to use or to give; Chapters gift cards are available in denominations of $10, $25 and $50. Use you card at participating Indigo, Chapters, Coles, Smithbooks, World\'s Biggest Bookstore locations, or conveniently shop online.','<p>Conditions: <br>This gift card has no cash value. The  gift cards can only be redeemed at Indigo, Chapters, Coles, Smithbooks, World\'s  Biggest Bookstore locations and online.</p>Chapters, Indigo, Coles, Smithbooks and World\'s Biggest Bookstore are  not affiliated with FiftyP and are not sponsors or co-sponsors with this  promotion.','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/indigo.png'),
('Coles','Use your Coles gift cards at our stores where we have a huge selection of books, music and multimedia software. Kids of all ages will appreciate selecting their own titles among the Best Sellers, Business, Computing, Literature, Gardening, Cooking and more. Select any amount you want to use or to give; Coles gift cards are available in denominations of $10, $25 and $50. Use you card at participating Indigo, Chapters, Coles, Smithbooks, World\'s Biggest Bookstore locations, or conveniently shop online.','<p>Conditions: <br>This gift card has no cash value. The  gift cards can only be redeemed at Indigo, Chapters, Coles, Smithbooks, World\'s  Biggest Bookstore locations and online.<br>Chapters, Indigo, Coles, Smithbooks and  World\'s Biggest Bookstore are not affiliated with FiftyP and are not  sponsors or co-sponsors with this promotion. </p>','This Gift Card is in the mail within 48 hours of your parent\'s approval. It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/indigo.png'),
('Indigo','Use your Indigo gift cards at our stores where we have a huge selection of books, music and multimedia software. Kids of all ages will appreciate selecting their own titles among the Best Sellers, Business, Computing, Literature, Gardening, Cooking and more. Select any amount you want to use or to give; Indigo gift cards are available in denominations of $10, $25 and $50. Use you card at participating Indigo, Chapters, Coles, Smithbooks, World\'s Biggest Bookstore locations, or conveniently shop online.','<p>Conditions: <br>This gift card has no cash value. The  gift cards can only be redeemed at Indigo, Chapters, Coles, Smithbooks, World\'s  Biggest Bookstore locations and online.<br>Chapters, Indigo, Coles, Smithbooks and  World\'s Biggest Bookstore are not affiliated with FiftyP and are not  sponsors or co-sponsors with this promotion. </p>','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/indigo.png'),
('HMV','Everyone loves music! HMV gift cards are a great way to shop a huge selection of movies and music at all 96 HMV locations throughout Canada. Come sample a CD in our listening lounge, or place a special order for that tune you\'re trying to find. It\'s a fun experience and HMV customers keep coming back. Want to shop online? Visit www.HMV.com, the World\'s Best Music Store online, for over 300,000 CDs, Videos, and DVDs.','<p>HMV gift cards are non-redeemable for  cash. Cards must have register validation. HMV is not responsible for theft or  loss. Redeemable for merchandise at any HMV Canada location only.<br>HMV is not affiliated  with FiftyP and is not a sponsor or co-sponsor with this promotion. </p>','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/hmv.png'),
('Best Buy','<p>Best Buy Gift Cards are great for  anyone! Best Buy wants your shopping to be fun, with lots of things to try out  while you shop. Take your time, we won\'t pressure you. Best buy has lots of the  latest music CDs, and �DVD movies. Like  games? Check out the selection of computer and video games at one our stores.� Saving up for something bigger? We also have brand  name Home Theatre, Home Office, Digital Audio, and Wireless Communications - all  backed by our low price guarantee so you can get the best buy.<br>Gift Cards are available in various  denominations, have no expiration date and no fees. Use your Best Buy Gift Card  at any Best Buy store location across Canada. For a store near you, visit www.bestbuy.ca</p>','Best Buy is not affiliated with FiftyP and is not a sponsors or co-sponsor with this promotion.','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/bestBuy.png'),
('Future Shop','<p>Get what you really want with a Future  Shop Gift Card. Future Shop has the latest electronics for the digital age.  From music CDs, DVD movies and games, to televisions, computers, and digital  cameras, we have the cool stuff you want. With so much to choose from you can  get something for yourself or the perfect gift for someone else. <br>Use your gift card for any merchandise  at Future Shop locations. They never expire and you can reload your card so you  can use it over and over and forget the hassle of cash. Redeem any remaining  value on you card at any time. <br>For more information about Future Shop  and our store locations, visit us online at www.futureshop.ca.</p>','Future Shop is not affiliated with FiftyP and is not a sponsors or co-sponsor with this promotion.','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/futureShop.png'),
('Black\'s Photography','<p>Black\'s Photo Corporation has the  latest in photofinishing and with our technology we can do even more with your  film, digital media and pictures that you already have. <br>Our <strong>VividPrints</strong> technology can read detail on your negative that other  systems can\'t see. You\'ll see the difference in how rich the colours are, the  detail of the highlights and shadows, the sharpness of the image. You get a  print that looks just like what you saw. <br>Whether you\'re a budding photographer  or just like to take pictures for fun, we\'ve got products and services from  cameras and frames to photofinishing. Use your gift card for whatever you need  and share the memories with your friends and family. Use it like cash at any  Black\'s or Astral store across Canada.</p>','<p>Conditions: Gift Cards are void if  altered or defaced, and cannot be replaced if lost or stolen. This card is not  a credit card or debit card. This card can be used one time for the amount  indicated on the card; any difference between the purchase price of the item  and the amount of the card will be refunded in cash. Black\'s cannot replace  cards if lost or stolen. Gift Cards will expire after two years from activation date.<br><strong>Disclaimer:</strong> Black\'s Photo Corporation and Astral are not  affiliated with FiftyP and are not sponsors or co-sponsors with this promotion. </p>','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/blacks.png'),
('Blockbuster','<p>They\'re  simple, they hold the change, and they fit into your pocket! Get happy about  where you spend allowance with BLOCKBUSTER&reg; GiftCards. <br>You can use the BLOCKBUSTER GiftCard&trade;  just like cash at BLOCKBUSTER&reg; stores right across Canada. They can be used to buy or  rent movies and games, and for accessories, snacks and more. With the  BLOCKBUSTER GiftCard&trade;, you can get it all. Give the Gift of Entertainment!&trade; </p>BLOCKBUSTER is Canada\'s  leader in rentable home entertainment and has over 350 stores across Canada.','<p>Canadian BLOCKBUSTER GiftCards&trade; can  only be used in Canada.  GiftCards cannot be used to purchase other GiftCards. Membership rules apply  for rentals. BLOCKBUSTER name, design and related marks are trademarks of  Blockbuster Inc. &copy; 1999 Blockbuster Inc. <br>All Rights Reserved.<br>BLOCKBUSTER is not affiliated  with FiftyP and is not a sponsor or co-sponsor with this promotion.</p>','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/blockbuster.png'),
('Cineplex Entertainment','Everyone loves the movies! Cineplex Entertainment gift cards offer the perfect solution for a great movie-going experience all throughout the year! Gift cards are available in $10, $25 and $50 denominations and can be used toward movie tickets and your favourites at the concession stand. Cineplex Entertainment gift cards are valid at our theatres throughout Canada: Famous Players, Cineplex Odeon and Galaxy Cinemas.','Cineplex Entertainment, Famous Players, Cineplex Odeon, and Galaxy Cinemas are not affiliated with FiftyP and are not sponsors or co-sponsors with this promotion.','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/cineplex.png'),
('Galaxy Cinemas','Everyone loves the movies! Cineplex Entertainment gift cards offer the perfect solution for a great movie-going experience all throughout the year! Gift cards are available in $10, $25 and $50 denominations and can be used toward movie tickets and your favourites at the concession stand. Cineplex Entertainment gift cards are valid at our theatres throughout Canada: Famous Players, Cineplex Odeon and Galaxy Cinemas.','Cineplex Entertainment, Famous Players, Cineplex Odeon, and Galaxy Cinemas are not affiliated with FiftyP and are not sponsors or co-sponsors with this promotion.','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/galaxy.png'),
('Birks','<p>Birks is Canada\'s most respected, premier  designer and manufacturer of fine jewellery, timepieces, sterling silverware  and gifts. With Birks history of trust, uncompromising quality and courteous  service we offer historical references of the past and an innovative, dynamic  and sharp focus on the future. <br>Whether it\'s something for you or a  gift for someone else, use your Birks gift card at 39 stores from coast to coast  to meet your shopping needs. �</p>','Birks is not affiliated with FiftyP and is not a sponsor or co-sponsor with this promotion.','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/birks.png'),
('Elmwood Spa','<p>Whether for you or a gift for someone  else, Elmwood Spa is a complete urban spa for the ultimate in stress relief and  relaxation. It\'s a great place to gather with friends, to celebrate, or your  very own place for stress relief and to chill - out.<br>Elmwood Spa is located in a landmark  historic building in downtown Toronto. A multi-million dollar renewal has  transformed it into a modern oasis for your health and well-being with two  restaurants, a juice bar, 34 treatment rooms, luxurious change rooms with  expanded amenities. There are also water therapies, including swimming pool,  whirlpool and steam rooms. Come let us cater to you and get rejuvenated from  head to toe.</p>','Elmwood Spa is not affiliated with FiftyP and is not a sponsor or co-sponsor with this promotion.','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/elmwoodSpa.png'),
('SpaFinder','SpaFinder is the ultimate reward for your or as a gift for someone else! Unwind, relax and renew mind & body with a choice of pampering experiences! Use the Spa Finder Gift Certificate to combine resort spa with travel and go somewhere you have always dreamed about! Indulge in delicious spa cuisine. Enjoy the benefits of rejuvenation procedures at one of our Medical Spas or schedule a massage and facial at your favourite Day Spa. Jumpstart plans of a new fabulous you at one of our weight loss destination spas. This is the luxury chance of a lifetime! Spa your stress away! Spa Finder Gift Certificates are redeemable at premier spas all across Canada.','SpaFinder is not affiliated with FiftyP and is not a sponsor or co-sponsor with this promotion.','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/spaFinder.png'),
('WaySpa','<p>WaySpa gift cards provide access to  some of the world\'s most luxurious spas, and with time-saving convenience! Use  them to Indulge and pamper yourself or someone else with a choice of thousands  of rejuvenating spas available across Canada, the US, Mexico, the Caribbean and  more. New spas are added every day! Save time and use them to book delectable  spa treatments and vacations, weekend getaways, or unique spa packages at  Wayspa.com or by calling 1-800-929-7723. Comes complete with your own personal  concierge service. An experience as pampering as the spa itself! <br>Features: Instant currency conversion  available online. Book online at www.WaySpa.com or call 1-800-WAYSPA3  (929-7723). Never expires and No restrictions</p>','WaySpa is not affiliated with FiftyP and is not a sponsor or co-sponsor with this promotion.','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/waySpa.png'),
('Canadian Tire','With over 440 Canadian Tire stores, 400 service centres and over 200 gas bars across Canada, Canadian Tire gift cards are the simple solution for your needs. Whether for you or someone else, with over 95,000 items in stock ranging from tires to toasters, lawn furniture to skates in every Canadian Tire store, everyone will find something they love. Canadian Tire gift cards offer a unique bonus when redeemed- Canadian Tire \'Money\'&trade;.','Canadian Tire is not affiliated with FiftyP and is not a sponsor or co-sponsor with this promotion.','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/canadianTire.png'),
('Pottery Barn Kids','Pottery Barn Kids has a great selection of children\'s furnishings and accessories with that Pottery Barn look and feel that you\'ve come to know. Designed with quality, value, safety and style, our selection includes exceptional pieces for children\'s bedrooms, playrooms, nurseries and family areas. From sturdy cribs to cozy kids\' bedding, we have everything kids  need to create a comfortable, coordinated space.','<p>Terms &amp; Conditions: </p><ol><li><span dir="LTR"> </span>Gift card is redeemable for Merchandise Only and cannot be  replaced if lost or stolen.</li><li>Gift card does not  expire.</li><li>Gift card may be redeemed in Canadian retail stores only. Certificate may also  be redeemed for purchases at Williams-Sonoma stores across Canada.</li><li>Gift card cannot be redeemed via the catalogues, or via phone orders.</li><li>Gift card cannot be redeemed via the Internet.</li><li>Redemption is permanent and non-returnable.</li><li>Gift card cannot be redeemed in the United States.</li></ol><p><strong>Disclaimer:</strong> Pottery Barn, Pottery Barn Kids and  Williams-Sonoma are not affiliated with FiftyP and are not sponsors  or co-sponsors with this promotion.</p>','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/potteryBarnKids.png'),
('East Side Mario\'s','At East Side Mario\'s Restaurants there is always more to make you sing! All of our entrees come with complimentary unlimited soup or salad and garlic homeloaf. Throughout the country, East Side Mario\'s guests rave over dishes such as the Linguine Chicken Tetrazzini and the Firecracker Shrimp Bowties. For people with a passion for life and great food, there\'s no place like East Side Mario\'s. Conveniently use your gift card at participating East Side Mario\'s.','East Side Mario\'s is not affiliated with FiftyP and is not a sponsor or co-sponsor with this promotion.','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/eastSideMarios.png'),
('Olive Garden','Olive Garden delights guests with a genuine Italian dining experience, featuring a range of fresh, simple and delicious dishes, including many inspired by our Culinary Institute of Tuscany in Italy, and an award-winning wine list.  For the restaurant nearest you, please visit us at www.olivegarden.com ','Olive Garden is not affiliated with FiftyP and is not a sponsor or co-sponsor with this promotion.','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/oliveGarden.png'),
('Red Lobster','<p>Red Lobster&reg; <br>Red Lobster is America\'s favourite  seafood restaurant.� It offers a wide  variety of freshly-prepared dishes, including fresh fish, shrimp, crab, and  live Maine lobster.� For the restaurant  nearest you call 1-800-LOBSTER or visit www.redlobster.com</p>','Red Lobster is not affiliated with FiftyP and is not a sponsors or co-sponsor with this promotion.','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/redLobster.png'),
('Kernels Popcorn','<p>Everyone loves popcorn...<br>Eat it naked.� Eat it sweet.�  Eat it seasoned.� Eat it with the  flavour cranked up to the max!� The card  that turns into Kernels extraordinary popcorn.�  The fun, delicious and entertaining gift that has great taste!<br>Celebrating 20 years in the bag,  Kernels Popcorn is Canada\'s  #1 gourmet popcorn chain.� Use your  Kernels Popcorn plastic card at all our retail store locations across Canada.� Check us out at www.kernelspopcorn.com.<br>Kernels Popcorn gift cards are  available for $10.00 each.� These  electronic gift cards can be used once, twice or as many times as you have  cravings by reloading them at all of our locations.</p>','<p>Conditions: <br>Kernels Popcorn Plastic Cards are not  redeemable for cash. Kernels Popcorn is not responsible for theft or loss. To  guarantee card value register your card online at www.kernelspopcorn.com.<br>Kernels Popcorn is not affiliated  with FiftyP and is not a sponsors or co-sponsor with this promotion.</p>','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/kernels.png'),
('Laura Secord','<p>Laura Secord has been making great  chocolate for over 90 years. Our chocolates are still made with time-honoured  recipes, and use only the finest ingredients to make some of the best in the  world.<br>Lots of families celebrate with Laura -  from Secord Easter Eggs at Easter, to Miniature Assorted Chocolates at  Christmas, and French &amp; Frosted Mints anytime! Laura Secord also offers  decadent truffles, fresh roasted nuts, and premium ice cream to indulge you  with. Visit one of our 160 stores across Canada for a great treat. For nearest  location please visit www.Laurasecord.ca</p>','Laura Secord  is not affiliated with FiftyP and is not a sponsors or co-sponsor with this promotion','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/lauraSecord.png'),
('Foot Locker','<p>Foot Locker, the leading athletic  retailer in footwear and apparel, carries selections from the best brands in  the business, including; Puma, Adidas, Nike, Timberland, K-Swiss, Converse etc.  Foot Locker carries a large selection of exclusive product that can\'t be found  at other athletic stores. <br>Our store staff knows all about the  latest technologies and trends and they will make your shopping experience fun. <br>Use your Footlocker gift card to get  just what you are looking for or as an easy way to give a gift to someone else.  The card is available in any denomination and is valid at all locations in Canada and the US. For Canadian store locations, visit footlocker.ca. </p>','<p>Foot Locker Gift Cards are redeemable  for merchandise only.<br>Foot Locker is not affiliated  with FiftyP and is not a sponsors or co-sponsor with this promotion.</p>','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/footLockerCa.png'),
('SportChek','<p>SportChek has been around for 25 years  and has grown into the largest retailer of its kind in Canada. "Chek" out our clothing,  shoes, hockey gear, racquets, team sports equipment, and outerwear all  available year round. We have seasonal items for golf, in-line skates, bikes,  ski, and snowboards. Sport Chek also has a reputation for carrying the best  brands in the business like Nike, Adidas, Rossignol, Salomon, CCM, and Bauer, all  at the very best value. <br>SportChek\'s new stores are unique in  the Sports Retailing business. You\'ll be amazed by our new layout as technology  and innovation promise to add excitement to the SportChek experience. What\'s  more, Sport Chek is known for its outstanding customer service by knowledgeable friendly staff.</p>','SportChek is not affiliated with FiftyP and is not a sponsors or co-sponsor with this promotion.','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/sportChek.png'),
('SportMart','<p>SportMart is one of Canada\'s largest  and fastest growing sporting goods chains offering brand name gear at guaranteed  lowest prices. SportMart carries footwear, sportswear, outerwear, skis,  snowboards, hockey, bikes, in-line skates, golf and more. <br>Sport Mart opened its first store in  1984 and has stores in British Columbia, Alberta, Saskatchewan, Manitoba, and Ontario  as well as online service at www.sportmart.ca. Sport Mart is a subsidiary of  the Forzani Group Ltd.</p>','SportMart is not affiliated with FiftyP and is not a sponsors or co-sponsor with this promotion.','This Gift Card is in the mail within 48 hours of your parent\'s approval.  It should arrive within 5 to 10 days.<br><br>ENJOY!!','giftCards/canada/sportMart.png');

select @productCategoryId:=(select product_category_id from product_category where name = "Groove'n");

select @productDescriptionId:=(select product_description_id from product_description where name = "Best Buy");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,25,@productDescriptionId,'CA',1.92,279),
(@productCategoryId,50,@productDescriptionId,'CA',1.92,280),
(@productCategoryId,100,@productDescriptionId,'CA',1.92,281);

select @productDescriptionId:=(select product_description_id from product_description where name = "Chapters");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,10,@productDescriptionId,'CA',1.92,122),
 (@productCategoryId,25,@productDescriptionId,'CA',1.92,22),
 (@productCategoryId,50,@productDescriptionId,'CA',1.92,23);

select @productDescriptionId:=(select product_description_id from product_description where name = "Coles");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,10,@productDescriptionId,'CA',1.92,142),
 (@productCategoryId,25,@productDescriptionId,'CA',1.92,143),
 (@productCategoryId,50,@productDescriptionId,'CA',1.92,144);

select @productDescriptionId:=(select product_description_id from product_description where name = "Indigo");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,10,@productDescriptionId,'CA',1.92,145),
 (@productCategoryId,25,@productDescriptionId,'CA',1.92,45),
 (@productCategoryId,50,@productDescriptionId,'CA',1.92,46);

select @productDescriptionId:=(select product_description_id from product_description where name = "Cineplex Entertainment");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,10,@productDescriptionId,'CA',1.92,25),
 (@productCategoryId,25,@productDescriptionId,'CA',1.92,208),
 (@productCategoryId,50,@productDescriptionId,'CA',1.92,171);

select @productDescriptionId:=(select product_description_id from product_description where name = "Galaxy Cinemas");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,25,@productDescriptionId,'CA',1.92,327),
 (@productCategoryId,50,@productDescriptionId,'CA',1.92,328);

select @productDescriptionId:=(select product_description_id from product_description where name = "Future Shop");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,25,@productDescriptionId,'CA',1.92,37),
 (@productCategoryId,50,@productDescriptionId,'CA',1.92,38),
 (@productCategoryId,100,@productDescriptionId,'CA',1.92,39);

select @productDescriptionId:=(select product_description_id from product_description where name = "HMV");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,25,@productDescriptionId,'CA',1.92,40),
 (@productCategoryId,50,@productDescriptionId,'CA',1.92,41);

select @productDescriptionId:=(select product_description_id from product_description where name = "SportChek");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,10,@productDescriptionId,'CA',1.92,197),
 (@productCategoryId,25,@productDescriptionId,'CA',1.92,72),
 (@productCategoryId,50,@productDescriptionId,'CA',1.92,73),
 (@productCategoryId,100,@productDescriptionId,'CA',1.92,74);

select @productDescriptionId:=(select product_description_id from product_description where name = "SportMart");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,25,@productDescriptionId,'CA',1.92,204),
 (@productCategoryId,50,@productDescriptionId,'CA',1.92,205);

select @productDescriptionId:=(select product_description_id from product_description where name = "Sunglass Hut");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,10,@productDescriptionId,'CA',1.92,282),
 (@productCategoryId,25,@productDescriptionId,'CA',1.92,283),
 (@productCategoryId,50,@productDescriptionId,'CA',1.92,284);

select @productCategoryId:=(select product_category_id from product_category where name = "Shop'n");

select @productDescriptionId:=(select product_description_id from product_description where name = "Best Buy");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,25,@productDescriptionId,'CA',1.92,279),
(@productCategoryId,50,@productDescriptionId,'CA',1.92,280),
(@productCategoryId,100,@productDescriptionId,'CA',1.92,281);

select @productDescriptionId:=(select product_description_id from product_description where name = "Birks");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
 values (@productCategoryId,50,@productDescriptionId,'CA',1.92,293),
(@productCategoryId,100,@productDescriptionId,'CA',1.92,294);

/**/

select @productDescriptionId:=(select product_description_id from product_description where name = "Chapters");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,10,@productDescriptionId,'CA',1.92,122),
 (@productCategoryId,25,@productDescriptionId,'CA',1.92,22),
 (@productCategoryId,50,@productDescriptionId,'CA',1.92,23);

select @productDescriptionId:=(select product_description_id from product_description where name = "Coles");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,10,@productDescriptionId,'CA',1.92,142),
 (@productCategoryId,25,@productDescriptionId,'CA',1.92,143),
 (@productCategoryId,50,@productDescriptionId,'CA',1.92,144);

select @productDescriptionId:=(select product_description_id from product_description where name = "Indigo");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,10,@productDescriptionId,'CA',1.92,145),
 (@productCategoryId,25,@productDescriptionId,'CA',1.92,45),
 (@productCategoryId,50,@productDescriptionId,'CA',1.92,46);

select @productDescriptionId:=(select product_description_id from product_description where name = "Future Shop");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,25,@productDescriptionId,'CA',1.92,37),
 (@productCategoryId,50,@productDescriptionId,'CA',1.92,38),
 (@productCategoryId,100,@productDescriptionId,'CA',1.92,39);



select @productDescriptionId:=(select product_description_id from product_description where name = "HMV");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,25,@productDescriptionId,'CA',1.92,40),
 (@productCategoryId,50,@productDescriptionId,'CA',1.92,41);

select @productDescriptionId:=(select product_description_id from product_description where name = "Kernels Popcorn");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,25,@productDescriptionId,'CA',1.92,199);


select @productDescriptionId:=(select product_description_id from product_description where name = "Laura Secord");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,25,@productDescriptionId,'CA',1.92,271),
 (@productCategoryId,50,@productDescriptionId,'CA',1.92,272);

/**/

select @productDescriptionId:=(select product_description_id from product_description where name = "Old Navy");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,10,@productDescriptionId,'CA',1.92,99),
 (@productCategoryId,25,@productDescriptionId,'CA',1.92,59);

select @productDescriptionId:=(select product_description_id from product_description where name = "Pottery Barn Kids");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,25,@productDescriptionId,'CA',1.92,240),
 (@productCategoryId,50,@productDescriptionId,'CA',1.92,241),
 (@productCategoryId,100,@productDescriptionId,'CA',1.92,242);

select @productDescriptionId:=(select product_description_id from product_description where name = "Roots");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,10,@productDescriptionId,'CA',1.92,69),
 (@productCategoryId,25,@productDescriptionId,'CA',1.92,70),
 (@productCategoryId,50,@productDescriptionId,'CA',1.92,71);

select @productDescriptionId:=(select product_description_id from product_description where name = "SportChek");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,10,@productDescriptionId,'CA',1.92,197),
 (@productCategoryId,25,@productDescriptionId,'CA',1.92,72),
 (@productCategoryId,50,@productDescriptionId,'CA',1.92,73),
 (@productCategoryId,100,@productDescriptionId,'CA',1.92,74);

select @productDescriptionId:=(select product_description_id from product_description where name = "SportMart");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,25,@productDescriptionId,'CA',1.92,204),
 (@productCategoryId,50,@productDescriptionId,'CA',1.92,205);

select @productCategoryId:=(select product_category_id from product_category where name = "Eat'n");

select @productDescriptionId:=(select product_description_id from product_description where name = "Cineplex Entertainment");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,10,@productDescriptionId,'CA',1.92,25),
 (@productCategoryId,25,@productDescriptionId,'CA',1.92,208),
 (@productCategoryId,50,@productDescriptionId,'CA',1.92,171);

select @productDescriptionId:=(select product_description_id from product_description where name = "Galaxy Cinemas");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
 values (@productCategoryId,25,@productDescriptionId,'CA',1.92,327),
 (@productCategoryId,50,@productDescriptionId,'CA',1.92,328);

select @productDescriptionId:=(select product_description_id from product_description where name = "Kernels Popcorn");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,25,@productDescriptionId,'CA',1.92,199);

select @productDescriptionId:=(select product_description_id from product_description where name = "Laura Secord");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,25,@productDescriptionId,'CA',1.92,271),
 (@productCategoryId,50,@productDescriptionId,'CA',1.92,272);

select @productDescriptionId:=(select product_description_id from product_description where name = "Olive Garden ");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,10,@productDescriptionId,'CA',1.92,58),
 (@productCategoryId,25,@productDescriptionId,'CA',1.92,139),
 (@productCategoryId,50,@productDescriptionId,'CA',1.92,155);

select @productDescriptionId:=(select product_description_id from product_description where name = "Red Lobster");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,25,@productDescriptionId,'CA',1.92,138),
 (@productCategoryId,50,@productDescriptionId,'CA',1.92,176);

select @productCategoryId:=(select product_category_id from product_category where name = "Wear'n");

select @productDescriptionId:=(select product_description_id from product_description where name = "Birks");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,50,@productDescriptionId,'CA',1.92,293),
(@productCategoryId,100,@productDescriptionId,'CA',1.92,294);

select @productDescriptionId:=(select product_description_id from product_description where name = "Gap");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,25,@productDescriptionId,'CA',1.92,1),
 (@productCategoryId,50,@productDescriptionId,'CA',1.92,2);


select @productDescriptionId:=(select product_description_id from product_description where name = "Old Navy");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,10,@productDescriptionId,'CA',1.92,99),
 (@productCategoryId,25,@productDescriptionId,'CA',1.92,59);

select @productDescriptionId:=(select product_description_id from product_description where name = "Pottery Barn Kids");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,25,@productDescriptionId,'CA',1.92,240),
 (@productCategoryId,50,@productDescriptionId,'CA',1.92,241),
 (@productCategoryId,100,@productDescriptionId,'CA',1.92,242);

select @productDescriptionId:=(select product_description_id from product_description where name = "Roots");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,10,@productDescriptionId,'CA',1.92,69),
 (@productCategoryId,25,@productDescriptionId,'CA',1.92,70),
 (@productCategoryId,50,@productDescriptionId,'CA',1.92,71);

select @productDescriptionId:=(select product_description_id from product_description where name = "SportChek");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,10,@productDescriptionId,'CA',1.92,197),
 (@productCategoryId,25,@productDescriptionId,'CA',1.92,72),
 (@productCategoryId,50,@productDescriptionId,'CA',1.92,73),
 (@productCategoryId,100,@productDescriptionId,'CA',1.92,74);

select @productDescriptionId:=(select product_description_id from product_description where name = "SportMart");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,25,@productDescriptionId,'CA',1.92,204),
 (@productCategoryId,50,@productDescriptionId,'CA',1.92,205);

select @productDescriptionId:=(select product_description_id from product_description where name = "Sunglass Hut");
insert into product (product_category_id,price,product_description_id,country_code,shipping_handling_cost,sku_name)
values (@productCategoryId,10,@productDescriptionId,'CA',1.92,282),
 (@productCategoryId,25,@productDescriptionId,'CA',1.92,283),
 (@productCategoryId,50,@productDescriptionId,'CA',1.92,284);


INSERT INTO sys_template (sys_template_id, description, design, subject) VALUES
('CANCELLATION_ACCOUNT_NOTIFICATION', 'Email template for account cancellation notification','<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd">\r\n<html>\r\n<head>\r\n<title>FiftyP</title>\r\n<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">\r\n</head>\r\n<body>\r\n<table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #7B2B83">\r\n  <tr>\r\n    <td style="border-bottom:1px solid #7B2B83">\r\n      <table width="100%" border="0">\r\n        <tr>\r\n          <td><img src="cid:logo_parent.gif" width="294" height="84"></td>\r\n          <td align="right" style="padding:55px 10px 0px 0px" ><font color="#F68B1F" size="2" style="font-size:14px;" face="verdana"><b>\r\n			FiftyP account cancellation notification!\r\n		  </b></font></td>\r\n        </tr>\r\n    </table></td>\r\n  </tr>\r\n  <tr>\r\n    <td style="padding:20px;font-size:12px; font-family:verdana;">\r\n	Dear FiftyP Parent,<br/><br/>  We received your request to cancel your family''s FiftyP account as of ${cancellationDate?string("MMMM d, yyyy")}. We''re sorry to see you go! We trust that your experience with FiftyP has helped put your family on the path to financial fitness.  \r\n	<br/><br/>	Beginning today you will no longer be able to log in to FiftyP or to access your account information. Please note that because half our profits are donated to charitable causes there can be no refunds.<br/><br/> Should you wish to reinstate your membership, please contact us by ${reinstateDate?string("MMMM d, yyyy")}  (ie, within 30 days) at <a href=''http://www.fiftyp.com''>support@fiftyp.com</a>. After that date your account information will be permanently deleted. <br/><br/>\r\n	In times like these it''s hard to minimize the value of teaching our kids to be financially and socially responsible. We hope you''ll reconsider FiftyP if you find you need support as you work toward these goals.\r\n	<br/><br/>You''re always welcome back to the FiftyP family!  <br/><br/>\r\n	With best wishes,<br>\r\n			The FiftyP Team<br>\r\n			<a href=''http://www.fiftyp.com''>www.fiftyp.com</a><br>\r\n	  </p>\r\n	</td>\r\n  </tr>\r\n  <tr>\r\n    <td bgcolor="#7B2B83" style="padding:5px"> <font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">For more information please contact our support team at </font><a href=''http://www.fiftyp.com''><font  style="font-size:11px; line-height:16px" face="verdana" color="#ffffff">support@fiftyp.com</font></a><br>\r\n    </td>\r\n  </tr>\r\n</table>\r\n\r\n</body>', 'FiftyP account cancellation notification');
